export interface NombreHebreo {
  hebreo: string
  nombre: string          // Castellanizado común
  transliteracion: string // Sefardí
  aliases: string[]       // Para búsqueda: fonética, variantes, sin acentos
  significado: string
  genero: 'M' | 'F'
  categoria: string
  referencia: string
}

export const nombresHebreos: NombreHebreo[] = [
  // ==================== PATRIARCAS ====================
  {
    hebreo: 'אָדָם',
    nombre: 'Adán',
    transliteracion: 'Adam',
    aliases: ['adam', 'adán', 'adam', 'adamah', 'אדם', 'אָדָם'],
    significado: '"Hombre" o "De la tierra" (adamah). El primer ser humano, creado a imagen del Eterno.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 2',
  },
  {
    hebreo: 'שֵׁת',
    nombre: 'Set',
    transliteracion: 'Shet',
    aliases: ['shet', 'set', 'seth', 'שת', 'שֵׁת'],
    significado: '"Compensación" o "Puesto". Tercer hijo de Adán y Eva.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 4',
  },
  {
    hebreo: 'אֱנוֹשׁ',
    nombre: 'Enós',
    transliteracion: 'Enosh',
    aliases: ['enosh', 'enós', 'enos', 'אנוש', 'אֱנוֹשׁ'],
    significado: '"Hombre" o "Mortal". Hijo de Set, nieto de Adán.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 4',
  },
  {
    hebreo: 'קֵינָן',
    nombre: 'Cainán',
    transliteracion: 'Kenan',
    aliases: ['kenan', 'cainán', 'cainan', 'קינן', 'קֵינָן'],
    significado: '"Adquirido" o "Posesión". Hijo de Enós.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 5',
  },
  {
    hebreo: 'מַהֲלַלְאֵל',
    nombre: 'Mahalaleel',
    transliteracion: 'Mahalalel',
    aliases: ['mahalalel', 'mahalaleel', 'מהללאל', 'מַהֲלַלְאֵל'],
    significado: '"Alabanza de Dios". Hijo de Cainán.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 5',
  },
  {
    hebreo: 'יֶרֶד',
    nombre: 'Jared',
    transliteracion: 'Yered',
    aliases: ['yered', 'jared', 'iered', 'ירד', 'יֶרֶד'],
    significado: '"Descenso" o "Descender". Hijo de Mahalaleel.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 5',
  },
  {
    hebreo: 'חֲנוֹךְ',
    nombre: 'Enoc',
    transliteracion: 'Janokh',
    aliases: ['janokh', 'enoc', 'henoch', 'henoc', 'חנוך', 'חֲנוֹךְ'],
    significado: '"Inaugurado" o "Dedicado". Caminó con Dios y fue llevado al cielo.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 5',
  },
  {
    hebreo: 'מְתוּשֶׁלַח',
    nombre: 'Matusalén',
    transliteracion: 'Metushelaj',
    aliases: ['metushelaj', 'matusalén', 'methuselah', 'מתושלח', 'מְתוּשֶׁלַח'],
    significado: '"Cuando muera, será enviado" (el diluvio). El hombre más longevo.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 5',
  },
  {
    hebreo: 'לֶמֶךְ',
    nombre: 'Lamec',
    transliteracion: 'Lemekh',
    aliases: ['lemekh', 'lamec', 'lamech', 'למך', 'לֶמֶךְ'],
    significado: '"Poderoso" o "El que subyuga". Padre de Noé.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 5',
  },
  {
    hebreo: 'נֹחַ',
    nombre: 'Noé',
    transliteracion: 'Noaj',
    aliases: ['noaj', 'noah', 'noe', 'noé', 'noach', 'נח', 'נֹחַ'],
    significado: '"Descanso" o "Consuelo". Justo que construyó el arca y salvó a la humanidad del diluvio.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 6',
  },
  {
    hebreo: 'שֵׁם',
    nombre: 'Sem',
    transliteracion: 'Shem',
    aliases: ['shem', 'sem', 'shem', 'שם', 'שֵׁם'],
    significado: '"Nombre" o "Fama". Hijo de Noé, ancestro de los semitas.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 6',
  },
  {
    hebreo: 'חָם',
    nombre: 'Cam',
    transliteracion: 'Jam',
    aliases: ['jam', 'cam', 'ham', 'חם', 'חָם'],
    significado: '"Caliente" o "Negro". Hijo de Noé, padre de Canaán.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 6',
  },
  {
    hebreo: 'יֶפֶת',
    nombre: 'Jafet',
    transliteracion: 'Yefet',
    aliases: ['yefet', 'jafet', 'japheth', 'יפת', 'יֶפֶת'],
    significado: '"Hermoso" o "Expandido". Hijo de Noé, ancestro de los pueblos indoeuropeos.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 6',
  },
  {
    hebreo: 'עֵבֶר',
    nombre: 'Éber',
    transliteracion: 'Ever',
    aliases: ['ever', 'éber', 'eber', 'עבר', 'עֵבֶר'],
    significado: '"El que pasa" o "Transmisor". Ancestro de Abraham y de los hebreos.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 10',
  },
  {
    hebreo: 'פֶּלֶג',
    nombre: 'Peleg',
    transliteracion: 'Peleg',
    aliases: ['peleg', 'peleg', 'פלג', 'פֶּלֶג'],
    significado: '"División" o "Canal". En sus días se dividió la tierra.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 10',
  },
  {
    hebreo: 'רְעוּ',
    nombre: 'Reú',
    transliteracion: "Re'u",
    aliases: ['reu', 'reú', 'rehu', 'רעו', 'רְעוּ'],
    significado: '"Amigo" o "Pastor". Ancestro de Abraham.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 11',
  },
  {
    hebreo: 'שְׂרוּג',
    nombre: 'Serug',
    transliteracion: 'Serug',
    aliases: ['serug', 'serug', 'שרוג', 'שְׂרוּג'],
    significado: '"Vástago" o "Tendón". Ancestro de Abraham.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 11',
  },
  {
    hebreo: 'נָחוֹר',
    nombre: 'Nahor',
    transliteracion: 'Najor',
    aliases: ['najor', 'nahor', 'nakhor', 'נחור', 'נָחוֹר'],
    significado: '"Resoplido" o "Ronquido". Abuelo de Abraham.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 11',
  },
  {
    hebreo: 'תֶּרַח',
    nombre: 'Téraj',
    transliteracion: 'Teraj',
    aliases: ['teraj', 'téraj', 'terah', 'תרח', 'תֶּרַח'],
    significado: '"Estación" o "Caminante". Padre de Abraham.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 11',
  },
  {
    hebreo: 'אַבְרָהָם',
    nombre: 'Abraham',
    transliteracion: 'Avraham',
    aliases: ['avraham', 'abraham', 'abran', 'avram', 'אברהם', 'אַבְרָהָם'],
    significado: '"Padre de multitudes". Primer patriarca, quien dejó Ur para seguir al Eterno.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 12',
  },
  {
    hebreo: 'יִצְחָק',
    nombre: 'Isaac',
    transliteracion: 'Yitzjak',
    aliases: ['yitzjak', 'yitzhak', 'itzjak', 'itzjak', 'isaac', 'isaak', 'יצחק', 'יִצְחָק'],
    significado: '"Se reirá". Hijo de Abraham y Sara, patriarca que continuó el pacto.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 21',
  },
  {
    hebreo: 'יִשְׁמָעֵאל',
    nombre: 'Ismael',
    transliteracion: 'Yishmael',
    aliases: ['yishmael', 'ismael', 'ishmael', 'ישמעאל', 'יִשְׁמָעֵאל'],
    significado: '"Dios oirá". Hijo de Abraham y Agar, padre de los ismaelitas.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 16',
  },
  {
    hebreo: 'לוֹט',
    nombre: 'Lot',
    transliteracion: 'Lot',
    aliases: ['lot', 'lot', 'לוט', 'לוֹט'],
    significado: '"Cubierto" o "Velado". Sobrino de Abraham, escapó de Sodoma.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 11',
  },
  {
    hebreo: 'יַעֲקֹב',
    nombre: 'Jacob',
    transliteracion: 'Yaakov',
    aliases: ['yaakov', 'yakov', 'jacob', 'jakob', 'יעקב', 'יַעֲקֹב'],
    significado: '"Suplantador" o "El que agarra el talón". Padre de las doce tribus de Israel.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 25',
  },
  {
    hebreo: 'עֵשָׂו',
    nombre: 'Esaú',
    transliteracion: 'Esav',
    aliases: ['esav', 'esau', 'esau', 'עשו', 'עֵשָׂו'],
    significado: '"Velludo" o "Peludo". Hijo de Isaac, hermano de Jacob, padre de Edom.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 25',
  },
  {
    hebreo: 'רְאוּבֵן',
    nombre: 'Rubén',
    transliteracion: 'Reuven',
    aliases: ['reuven', 'rubén', 'reuben', 'ראובן', 'רְאוּבֵן'],
    significado: '"Mirad, un hijo". Hijo primogénito de Jacob y Lea.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'שִׁמְעוֹן',
    nombre: 'Simón',
    transliteracion: 'Shimon',
    aliases: ['shimon', 'simeón', 'simón', 'simon', 'שמעון', 'שִׁמְעוֹן'],
    significado: '"Oído" u "Oír". Segundo hijo de Jacob.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'לֵוִי',
    nombre: 'Leví',
    transliteracion: 'Levi',
    aliases: ['levi', 'leví', 'levi', 'לוי', 'לֵוִי'],
    significado: '"Unido" o "Acompañado". Fundador de la tribu sacerdotal.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'יְהוּדָה',
    nombre: 'Judá',
    transliteracion: 'Yehudah',
    aliases: ['yehudah', 'judah', 'juda', 'judá', 'yehuda', 'יהודה', 'יְהוּדָה'],
    significado: '"Alabaré a YHVH". Fundador de la tribu real de la cual proviene el Mashiaj.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'דָּן',
    nombre: 'Dan',
    transliteracion: 'Dan',
    aliases: ['dan', 'dan', 'דן', 'דָּן'],
    significado: '"Juez" o "Él juzgó". Fundador de la tribu de Dan.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'נַפְתָּלִי',
    nombre: 'Neftalí',
    transliteracion: 'Naftali',
    aliases: ['naftali', 'neftalí', 'naphtali', 'נפתלי', 'נַפְתָּלִי'],
    significado: '"Mi lucha" o "Lucha". Fundador de la tribu de Neftalí.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'גָּד',
    nombre: 'Gad',
    transliteracion: 'Gad',
    aliases: ['gad', 'gad', 'גד', 'גָּד'],
    significado: '"Suerte" o "Fortuna". Fundador de la tribu de Gad.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'אָשֵׁר',
    nombre: 'Asher',
    transliteracion: 'Asher',
    aliases: ['asher', 'asher', 'אשר', 'אָשֵׁר'],
    significado: '"Felicidad" o "Bendito". Fundador de la tribu de Asher.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'יִשָּׂשכָר',
    nombre: 'Isacar',
    transliteracion: 'Yissakhar',
    aliases: ['yissakhar', 'isacar', 'issachar', 'יששכר', 'יִשָּׂשכָר'],
    significado: '"Hay recompensa". Fundador de la tribu de Isacar.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'זְבוּלוּן',
    nombre: 'Zabulón',
    transliteracion: 'Zevulun',
    aliases: ['zevulun', 'zabulón', 'zebulun', 'זבולון', 'זְבוּלוּן'],
    significado: '"Morada" o "Honor". Fundador de la tribu de Zabulón.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'יוֹסֵף',
    nombre: 'José',
    transliteracion: 'Yosef',
    aliases: ['yosef', 'yosef', 'jose', 'joseph', 'yusuf', 'יוסף', 'יוֹסֵף'],
    significado: '"Añadir" o "Aumentar". Hijo de Jacob vendido a Egipto, quien se convirtió en visir y salvó a su familia.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'בִּנְיָמִין',
    nombre: 'Benjamín',
    transliteracion: 'Binyamin',
    aliases: ['binyamin', 'benjamin', 'benyamin', 'binyamin', 'בנימין', 'בִּנְיָמִין'],
    significado: '"Hijo de mi mano derecha" o "Hijo del sur". Último hijo de Jacob y Raquel, fundador de la tribu de Benjamín.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 35',
  },

  // ==================== MATRIARCAS ====================
  {
    hebreo: 'חַוָּה',
    nombre: 'Eva',
    transliteracion: 'Javah',
    aliases: ['javah', 'chavah', 'eva', 'eve', 'havah', 'khavah', 'חוה', 'חַוָּה'],
    significado: '"Vida" o "Viviente". La primera mujer, madre de toda la humanidad.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 3',
  },
  {
    hebreo: 'שָׂרָה',
    nombre: 'Sara',
    transliteracion: 'Sarah',
    aliases: ['sarah', 'sara', 'sarah', 'שרה', 'שָׂרָה'],
    significado: '"Princesa" o "Noble". Matriarca del pueblo hebreo, madre de Isaac.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 17',
  },
  {
    hebreo: 'רִבְקָה',
    nombre: 'Rebeca',
    transliteracion: 'Rivkah',
    aliases: ['rivkah', 'rebekah', 'rebecca', 'rebeca', 'רבקה', 'רִבְקָה'],
    significado: '"Atar" o "Unir". Matriarca, esposa de Isaac y madre de Jacob y Esaú.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 24',
  },
  {
    hebreo: 'לֵאָה',
    nombre: 'Lea',
    transliteracion: 'Leah',
    aliases: ['leah', 'lea', 'leah', 'leah', 'לֵאָה', 'לאה'],
    significado: '"Fatigada" o "Débil". Primera esposa de Jacob, madre de seis tribus incluyendo Judá y Leví.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'רָחֵל',
    nombre: 'Raquel',
    transliteracion: 'Rajel',
    aliases: ['rajel', 'raquel', 'rachel', 'rachel', 'rahel', 'רחל', 'רָחֵל'],
    significado: '"Oveja" o "Cordera". Matriarca amada de Jacob, madre de José y Benjamín.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'דִּינָה',
    nombre: 'Dina',
    transliteracion: 'Dinah',
    aliases: ['dinah', 'dina', 'dinah', 'דינה', 'דִּינָה'],
    significado: '"Justicia" o "Vindicada". Hija de Jacob y Lea.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'תָּמָר',
    nombre: 'Tamar',
    transliteracion: 'Tamar',
    aliases: ['tamar', 'tamar', 'תמר', 'תָּמָר'],
    significado: '"Palmera" o "Dátil". Nuera de Judá, madre de los gemelos Peres y Zéraj.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 38',
  },
  {
    hebreo: 'יוֹכֶבֶד',
    nombre: 'Jocabed',
    transliteracion: 'Yokheved',
    aliases: ['yokheved', 'jocabed', 'jochebed', 'יוכבד', 'יוֹכֶבֶד'],
    significado: '"YHVH es gloria". Madre de Moisés, Aarón y Miriam.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Éxodo 6',
  },
  {
    hebreo: 'שִׁפְרָה',
    nombre: 'Sifrá',
    transliteracion: 'Shifrah',
    aliases: ['shifrah', 'sifrá', 'shiphrah', 'שפרה', 'שִׁפְרָה'],
    significado: '"Hermosa" o "Buena". Una de las parteras hebreas que desobedeció al Faraón.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Éxodo 1',
  },
  {
    hebreo: 'פּוּעָה',
    nombre: 'Puá',
    transliteracion: "Pu'ah",
    aliases: ['puah', 'puá', 'puah', 'פועה', 'פּוּעָה'],
    significado: '"Hermosa" o "Joven". Una de las parteras hebreas que desobedeció al Faraón.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Éxodo 1',
  },
  {
    hebreo: 'רוּת',
    nombre: 'Rut',
    transliteracion: 'Rut',
    aliases: ['rut', 'ruth', 'rut', 'rut', 'רות', 'רוּת'],
    significado: '"Compañera" o "Amiga". Moabita que se unió al pueblo de Israel y bisabuela del rey David.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Rut 1',
  },
  {
    hebreo: 'עָרְפָּה',
    nombre: 'Orfa',
    transliteracion: 'Orpah',
    aliases: ['orpah', 'orfa', 'orpha', 'ערפה', 'עָרְפָּה'],
    significado: '"Nuca" o "Cuello". Cuñada de Rut que regresó a Moab.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Rut 1',
  },

  // ==================== PROFETAS (HOMBRES) ====================
  {
    hebreo: 'מֹשֶׁה',
    nombre: 'Moisés',
    transliteracion: 'Mosheh',
    aliases: ['mosheh', 'moshe', 'moises', 'mose', 'moshé', 'משה', 'מֹשֶׁה'],
    significado: '"Sacado de las aguas". El mayor profeta, quien recibió la Torá en el Sinai.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Éxodo 2',
  },
  {
    hebreo: 'אַהֲרֹן',
    nombre: 'Aarón',
    transliteracion: 'Aharon',
    aliases: ['aharon', 'aaron', 'aaron', 'aharon', 'אהרן', 'אַהֲרֹן'],
    significado: '"Montañista" o "Exaltado". Primer kohen gadol, hermano de Moisés.',
    genero: 'M',
    categoria: 'Kohen',
    referencia: 'Éxodo 4',
  },
  {
    hebreo: 'יְהוֹשֻׁעַ',
    nombre: 'Josué',
    transliteracion: 'Yehoshua',
    aliases: ['yehoshua', 'yehoshua', 'joshua', 'joshua', 'יהושע', 'יְהוֹשֻׁעַ'],
    significado: '"YHVH es salvación". Líder que condujo a Israel a la Tierra Prometida.',
    genero: 'M',
    categoria: 'Líder',
    referencia: 'Josué 1',
  },
  {
    hebreo: 'שְׁמוּאֵל',
    nombre: 'Samuel',
    transliteracion: 'Shmuel',
    aliases: ['shmuel', 'samuel', 'shmuel', 'shmuel', 'שמואל', 'שְׁמוּאֵל'],
    significado: '"Dios escuchó". Último juez y primer profeta que ungió a los reyes Saúl y David.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: '1 Samuel 1',
  },
  {
    hebreo: 'נָתָן',
    nombre: 'Natán',
    transliteracion: 'Natan',
    aliases: ['natan', 'natán', 'nathan', 'נתן', 'נָתָן'],
    significado: '"Él dio" o "Regalo". Profeta que confrontó a David por el caso de Betsabé.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: '2 Samuel 7',
  },
  {
    hebreo: 'אֵלִיָּהוּ',
    nombre: 'Elías',
    transliteracion: 'Eliyahu',
    aliases: ['eliyahu', 'elias', 'elijah', 'eliyahu', 'eliyahu', 'אליהו', 'אֵלִיָּהוּ'],
    significado: '"YHVH es mi Dios". Profeta que desafió a los profetas de Baal en el Monte Carmelo.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: '1 Reyes 17',
  },
  {
    hebreo: 'אֱלִישָׁע',
    nombre: 'Eliseo',
    transliteracion: 'Elisha',
    aliases: ['elisha', 'eliseo', 'elishah', 'אלישע', 'אֱלִישָׁע'],
    significado: '"Dios es salvación". Profeta sucesor de Elías, realizó muchos milagros.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: '1 Reyes 19',
  },
  {
    hebreo: 'יִרְמְיָהוּ',
    nombre: 'Jeremías',
    transliteracion: 'Yirmeyahu',
    aliases: ['yirmeyahu', 'jeremiah', 'jeremias', 'yirmi', 'ירמיהו', 'יִרְמְיָהוּ'],
    significado: '"YHVH exaltará". Profeta del exilio babilónico, autor de Lamentaciones.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Jeremías 1',
  },
  {
    hebreo: 'יְחֶזְקֵאל',
    nombre: 'Ezequiel',
    transliteracion: 'Yechezkel',
    aliases: ['yechezkel', 'ezekiel', 'ezequiel', 'yehezkel', 'יחזקאל', 'יְחֶזְקֵאל'],
    significado: '"Dios fortalecerá". Profeta en el exilio babilónico, visionario del Tercer Templo.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Ezequiel 1',
  },
  {
    hebreo: 'הוֹשֵׁעַ',
    nombre: 'Oseas',
    transliteracion: 'Hoshea',
    aliases: ['hoshea', 'oseas', 'hosea', 'הושע', 'הוֹשֵׁעַ'],
    significado: '"Salvación". Profeta que usó su matrimonio como metáfora del amor de Dios por Israel.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Oseas 1',
  },
  {
    hebreo: 'יוֹאֵל',
    nombre: 'Joel',
    transliteracion: 'Yoel',
    aliases: ['yoel', 'joel', 'yoel', 'יואל', 'יוֹאֵל'],
    significado: '"YHVH es Dios". Profeta del día de YHVH y el derramamiento del Espíritu.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Joel 1',
  },
  {
    hebreo: 'עָמוֹס',
    nombre: 'Amós',
    transliteracion: 'Amos',
    aliases: ['amos', 'amós', 'amos', 'עמוס', 'עָמוֹס'],
    significado: '"Carga" o "Portador". Profeta de justicia social, pastor de Tecoa.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Amós 1',
  },
  {
    hebreo: 'עֹבַדְיָה',
    nombre: 'Abdías',
    transliteracion: 'Ovadyah',
    aliases: ['ovadyah', 'abdías', 'obadiah', 'עובדיה', 'עֹבַדְיָה'],
    significado: '"Siervo de YHVH". Profeta contra Edom.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Abdías 1',
  },
  {
    hebreo: 'יוֹנָה',
    nombre: 'Jonás',
    transliteracion: 'Yonah',
    aliases: ['yonah', 'jona', 'jonás', 'yonah', 'יונה', 'יוֹנָה'],
    significado: '"Paloma". Profeta que fue tragado por un gran pez y predicó a Nínive.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Jonás 1',
  },
  {
    hebreo: 'מִיכָה',
    nombre: 'Miqueas',
    transliteracion: 'Mikhah',
    aliases: ['mikhah', 'miqueas', 'micah', 'מיכה', 'מִיכָה'],
    significado: '"¿Quién como YHVH?". Profeta que anunció el nacimiento del Mesías en Belén.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Miqueas 1',
  },
  {
    hebreo: 'נַחוּם',
    nombre: 'Nahúm',
    transliteracion: 'Najum',
    aliases: ['najum', 'nahúm', 'nahum', 'נחום', 'נַחוּם'],
    significado: '"Consuelo" o "Compasión". Profeta contra Nínive.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Nahúm 1',
  },
  {
    hebreo: 'חֲבַקּוּק',
    nombre: 'Habacuc',
    transliteracion: 'Javakuk',
    aliases: ['javakuk', 'habacuc', 'habakkuk', 'חבקוק', 'חֲבַקּוּק'],
    significado: '"Abrazo" o "Enlazado". Profeta que cuestionó a Dios y recibió respuesta.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Habacuc 1',
  },
  {
    hebreo: 'צְפַנְיָה',
    nombre: 'Sofonías',
    transliteracion: 'Tzefanyah',
    aliases: ['tzefanyah', 'cefanías', 'zephaniah', 'צפניה', 'צְפַנְיָה'],
    significado: '"YHVH ha escondido". Profeta del día de la ira.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Sofonías 1',
  },
  {
    hebreo: 'חַגַּי',
    nombre: 'Ageo',
    transliteracion: 'Jaggay',
    aliases: ['jaggay', 'ageo', 'haggai', 'חגי', 'חַגַּי'],
    significado: '"Festivo" o "Fiesta". Profeta de la reconstrucción del Templo.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Ageo 1',
  },
  {
    hebreo: 'זְכַרְיָה',
    nombre: 'Zacarías',
    transliteracion: 'Zekharyah',
    aliases: ['zekharyah', 'zacarías', 'zechariah', 'זכריה', 'זְכַרְיָה'],
    significado: '"YHVH recuerda". Profeta de las visiones y la restauración de Jerusalén.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Zacarías 1',
  },
  {
    hebreo: 'מַלְאָכִי',
    nombre: 'Malaquías',
    transliteracion: "Mal'akhi",
    aliases: ['malakhi', 'malaquías', 'malachi', 'מלאכי', 'מַלְאָכִי'],
    significado: '"Mi mensajero". Último profeta del Antiguo Testamento, anunció la venida de Elías.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Malaquías 1',
  },
  {
    hebreo: 'בִּלְעָם',
    nombre: 'Balaam',
    transliteracion: "Bil'am",
    aliases: ['bilam', 'balaam', "bil'am", 'בלעם', 'בִּלְעָם'],
    significado: '"Devorador" o "No del pueblo". Profeta que bendijo a Israel en contra de su voluntad.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Números 22',
  },

  // ==================== PROFETISAS (MUJERES) ====================
  {
    hebreo: 'מִרְיָם',
    nombre: 'Miriam',
    transliteracion: 'Miryam',
    aliases: ['miryam', 'miriam', 'maryam', 'maria', 'miryam', 'מרים', 'מִרְיָם'],
    significado: '"Amargura" o "Rebeldía". Hermana de Moisés y Aarón, profetisa que lideró a las mujeres.',
    genero: 'F',
    categoria: 'Profetisa',
    referencia: 'Éxodo 15',
  },
  {
    hebreo: 'דְּבוֹרָה',
    nombre: 'Débora',
    transliteracion: 'Devorah',
    aliases: ['devorah', 'deborah', 'debora', 'devora', 'דבורה', 'דְּבוֹרָה'],
    significado: '"Abeja". Profetisa y jueza que lideró a Israel contra Sísara.',
    genero: 'F',
    categoria: 'Profetisa',
    referencia: 'Jueces 4',
  },
  {
    hebreo: 'חַנָּה',
    nombre: 'Ana',
    transliteracion: 'Jannah',
    aliases: ['jannah', 'hannah', 'hana', 'anna', 'hanah', 'חנה', 'חַנָּה'],
    significado: '"Gracia" o "Favor". Madre de Samuel, modelo de oración y fe.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: '1 Samuel 1',
  },
  {
    hebreo: 'חוּלְדָּה',
    nombre: 'Hulda',
    transliteracion: 'Juldah',
    aliases: ['juldah', 'huldah', 'hulda', 'חולדה', 'חוּלְדָּה'],
    significado: '"Comadreja". Profetisa en tiempos del rey Josías, confirmó el rollo de la Torá.',
    genero: 'F',
    categoria: 'Profetisa',
    referencia: '2 Reyes 22',
  },

  // ==================== REYES (HOMBRES) ====================
  {
    hebreo: 'שָׁאוּל',
    nombre: 'Saúl',
    transliteracion: 'Shaul',
    aliases: ['shaul', 'saul', 'saúl', 'שאול', 'שָׁאוּל'],
    significado: '"Pedido" o "Preguntado". Primer rey de Israel, ungido por Samuel.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Samuel 9',
  },
  {
    hebreo: 'דָּוִד',
    nombre: 'David',
    transliteracion: 'David',
    aliases: ['david', 'dawid', 'dawid', 'דוד', 'דָּוִד'],
    significado: '"Amado" o "Querido". El rey ungido que unificó a Israel y de cuya línea vendría el Mashiaj.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Samuel 16',
  },
  {
    hebreo: 'שְׁלֹמֹה',
    nombre: 'Salomón',
    transliteracion: 'Shlomoh',
    aliases: ['shlomoh', 'shlomo', 'solomon', 'salomon', 'salomón', 'שלמה', 'שְׁלֹמֹה'],
    significado: '"Paz". Hijo de David, constructor del Primer Templo de Jerusalén.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 3',
  },
  {
    hebreo: 'יָרָבְעָם',
    nombre: 'Jeroboam',
    transliteracion: 'Yarov\'am',
    aliases: ['yarovam', 'jeroboam', 'yarobam', 'ירבעם', 'יָרָבְעָם'],
    significado: '"El pueblo contendrá". Primer rey de Israel (norte) después de la división.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 11',
  },
  {
    hebreo: 'אֲבִיָּה',
    nombre: 'Abías',
    transliteracion: 'Aviyah',
    aliases: ['aviyah', 'abías', 'abijah', 'אביה', 'אֲבִיָּה'],
    significado: '"Mi padre es YHVH". Rey de Judá, hijo de Jeroboam.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 14',
  },
  {
    hebreo: 'אָסָא',
    nombre: 'Asa',
    transliteracion: 'Asa',
    aliases: ['asa', 'asa', 'אסא', 'אָסָא'],
    significado: '"Médico" o "Sanador". Rey piadoso de Judá que eliminó la idolatría.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 15',
  },
  {
    hebreo: 'עָמְרִי',
    nombre: 'Omri',
    transliteracion: 'Omri',
    aliases: ['omri', 'omri', 'עמרי', 'עָמְרִי'],
    significado: '"Vida" o "Siervo de YHVH". Rey de Israel, padre de Acab.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 16',
  },
  {
    hebreo: 'אַחְאָב',
    nombre: 'Acab',
    transliteracion: 'Achav',
    aliases: ['achav', 'acab', 'ahab', 'אחאב', 'אַחְאָב'],
    significado: '"Hermano del padre" o "Tío". Rey malvado de Israel, esposo de Jezabel.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 16',
  },
  {
    hebreo: 'יְהוֹשָׁפָט',
    nombre: 'Josafat',
    transliteracion: 'Yehoshafat',
    aliases: ['yehoshafat', 'josafat', 'jehoshaphat', 'יהושפט', 'יְהוֹשָׁפָט'],
    significado: '"YHVH ha juzgado". Rey piadoso de Judá.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 22',
  },
  {
    hebreo: 'יְהוֹרָם',
    nombre: 'Joram',
    transliteracion: 'Yehoram',
    aliases: ['yehoram', 'joram', 'jehoram', 'יהורם', 'יְהוֹרָם'],
    significado: '"YHVH es exaltado". Rey de Judá, hijo de Josafat.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 8',
  },
  {
    hebreo: 'אֲחַזְיָהוּ',
    nombre: 'Ocozías',
    transliteracion: 'Ajazyahu',
    aliases: ['ajazyahu', 'ocozías', 'ahaziah', 'אחזיהו', 'אֲחַזְיָהוּ'],
    significado: '"YHVH sostiene". Rey de Judá que cayó por una ventana.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 8',
  },
  {
    hebreo: 'עֻזִּיָּהוּ',
    nombre: 'Uzías',
    transliteracion: 'Uziyahu',
    aliases: ['uziyahu', 'uzías', 'uzziah', 'עוזיהו', 'עֻזִּיָּהוּ'],
    significado: '"Fuerza de YHVH". Rey de Judá que fue leproso por su orgullo.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 15',
  },
  {
    hebreo: 'חִזְקִיָּהוּ',
    nombre: 'Ezequías',
    transliteracion: 'Jizkiyahu',
    aliases: ['jizkiyahu', 'ezequías', 'hezekiah', 'חזקיהו', 'חִזְקִיָּהוּ'],
    significado: '"YHVH fortalece". Rey piadoso de Judá que extendió su vida 15 años.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 18',
  },
  {
    hebreo: 'מְנַשֶּׁה',
    nombre: 'Manasés',
    transliteracion: 'Menashé',
    aliases: ['menashé', 'manasés', 'manasseh', 'מנשה', 'מְנַשֶּׁה'],
    significado: '"Hacer olvidar". Rey malvado de Judá que luego se arrepintió.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 21',
  },
  {
    hebreo: 'אַמּוֹן',
    nombre: 'Amón',
    transliteracion: 'Amon',
    aliases: ['amon', 'amón', 'amon', 'אמון', 'אַמּוֹן'],
    significado: '"Oculto" o "Fiel". Rey malvado de Judá, hijo de Manasés.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 21',
  },
  {
    hebreo: 'יֹאשִׁיָּהוּ',
    nombre: 'Josías',
    transliteracion: 'Yoshiyahu',
    aliases: ['yoshiyahu', 'josías', 'josiah', 'יאשיהו', 'יֹאשִׁיָּהוּ'],
    significado: '"YHVH sostiene". Rey reformador de Judá que encontró el rollo de la Torá.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 22',
  },
  {
    hebreo: 'יְהוֹיָקִים',
    nombre: 'Joaquín',
    transliteracion: 'Yehoyakim',
    aliases: ['yehoyakim', 'joaquín', 'jehoiakim', 'יהויקים', 'יְהוֹיָקִים'],
    significado: '"YHVH establecerá". Rey de Judá que quemó el rollo de Jeremías.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 23',
  },
  {
    hebreo: 'יְהוֹיָכִין',
    nombre: 'Joacín',
    transliteracion: 'Yehoyakhin',
    aliases: ['yehoyakhin', 'joacín', 'jehoiachin', 'יהויכין', 'יְהוֹיָכִין'],
    significado: '"YHVH establecerá". Rey exiliado a Babilonia con Ezequiel.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 24',
  },
  {
    hebreo: 'צִדְקִיָּהוּ',
    nombre: 'Sedequías',
    transliteracion: 'Tzidkiyahu',
    aliases: ['tzidkiyahu', 'sedequías', 'zedekiah', 'צדקיהו', 'צִדְקִיָּהוּ'],
    significado: '"Justicia de YHVH". Último rey de Judá, vio a sus hijos morir y fue cegado.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '2 Reyes 24',
  },

  // ==================== REINAS (MUJERES) ====================
  {
    hebreo: 'אֶסְתֵּר',
    nombre: 'Ester',
    transliteracion: 'Ester',
    aliases: ['ester', 'esther', 'ester', 'hadassah', 'אסתר', 'אֶסְתֵּר'],
    significado: '"Estrella" o "Oculta". Reina de Persia que salvó al pueblo judío de la destrucción.',
    genero: 'F',
    categoria: 'Reina',
    referencia: 'Ester 2',
  },
  {
    hebreo: 'בַּת־שֶׁבַע',
    nombre: 'Betsabé',
    transliteracion: 'Bat-Sheva',
    aliases: ['bat-sheva', 'batsheva', 'betsabe', 'bethsheba', 'בת שבע', 'בַּת־שֶׁבַע'],
    significado: '"Hija del juramento". Madre del rey Salomón, esposa de David y ancestro del Mashiaj.',
    genero: 'F',
    categoria: 'Reina',
    referencia: '2 Samuel 11',
  },
  {
    hebreo: 'מִיכַל',
    nombre: 'Mical',
    transliteracion: 'Mijal',
    aliases: ['mijal', 'michal', 'mical', 'mikal', 'מיכל', 'מִיכַל'],
    significado: '"¿Quién como Dios?". Hija de Saúl, primera esposa de David.',
    genero: 'F',
    categoria: 'Reina',
    referencia: '1 Samuel 14',
  },
  {
    hebreo: 'אֲבִיגַיִל',
    nombre: 'Abigail',
    transliteracion: 'Avigayil',
    aliases: ['avigayil', 'abigail', 'avigail', 'abigaíl', 'abigayil', 'אביגיל', 'אֲבִיגַיִל'],
    significado: '"Mi padre es alegría". Esposa sabia y prudente del rey David, quien evitó un derramamiento de sangre.',
    genero: 'F',
    categoria: 'Reina',
    referencia: '1 Samuel 25',
  },
  {
    hebreo: 'אֲבִישׁוֹג',
    nombre: 'Abisag',
    transliteracion: 'Avishag',
    aliases: ['avishag', 'abisag', 'abishag', 'אבישג', 'אֲבִישׁוֹג'],
    significado: '"Mi padre divaga". Joven que cuidó al rey David en su vejez.',
    genero: 'F',
    categoria: 'Reina',
    referencia: '1 Reyes 1',
  },
  {
    hebreo: 'רִצְפָּה',
    nombre: 'Rizpa',
    transliteracion: 'Ritzpah',
    aliases: ['ritzpah', 'rizpa', 'rizpah', 'רצפה', 'רִצְפָּה'],
    significado: '"Carbón encendido". Concubina de Saúl, protegió los cuerpos de sus hijos.',
    genero: 'F',
    categoria: 'Reina',
    referencia: '2 Samuel 21',
  },

  // ==================== JUECES ====================
  {
    hebreo: 'עָתְנִיאֵל',
    nombre: 'Otniel',
    transliteracion: 'Otniel',
    aliases: ['otniel', 'otniel', 'עתניאל', 'עָתְנִיאֵל'],
    significado: '"León de Dios" o "Fuerza de Dios". Primer juez de Israel.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 3',
  },
  {
    hebreo: 'אֵהוּד',
    nombre: 'Aod',
    transliteracion: 'Ehud',
    aliases: ['ehud', 'aod', 'ehud', 'אהוד', 'אֵהוּד'],
    significado: '"Fuerte" o "Poderoso". Juez zurdo que mató al rey Eglón de Moab.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 3',
  },
  {
    hebreo: 'שַׁמְגַּר',
    nombre: 'Samgar',
    transliteracion: 'Shamgar',
    aliases: ['shamgar', 'samgar', 'shamgar', 'שמגר', 'שַׁמְגַּר'],
    significado: '"Destructor" o "El que derrota". Juez que mató a 600 filisteos con una aguijada.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 3',
  },
  {
    hebreo: 'בָּרָק',
    nombre: 'Barac',
    transliteracion: 'Barak',
    aliases: ['barak', 'barac', 'barach', 'ברק', 'בָּרָק'],
    significado: '"Rayo" o "Relámpago". Juez que derrotó a Sísara con Débora.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 4',
  },
  {
    hebreo: 'גִּדְעוֹן',
    nombre: 'Gedeón',
    transliteracion: 'Gideon',
    aliases: ['gideon', 'gedeon', 'gideon', 'gedeon', 'גדעון', 'גִּדְעוֹן'],
    significado: '"Destructor" o "Talador". Juez que derrotó a los madianitas con 300 hombres.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 6',
  },
  {
    hebreo: 'אֲבִימֶלֶךְ',
    nombre: 'Abimelec',
    transliteracion: 'Avimelekh',
    aliases: ['avimelekh', 'abimelec', 'abimelech', 'אבימלך', 'אֲבִימֶלֶךְ'],
    significado: '"Mi padre es rey". Hijo de Gedeón que se autoproclamó rey de Siquem.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 9',
  },
  {
    hebreo: 'תּוֹלָע',
    nombre: 'Tola',
    transliteracion: 'Tola',
    aliases: ['tola', 'tola', 'תולע', 'תּוֹלָע'],
    significado: '"Gusano" o "Escarlata". Juez de Israel.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 10',
  },
  {
    hebreo: 'יָאִיר',
    nombre: 'Jair',
    transliteracion: 'Yair',
    aliases: ['yair', 'jair', 'yair', 'יאיר', 'יָאִיר'],
    significado: '"Él iluminará". Juez de Israel, tenía 30 hijos que montaban asnos.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 10',
  },
  {
    hebreo: 'יִפְתָּח',
    nombre: 'Jefté',
    transliteracion: 'Yiftaj',
    aliases: ['yiftaj', 'jefté', 'jephthah', 'iftaj', 'יפתח', 'יִפְתָּח'],
    significado: '"Abridor" o "Libertador". Juez que hizo voto imprudente con su hija.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 11',
  },
  {
    hebreo: 'אִבְצָן',
    nombre: 'Ibsán',
    transliteracion: 'Ivtzan',
    aliases: ['ivtzan', 'ibsán', 'ibzan', 'אבצן', 'אִבְצָן'],
    significado: '"Hermoso" o "Blanco". Juez de Israel, tuvo 30 hijos y 30 hijas.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 12',
  },
  {
    hebreo: 'אֵילוֹן',
    nombre: 'Elón',
    transliteracion: 'Elon',
    aliases: ['elon', 'elón', 'elon', 'אילון', 'אֵילוֹן'],
    significado: '"Roble" o "Fuerte". Juez de Israel.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 12',
  },
  {
    hebreo: 'עַבְדּוֹן',
    nombre: 'Abdón',
    transliteracion: 'Avdon',
    aliases: ['avdon', 'abdón', 'abdon', 'עבדון', 'עַבְדּוֹן'],
    significado: '"Siervo" o "Servicial". Juez de Israel, tuvo 40 hijos y 30 nietos.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 12',
  },
  {
    hebreo: 'שִׁמְשׁוֹן',
    nombre: 'Sansón',
    transliteracion: 'Shimshon',
    aliases: ['shimshon', 'samson', 'sansón', 'shimshon', 'shimson', 'שמשון', 'שִׁמְשׁוֹן'],
    significado: '"Como el sol". Nazareo de gran fuerza que libró a Israel de los filisteos.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 13',
  },

  // ==================== GUERREROS Y LÍDERES ====================
  {
    hebreo: 'יְהוֹנָתָן',
    nombre: 'Jonatán',
    transliteracion: 'Yonatan',
    aliases: ['yonatan', 'jonathan', 'jonatan', 'jhonatan', 'יהונתן', 'יְהוֹנָתָן'],
    significado: '"YHVH ha dado". Amigo leal de David, hijo de Saúl.',
    genero: 'M',
    categoria: 'Guerrero',
    referencia: '1 Samuel 14',
  },
  {
    hebreo: 'אֲבִישַׁי',
    nombre: 'Abisai',
    transliteracion: 'Avishai',
    aliases: ['avishai', 'abisai', 'abishai', 'אבישי', 'אֲבִישַׁי'],
    significado: '"Mi padre es regalo". Guerrero y sobrino de David, hijo de Sarvia.',
    genero: 'M',
    categoria: 'Guerrero',
    referencia: '1 Samuel 26',
  },
  {
    hebreo: 'יוֹאָב',
    nombre: 'Joab',
    transliteracion: "Yo'av",
    aliases: ['yoav', 'joab', 'yoab', 'יואב', 'יוֹאָב'],
    significado: '"YHVH es padre". Comandante del ejército de David, hermano de Abisai.',
    genero: 'M',
    categoria: 'Guerrero',
    referencia: '2 Samuel 8',
  },
  {
    hebreo: 'נְחֶמְיָה',
    nombre: 'Nehemías',
    transliteracion: 'Nejemyah',
    aliases: ['nejemyah', 'nehemías', 'nehemiah', 'נחמיה', 'נְחֶמְיָה'],
    significado: '"YHVH consuela". Gobernador que reconstruyó los muros de Jerusalén.',
    genero: 'M',
    categoria: 'Líder',
    referencia: 'Nehemías 1',
  },
  {
    hebreo: 'מָרְדְּכַי',
    nombre: 'Mardoqueo',
    transliteracion: 'Mordejai',
    aliases: ['mordejai', 'mardoqueo', 'mordecai', 'mordechai', 'מרדכי', 'מָרְדְּכַי'],
    significado: '"Pequeño" o "Hombre de Marduk". Tío de Ester, salvó al rey y al pueblo judío.',
    genero: 'M',
    categoria: 'Líder',
    referencia: 'Ester 2',
  },
  {
    hebreo: 'בֹּעַז',
    nombre: 'Boaz',
    transliteracion: 'Boaz',
    aliases: ['boaz', 'boaz', 'בועז', 'בֹּעַז'],
    significado: '"Fuerza" o "En él hay poder". Redentor de Rut, antepasado de David.',
    genero: 'M',
    categoria: 'Líder',
    referencia: 'Rut 2',
  },

  // ==================== SACERDOTES Y LEVITAS ====================
  {
    hebreo: 'אֶלְעָזָר',
    nombre: 'Eleazar',
    transliteracion: 'Elazar',
    aliases: ['elazar', 'eleazar', 'elazar', 'אלעזר', 'אֶלְעָזָר'],
    significado: '"Dios ha ayudado". Sumo sacerdote, hijo de Aarón, sucesor de su padre.',
    genero: 'M',
    categoria: 'Kohen',
    referencia: 'Éxodo 6',
  },
  {
    hebreo: 'פִּינְחָס',
    nombre: 'Finés',
    transliteracion: 'Pinjas',
    aliases: ['pinjas', 'finés', 'phinehas', 'פינחס', 'פִּינְחָס'],
    significado: '"Boca de serpiente" o "Oráculo". Sacerdote que detuvo la plaga con su celo.',
    genero: 'M',
    categoria: 'Kohen',
    referencia: 'Números 25',
  },
  {
    hebreo: 'חִלְקִיָּהוּ',
    nombre: 'Hilcías',
    transliteracion: 'Hilkiyahu',
    aliases: ['hilkiyahu', 'hilcías', 'hilkiyah', 'חלקיהו', 'חִלְקִיָּהוּ'],
    significado: '"Mi porción es YHVH". Sumo sacerdote que encontró el rollo de la Torá en el Templo.',
    genero: 'M',
    categoria: 'Kohen',
    referencia: '2 Reyes 22',
  },
  {
    hebreo: 'יְהוֹיָדָע',
    nombre: 'Joiada',
    transliteracion: 'Yehoyada',
    aliases: ['yehoyada', 'joiada', 'jehoiada', 'יהוידע', 'יְהוֹיָדָע'],
    significado: '"YHVH conoce". Sumo sacerdote que coronó a Joás y derrocó a Atalía.',
    genero: 'M',
    categoria: 'Kohen',
    referencia: '2 Reyes 11',
  },
  {
    hebreo: 'עֶזְרָא',
    nombre: 'Esdras',
    transliteracion: 'Ezra',
    aliases: ['ezra', 'esdras', 'ezrah', 'עזרא', 'עֶזְרָא'],
    significado: '"Ayuda" o "Socorro". Escriba y sacerdote que restauró la Torá después del exilio.',
    genero: 'M',
    categoria: 'Kohen',
    referencia: 'Esdras 7',
  },
  {
    hebreo: 'אָסָף',
    nombre: 'Asaf',
    transliteracion: 'Asaf',
    aliases: ['asaf', 'asaph', 'asaf', 'asaf', 'אסף', 'אָסָף'],
    significado: '"Recoger" o "Juntar". Levita y cantor del Templo, autor de muchos Salmos.',
    genero: 'M',
    categoria: 'Levita',
    referencia: '1 Crónicas 16',
  },

  // ==================== EXTRANJEROS / GENTILES ====================
  {
    hebreo: 'פַּרְעֹה',
    nombre: 'Faraón',
    transliteracion: "Par'oh",
    aliases: ['paroh', 'faraón', 'pharaoh', 'פרעה', 'פַּרְעֹה'],
    significado: '"Casa grande" (egipcio). Rey de Egipto.',
    genero: 'M',
    categoria: 'Gobernante',
    referencia: 'Génesis 12',
  },
  {
    hebreo: 'פּוֹטִיפַר',
    nombre: 'Potifar',
    transliteracion: 'Potifar',
    aliases: ['potifar', 'potifar', 'פוטיפר', 'פּוֹטִיפַר'],
    significado: '"El que pertenece al dios Ra" (egipcio). Oficial de Faraón, dueño de José.',
    genero: 'M',
    categoria: 'Gobernante',
    referencia: 'Génesis 37',
  },
  // ==================== JUSTOS Y SABIOS ====================
{
  hebreo: 'אִיּוֹב',
  nombre: 'Job',
  transliteracion: 'Iyov',
  aliases: ['iyov', 'job', 'iob', 'איוב', 'אִיּוֹב'],
  significado: '"Odiado" o "Perseguido". Justo probado por el sufrimiento, modelo de paciencia y fe.',
  genero: 'M',
  categoria: 'Justo',
  referencia: 'Job 1',
},
{
  hebreo: 'אֱלִיפַז',
  nombre: 'Elifaz',
  transliteracion: 'Elifaz',
  aliases: ['elifaz', 'elifaz', 'אליפז', 'אֱלִיפַז'],
  significado: '"Mi Dios es fino/oro". Amigo de Job de Temán.',
  genero: 'M',
  categoria: 'Sabio',
  referencia: 'Job 2',
},
{
  hebreo: 'בִּלְדַּד',
  nombre: 'Bildad',
  transliteracion: 'Bildad',
  aliases: ['bildad', 'bildad', 'בלדד', 'בִּלְדַּד'],
  significado: '"Confusión de amor". Amigo de Job de Súah.',
  genero: 'M',
  categoria: 'Sabio',
  referencia: 'Job 2',
},
{
  hebreo: 'צוֹפַר',
  nombre: 'Zofar',
  transliteracion: 'Tzofar',
  aliases: ['tzofar', 'zofar', 'צופר', 'צוֹפַר'],
  significado: '"Pájaro" o "Despertador". Amigo de Job de Naamá.',
  genero: 'M',
  categoria: 'Sabio',
  referencia: 'Job 2',
},
{
  hebreo: 'אֱלִיהוּא',
  nombre: 'Eliú',
  transliteracion: 'Elihu',
  aliases: ['elihu', 'eliu', 'elihu', 'אליהוא', 'אֱלִיהוּא'],
  significado: '"Él es mi Dios". Joven sabio que intervino en el debate de Job.',
  genero: 'M',
  categoria: 'Sabio',
  referencia: 'Job 32',
},
{
  hebreo: 'אֲגוּר',
  nombre: 'Agur',
  transliteracion: 'Agur',
  aliases: ['agur', 'agur', 'אגור', 'אֲגוּר'],
  significado: '"Recogido" o "Huésped". Autor de los proverbios de Agur.',
  genero: 'M',
  categoria: 'Sabio',
  referencia: 'Proverbios 30',
},
{
  hebreo: 'לְמוּאֵל',
  nombre: 'Lemuel',
  transliteracion: 'Lemuel',
  aliases: ['lemuel', 'lemuel', 'למואל', 'לְמוּאֵל'],
  significado: '"Para Dios" o "Dedicado a Dios". Rey a quien se dirigen las palabras de su madre.',
  genero: 'M',
  categoria: 'Sabio',
  referencia: 'Proverbios 31',
},

// ==================== PROFETAS ADICIONALES ====================
{
  hebreo: 'יְשַׁעְיָהוּ',
  nombre: 'Isaías',
  transliteracion: 'Yeshayahu',
  aliases: ['yeshayahu', 'isaias', 'isaiah', 'ישעיהו', 'יְשַׁעְיָהוּ'],
  significado: '"YHVH es salvación". Gran profeta del exilio y del siervo sufriente.',
  genero: 'M',
  categoria: 'Profeta',
  referencia: 'Isaías 1',
},
{
  hebreo: 'דָּנִיֵּאל',
  nombre: 'Daniel',
  transliteracion: "Daniel",
  aliases: ['daniel', 'daniel', 'dani', 'דניאל', 'דָּנִיֵּאל'],
  significado: '"Dios es mi juez". Profeta en el exilio babilónico, visionario y justo.',
  genero: 'M',
  categoria: 'Profeta',
  referencia: 'Daniel 1',
},
{
  hebreo: 'בָּרוּךְ',
  nombre: 'Baruc',
  transliteracion: 'Baruch',
  aliases: ['baruch', 'baruc', 'baruj', 'ברוך', 'בָּרוּךְ'],
  significado: '"Bendito". Escriba fiel del profeta Jeremías.',
  genero: 'M',
  categoria: 'Profeta',
  referencia: 'Jeremías 32',
},

// ==================== MATRIARCAS Y MUJERES ====================
{
  hebreo: 'נָעֳמִי',
  nombre: 'Noemí',
  transliteracion: "Na'omi",
  aliases: ['naomi', 'noemi', 'noemi', 'נעמי', 'נָעֳמִי'],
  significado: '"Mi deleite" o "Pleamar". Suegra de Rut, volvió de Moab a Belén.',
  genero: 'F',
  categoria: 'Matriarca',
  referencia: 'Rut 1',
},
{
  hebreo: 'פְּנִנָּה',
  nombre: 'Penina',
  transliteracion: 'Peninah',
  aliases: ['peninah', 'penina', 'peninnah', 'פנינה', 'פְּנִנָּה'],
  significado: '"Coral" o "Perla". Rival de Ana, esposa de Elcana.',
  genero: 'F',
  categoria: 'Matriarca',
  referencia: '1 Samuel 1',
},
{
  hebreo: 'אִיזֶבֶל',
  nombre: 'Jezabel',
  transliteracion: 'Izevel',
  aliases: ['izevel', 'jezabel', 'jezebel', 'איזבל', 'אִיזֶבֶל'],
  significado: '"Donde está el príncipe?" (tiro-fenicio). Reina malvada, esposa de Acab.',
  genero: 'F',
  categoria: 'Reina',
  referencia: '1 Reyes 16',
},
{
  hebreo: 'עֲתַלְיָה',
  nombre: 'Atalía',
  transliteracion: 'Atalyah',
  aliases: ['atalyah', 'atalia', 'athaliah', 'עתליה', 'עֲתַלְיָה'],
  significado: '"YHVH es exaltado". Reina usurpadora de Judá, hija de Jezabel.',
  genero: 'F',
  categoria: 'Reina',
  referencia: '2 Reyes 11',
},
{
  hebreo: 'מֵרַב',
  nombre: 'Merab',
  transliteracion: 'Merav',
  aliases: ['merav', 'merab', 'merav', 'מרב', 'מֵרַב'],
  significado: '"Aumento" o "Mucha". Hija mayor de Saúl, prometida a David.',
  genero: 'F',
  categoria: 'Reina',
  referencia: '1 Samuel 14',
},
{
  hebreo: 'אֱלִישֶׁבַע',
  nombre: 'Elisabet',
  transliteracion: 'Elisheva',
  aliases: ['elisheva', 'elisabet', 'elizabeth', 'eliseba', 'אלישבע', 'אֱלִישֶׁבַע'],
  significado: '"Dios es mi juramento". Esposa de Zacarías, madre de Juan el Bautista.',
  genero: 'F',
  categoria: 'Matriarca',
  referencia: 'Lucas 1',
},
{
  hebreo: 'שְׁלוֹמִית',
  nombre: 'Salomé',
  transliteracion: 'Shlomit',
  aliases: ['shlomit', 'salome', 'salome', 'shlomith', 'שלומית', 'שְׁלוֹמִית'],
  significado: '"Pacífica". Seguidora de Jesús, hija de Herodías (NT).',
  genero: 'F',
  categoria: 'Matriarca',
  referencia: 'Marcos 6 / Marcos 16',
},
{
  hebreo: 'מַרְתָּא',
  nombre: 'Marta',
  transliteracion: 'Marta',
  aliases: ['marta', 'marta', 'martha', 'מרתא', 'מַרְתָּא'],
  significado: '"Señora" o "Amo" (araméo). Hermana de María y Lázaro, anfitriona de Jesús.',
  genero: 'F',
  categoria: 'Matriarca',
  referencia: 'Lucas 10',
},
{
  hebreo: 'טְבִיתָא',
  nombre: 'Tabita',
  transliteracion: 'Tabita',
  aliases: ['tabita', 'tabita', 'dorcas', 'טביתא', 'טְבִיתָא'],
  significado: '"Gacela" (araméo). Discípula resucitada por Pedro en Jope.',
  genero: 'F',
  categoria: 'Matriarca',
  referencia: 'Hechos 9',
},

// ==================== REYES DE ISRAEL Y JUDÁ ====================
{
  hebreo: 'אַבְשָׁלוֹם',
  nombre: 'Absalón',
  transliteracion: 'Avshalom',
  aliases: ['avshalom', 'absalon', 'absalom', 'אבשלום', 'אַבְשָׁלוֹם'],
  significado: '"Padre de paz". Hijo de David, se rebeló contra su padre.',
  genero: 'M',
  categoria: 'Príncipe',
  referencia: '2 Samuel 13',
},
{
  hebreo: 'אֲדֹנִיָּהוּ',
  nombre: 'Adonías',
  transliteracion: 'Adoniyah',
  aliases: ['adoniyah', 'adonias', 'adonijah', 'אדניהו', 'אֲדֹנִיָּהוּ'],
  significado: '"Mi señor es YHVH". Hijo de David, pretendió el trono.',
  genero: 'M',
  categoria: 'Príncipe',
  referencia: '1 Reyes 1',
},
{
  hebreo: 'אַמְנוֹן',
  nombre: 'Amnón',
  transliteracion: 'Amnon',
  aliases: ['amnon', 'amnon', 'amnon', 'אמנון', 'אַמְנוֹן'],
  significado: '"Fiel". Primogénito de David, violó a su hermana Tamar.',
  genero: 'M',
  categoria: 'Príncipe',
  referencia: '2 Samuel 13',
},
{
  hebreo: 'אִישְׁבֹּשֶׁת',
  nombre: 'Isboset',
  transliteracion: 'Ishboshet',
  aliases: ['ishboshet', 'isboset', 'ishbaal', 'אישבשת', 'אִישְׁבֹּשֶׁת'],
  significado: '"Hombre de vergüenza". Hijo de Saúl, rey de Israel.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Samuel 2',
},
{
  hebreo: 'רְחַבְעָם',
  nombre: 'Roboam',
  transliteracion: "Rehav'am",
  aliases: ['rehavam', 'roboam', 'rehoboam', 'רחבעם', 'רְחַבְעָם'],
  significado: '"El pueblo se ensancha". Hijo de Salomón, causó la división del reino.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '1 Reyes 12',
},
{
  hebreo: 'נָדָב',
  nombre: 'Nadab',
  transliteracion: 'Nadav',
  aliases: ['nadav', 'nadab', 'nadab', 'נדב', 'נָדָב'],
  significado: '"Generoso" o "Liberal". Hijo de Jeroboam, rey de Israel.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '1 Reyes 15',
},
{
  hebreo: 'בַּעְשָׁא',
  nombre: 'Baasa',
  transliteracion: "Ba'sha",
  aliases: ['basha', 'baasa', 'baasha', 'בעשא', 'בַּעְשָׁא'],
  significado: '"Él ofende" o "Maloliente". Rey de Israel que exterminó la casa de Jeroboam.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '1 Reyes 15',
},
{
  hebreo: 'אֵלָה',
  nombre: 'Elá',
  transliteracion: 'Elah',
  aliases: ['elah', 'ela', 'elah', 'אלה', 'אֵלָה'],
  significado: '"Encina" o "Árbol". Rey de Israel, asesinado por Zimri.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '1 Reyes 16',
},
{
  hebreo: 'זִמְרִי',
  nombre: 'Zimri',
  transliteracion: 'Zimri',
  aliases: ['zimri', 'zimri', 'zimri', 'זמרי', 'זִמְרִי'],
  significado: '"Mi música" o "Mi canto". Rey de Israel por 7 días.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '1 Reyes 16',
},
{
  hebreo: 'שַׁלֻּם',
  nombre: 'Salum',
  transliteracion: 'Shallum',
  aliases: ['shallum', 'salum', 'shallum', 'שלם', 'שַׁלֻּם'],
  significado: '"Retribución". Rey de Israel, asesinó a Zacarías.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 15',
},
{
  hebreo: 'מְנַחֵם',
  nombre: 'Menajem',
  transliteracion: 'Menachem',
  aliases: ['menachem', 'menajem', 'menahem', 'מנחם', 'מְנַחֵם'],
  significado: '"Consolador". Rey de Israel, cruel tirano.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 15',
},
{
  hebreo: 'פְּקַחְיָהוּ',
  nombre: 'Pekajías',
  transliteracion: 'Pekachyahu',
  aliases: ['pekachyahu', 'pekajias', 'pekahiah', 'פקחיהו', 'פְּקַחְיָהוּ'],
  significado: '"YHVH ha abierto los ojos". Rey de Israel.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 15',
},
{
  hebreo: 'פֶּקַח',
  nombre: 'Pekaj',
  transliteracion: 'Pekach',
  aliases: ['pekach', 'pekaj', 'pekah', 'פקח', 'פֶּקַח'],
  significado: '"Abrir los ojos". Rey de Israel, asesinó a Pekajías.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 15',
},
{
  hebreo: 'הוֹשֵׁעַ',
  nombre: 'Oseas',
  transliteracion: 'Hoshea',
  aliases: ['hoshea', 'oseas', 'hosea', 'הושע', 'הוֹשֵׁעַ'],
  significado: '"Salvación". Último rey de Israel antes de la caída de Samaria.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 17',
},
{
  hebreo: 'יֵהוּא',
  nombre: 'Jehú',
  transliteracion: 'Yehu',
  aliases: ['yehu', 'jehu', 'jehu', 'יהוא', 'יֵהוּא'],
  significado: '"Él es YHVH". Rey de Israel que exterminó la casa de Acab y Jezabel.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 9',
},
{
  hebreo: 'יְהוֹאָחָז',
  nombre: 'Joacaz',
  transliteracion: 'Yehoachaz',
  aliases: ['yehoachaz', 'joacaz', 'jehoahaz', 'יהואחז', 'יְהוֹאָחָז'],
  significado: '"YHVH ha tomado posesión". Rey de Israel.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 13',
},
{
  hebreo: 'יְהוֹאָשׁ',
  nombre: 'Joás',
  transliteracion: 'Yehoash',
  aliases: ['yehoash', 'joas', 'joash', 'יהואש', 'יְהוֹאָשׁ'],
  significado: '"YHVH ha dado". Rey de Israel, restaurado por Eliseo.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 13',
},
{
  hebreo: 'אֲמַצְיָהוּ',
  nombre: 'Amasías',
  transliteracion: 'Amatsyahu',
  aliases: ['amatsyahu', 'amasias', 'amaziah', 'אמציהו', 'אֲמַצְיָהוּ'],
  significado: '"Fortaleza de YHVH". Rey de Judá, venció a Edom.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 14',
},
{
  hebreo: 'יוֹתָם',
  nombre: 'Jotam',
  transliteracion: 'Yotam',
  aliases: ['yotam', 'jotam', 'jotham', 'יותם', 'יוֹתָם'],
  significado: '"YHVH es perfecto". Rey de Judá, hijo de Uzías.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 15',
},
{
  hebreo: 'אָחָז',
  nombre: 'Acaz',
  transliteracion: 'Achaz',
  aliases: ['achaz', 'acaz', 'ahaz', 'אחז', 'אָחָז'],
  significado: '"El que posee" o "Agarra". Rey malvado de Judá, padre de Ezequías.',
  genero: 'M',
  categoria: 'Rey',
  referencia: '2 Reyes 16',
},
{
  hebreo: 'גְּדַלְיָהוּ',
  nombre: 'Gedalías',
  transliteracion: 'Gedalyahu',
  aliases: ['gedalyahu', 'gedalias', 'gedaliah', 'גדליהו', 'גְּדַלְיָהוּ'],
  significado: '"YHVH es grande". Gobernador de Judá tras la destrucción del Templo.',
  genero: 'M',
  categoria: 'Gobernante',
  referencia: '2 Reyes 25',
},

// ==================== GUERREROS Y LÍDERES ====================
{
  hebreo: 'כָּלֵב',
  nombre: 'Calev',
  transliteracion: 'Kalev',
  aliases: ['kalev', 'caleb', 'calev', 'כלב', 'כָּלֵב'],
  significado: '"Perro" o "Todo corazón". Explorador fiel que entró a la Tierra Prometida.',
  genero: 'M',
  categoria: 'Guerrero',
  referencia: 'Números 13',
},
{
  hebreo: 'אַבְנֵר',
  nombre: 'Abner',
  transliteracion: 'Avner',
  aliases: ['avner', 'abner', 'abner', 'אבנר', 'אַבְנֵר'],
  significado: '"Mi padre es luz". Comandante del ejército de Saúl.',
  genero: 'M',
  categoria: 'Guerrero',
  referencia: '1 Samuel 14',
},
{
  hebreo: 'אֱלִיעֶזֶר',
  nombre: 'Eliezer',
  transliteracion: 'Eliezer',
  aliases: ['eliezer', 'eliezer', 'eliezer', 'אליעזר', 'אֱלִיעֶזֶר'],
  significado: '"Mi Dios es ayuda". Siervo de Abraham, luego de Moisés.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Génesis 15',
},
{
  hebreo: 'בַּרְזִלַּי',
  nombre: 'Barzilai',
  transliteracion: 'Barzilai',
  aliases: ['barzilai', 'barzilai', 'barzillai', 'ברזלי', 'בַּרְזִלַּי'],
  significado: '"De hierro". Anciano de Galaad que ayudó a David.',
  genero: 'M',
  categoria: 'Líder',
  referencia: '2 Samuel 17',
},
{
  hebreo: 'שִׁמְעִי',
  nombre: 'Simei',
  transliteracion: 'Shimei',
  aliases: ['shimei', 'simei', 'shimi', 'שמעי', 'שִׁמְעִי'],
  significado: '"Oído" o "Famoso". Benjamita que maldijo a David.',
  genero: 'M',
  categoria: 'Líder',
  referencia: '2 Samuel 16',
},
{
  hebreo: 'עִירָא',
  nombre: 'Ira',
  transliteracion: 'Ira',
  aliases: ['ira', 'ira', 'ira', 'עירא', 'עִירָא'],
  significado: '"Vigilante" o "Ciudad". Guerrero de David.',
  genero: 'M',
  categoria: 'Guerrero',
  referencia: '2 Samuel 20',
},
{
  hebreo: 'בְּנָיָהוּ',
  nombre: 'Benaía',
  transliteracion: 'Benayah',
  aliases: ['benayah', 'benaia', 'benaiah', 'בניהו', 'בְּנָיָהוּ'],
  significado: '"YHVH ha edificado". Valiente de los 30 de David.',
  genero: 'M',
  categoria: 'Guerrero',
  referencia: '2 Samuel 23',
},
{
  hebreo: 'עֲשָׂהאֵל',
  nombre: 'Asahel',
  transliteracion: 'Asahel',
  aliases: ['asahel', 'asahel', 'asahel', 'עשהאל', 'עֲשָׂהאֵל'],
  significado: '"Dios ha hecho". Hermano de Joab, veloz como una gacela.',
  genero: 'M',
  categoria: 'Guerrero',
  referencia: '2 Samuel 2',
},
{
  hebreo: 'עֲמָשָׂא',
  nombre: 'Amasa',
  transliteracion: 'Amasa',
  aliases: ['amasa', 'amasa', 'amasa', 'עמשא', 'עֲמָשָׂא'],
  significado: '"Carga" o "Levantamiento". Sobrino de David, asesinado por Joab.',
  genero: 'M',
  categoria: 'Guerrero',
  referencia: '2 Samuel 17',
},
{
  hebreo: 'אִתַּי',
  nombre: 'Ittai',
  transliteracion: 'Ittai',
  aliases: ['ittai', 'ittai', 'itai', 'אתי', 'אִתַּי'],
  significado: '"Conmigo". Gitateo leal a David.',
  genero: 'M',
  categoria: 'Guerrero',
  referencia: '2 Samuel 15',
},
{
  hebreo: 'זְרֻבָּבֶל',
  nombre: 'Zorobabel',
  transliteracion: 'Zerubavel',
  aliases: ['zerubavel', 'zorobabel', 'zerubbabel', 'זרבבל', 'זְרֻבָּבֶל'],
  significado: '"Engendrado en Babilonia". Líder del regreso del exilio, reconstruyó el altar.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Esdras 3',
},

// ==================== SACERDOTES Y LEVITAS ====================
{
  hebreo: 'אֶלְקָנָה',
  nombre: 'Elcana',
  transliteracion: 'Elkanah',
  aliases: ['elkanah', 'elcana', 'elkanah', 'אלקנה', 'אֶלְקָנָה'],
  significado: '"Dios ha poseído". Padre de Samuel, esposo de Ana y Penina.',
  genero: 'M',
  categoria: 'Levita',
  referencia: '1 Samuel 1',
},
{
  hebreo: 'עֵלִי',
  nombre: 'Elí',
  transliteracion: 'Eli',
  aliases: ['eli', 'eli', 'eli', 'עלי', 'עֵלִי'],
  significado: '"Elevado". Sumo sacerdote, mentor de Samuel.',
  genero: 'M',
  categoria: 'Kohen',
  referencia: '1 Samuel 1',
},
{
  hebreo: 'מָנוֹחַ',
  nombre: 'Manoa',
  transliteracion: 'Manoach',
  aliases: ['manoach', 'manoa', 'manoah', 'מנוח', 'מָנוֹחַ'],
  significado: '"Descanso". Padre de Sansón.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Jueces 13',
},
{
  hebreo: 'יוֹאֵל',
  nombre: 'Joel',
  transliteracion: 'Yoel',
  aliases: ['yoel', 'joel', 'joel', 'יואל', 'יוֹאֵל'],
  significado: '"YHVH es Dios". Hijo de Samuel, juez corrupto.',
  genero: 'M',
  categoria: 'Levita',
  referencia: '1 Samuel 8',
},
{
  hebreo: 'אֲבִיָּה',
  nombre: 'Abías',
  transliteracion: 'Aviyah',
  aliases: ['aviyah', 'abias', 'abijah', 'אביה', 'אֲבִיָּה'],
  significado: '"Mi padre es YHVH". Hijo de Samuel, juez corrupto.',
  genero: 'M',
  categoria: 'Levita',
  referencia: '1 Samuel 8',
},
{
  hebreo: 'מַלְכִּי־צֶדֶק',
  nombre: 'Melquisedec',
  transliteracion: 'Malki-Tzedek',
  aliases: ['malki-tzedek', 'melquisedec', 'melchizedek', 'מלכי־צדק', 'מַלְכִּי־צֶדֶק'],
  significado: '"Mi rey es justicia". Sacerdote de El Elyón, rey de Salem.',
  genero: 'M',
  categoria: 'Kohen',
  referencia: 'Génesis 14',
},

// ==================== FAMILIA DE RUT ====================
{
  hebreo: 'אֱלִימֶלֶךְ',
  nombre: 'Elimelec',
  transliteracion: 'Elimelech',
  aliases: ['elimelech', 'elimelec', 'elimelek', 'אלימלך', 'אֱלִימֶלֶךְ'],
  significado: '"Mi Dios es rey". Esposo de Noemí, murió en Moab.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Rut 1',
},
{
  hebreo: 'כְּלִיאוֹן',
  nombre: 'Quelión',
  transliteracion: 'Kilyon',
  aliases: ['kilyon', 'quelion', 'chilion', 'כליאון', 'כְּלִיאוֹן'],
  significado: '"Acabamiento" o "Quebrantamiento". Hijo de Elimelec.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Rut 1',
},
{
  hebreo: 'מַחְלוֹן',
  nombre: 'Majlón',
  transliteracion: 'Machlon',
  aliases: ['machlon', 'majon', 'mahlon', 'מחלון', 'מַחְלוֹן'],
  significado: '"Enfermo" o "Doliente". Hijo de Elimelec, esposo de Rut.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Rut 1',
},
{
  hebreo: 'עוֹבֵד',
  nombre: 'Obed',
  transliteracion: 'Oved',
  aliases: ['oved', 'obed', 'obed', 'עובד', 'עוֹבֵד'],
  significado: '"Siervo" o "Trabajador". Hijo de Boaz y Rut, padre de Isaí.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Rut 4',
},
{
  hebreo: 'יִשַׁי',
  nombre: 'Isaí',
  transliteracion: 'Yishai',
  aliases: ['yishai', 'isai', 'jesse', 'ישי', 'יִשַׁי'],
  significado: '"Don" o "Mi don". Padre del rey David.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Rut 4',
},

// ==================== NUEVO TESTAMENTO — RAÍZ HEBREA ====================
{
  hebreo: 'יֵשׁוּעַ',
  nombre: 'Jesús',
  transliteracion: 'Yeshua',
  aliases: ['yeshua', 'jesus', 'yeshu', 'ישוע', 'יֵשׁוּעַ'],
  significado: '"YHVH es salvación". Mashiaj, hijo de María y José.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Mateo 1',
},
{
  hebreo: 'יוֹחָנָן',
  nombre: 'Juan',
  transliteracion: 'Yojanan',
  aliases: ['yojanan', 'juan', 'john', 'johanan', 'יוחנן', 'יוֹחָנָן'],
  significado: '"YHVH ha tenido misericordia". El Bautista, o el apóstol amado.',
  genero: 'M',
  categoria: 'Profeta',
  referencia: 'Lucas 1',
},
{
  hebreo: 'מַתִּתְיָהוּ',
  nombre: 'Mateo',
  transliteracion: 'Mattityahu',
  aliases: ['mattityahu', 'mateo', 'matthew', 'mati', 'מתתיהו', 'מַתִּתְיָהוּ'],
  significado: '"Don de YHVH". Apóstol, ex recaudador de impuestos.',
  genero: 'M',
  categoria: 'Apóstol',
  referencia: 'Mateo 9',
},
{
  hebreo: 'תְּאוֹמָא',
  nombre: 'Tomás',
  transliteracion: "Te'oma",
  aliases: ['teoma', 'tomas', 'thomas', 'didymus', 'תאומא', 'תְּאוֹמָא'],
  significado: '"Gemelo" (araméo). Apóstol que dudó y tocó las heridas del Mashiaj.',
  genero: 'M',
  categoria: 'Apóstol',
  referencia: 'Juan 20',
},
{
  hebreo: 'בַּר־תַּלְמַי',
  nombre: 'Bartolomé',
  transliteracion: 'Bar-Talmai',
  aliases: ['bar-talmai', 'bartolome', 'bartholomew', 'nathanael', 'בר־תלמי', 'בַּר־תַּלְמַי'],
  significado: '"Hijo de Talmai" (hijo del sur/plenitud). Apóstol, identificado con Natanael.',
  genero: 'M',
  categoria: 'Apóstol',
  referencia: 'Mateo 10',
},
{
  hebreo: 'מַתִּתְיָהוּ',
  nombre: 'Matías',
  transliteracion: 'Mattityahu',
  aliases: ['mattityahu', 'matias', 'mathias', 'matthias', 'מתתיהו', 'מַתִּתְיָהוּ'],
  significado: '"Don de YHVH". Elegido para reemplazar a Judas Iscariote entre los apóstoles.',
  genero: 'M',
  categoria: 'Apóstol',
  referencia: 'Hechos 1',
},
{
  hebreo: 'בַּר־נַבִּי',
  nombre: 'Bernabé',
  transliteracion: 'Bar-Navi',
  aliases: ['bar-navi', 'barnabe', 'barnabas', 'barnabas', 'בר־נבי', 'בַּר־נַבִּי'],
  significado: '"Hijo de profecía" o "Hijo de consuelo" (bar-naba). Compañero de Pablo.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Hechos 4',
},
{
  hebreo: 'שִׁילָא',
  nombre: 'Silas',
  transliteracion: 'Shila',
  aliases: ['shila', 'silas', 'silvanus', 'שילא', 'שִׁילָא'],
  significado: '"Pedido" o "Tercero" (araméo). Líder de la congregación de Jerusalén, compañero de Pablo.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Hechos 15',
},
{
  hebreo: 'נַקְדִּימוֹן',
  nombre: 'Nicodemo',
  transliteracion: 'Nakdimon',
  aliases: ['nakdimon', 'nicodemo', 'nicodemus', 'נקדימון', 'נַקְדִּימוֹן'],
  significado: '"Vencedor del pueblo" o "Inocente de sangre". Fariseo que visitó a Jesús de noche.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Juan 3',
},
{
  hebreo: 'גַּמְלִיאֵל',
  nombre: 'Gamaliel',
  transliteracion: 'Gamliel',
  aliases: ['gamliel', 'gamaliel', 'gamaliel', 'גמליאל', 'גַּמְלִיאֵל'],
  significado: '"Recompensa de Dios". Rabino fariseo, maestro de Pablo.',
  genero: 'M',
  categoria: 'Líder',
  referencia: 'Hechos 5',
},
{
  hebreo: 'חָנָן',
  nombre: 'Anás',
  transliteracion: 'Janan',
  aliases: ['janan', 'anas', 'annas', 'chanan', 'חנן', 'חָנָן'],
  significado: '"Gracioso" o "Misericordioso". Sumo sacerdote, suegro de Caifás.',
  genero: 'M',
  categoria: 'Kohen',
  referencia: 'Lucas 3',
},
{
  hebreo: 'קַיָּפָא',
  nombre: 'Caifás',
  transliteracion: 'Kayafa',
  aliases: ['kayafa', 'caifas', 'caiaphas', 'קיפא', 'קַיָּפָא'],
  significado: '"Hondonada" o "Depresión". Sumo sacerdote durante el juicio de Jesús.',
  genero: 'M',
  categoria: 'Kohen',
  referencia: 'Mateo 26',
},
]

export const categorias = [
  'Todos',
  'Patriarca',
  'Matriarca',
  'Profeta',
  'Profetisa',
  'Rey',
  'Reina',
  'Príncipe',
  'Líder',
  'Juez',
  'Kohen',
  'Levita',
  'Guerrero',
  'Gobernante',
  'Justo',
  'Sabio',
  'Apóstol',
]