export interface NombreHebreo {
  hebreo: string
  nombre: string          // Castellanizado común
  transliteracion: string // Sefardí
  aliases: string[]       // Para búsqueda: fonética, variantes, sin acentos
  significado: string
  genero: 'M' | 'F'
  categoria: string
  referencia: string
}

export const nombresHebreos: NombreHebreo[] = [
  {
    hebreo: 'דָּוִד',
    nombre: 'David',
    transliteracion: 'David',
    aliases: ['david', 'dawid', 'dawid', 'דוד', 'דָּוִד'],
    significado: '"Amado" o "Querido". El rey ungido que unificó a Israel y de cuya línea vendría el Mashiaj.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Samuel 16',
  },
  {
    hebreo: 'מֹשֶׁה',
    nombre: 'Moisés',
    transliteracion: 'Mosheh',
    aliases: ['mosheh', 'moshe', 'moises', 'mose', 'moshé', 'משה', 'מֹשֶׁה'],
    significado: '"Sacado de las aguas". El mayor profeta, quien recibió la Torá en el Sinai.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Éxodo 2',
  },
  {
    hebreo: 'שָׂרָה',
    nombre: 'Sara',
    transliteracion: 'Sarah',
    aliases: ['sarah', 'sara', 'sarah', 'שרה', 'שָׂרָה'],
    significado: '"Princesa" o "Noble". Matriarca del pueblo hebreo, madre de Isaac.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 17',
  },
  {
    hebreo: 'אַבְרָהָם',
    nombre: 'Abraham',
    transliteracion: 'Avraham',
    aliases: ['avraham', 'abraham', 'abran', 'avram', 'אברהם', 'אַבְרָהָם'],
    significado: '"Padre de multitudes". Primer patriarca, quien dejó Ur para seguir al Eterno.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 12',
  },
  {
    hebreo: 'יִצְחָק',
    nombre: 'Isaac',
    transliteracion: 'Yitzjak',
    aliases: ['yitzjak', 'yitzhak', 'itzjak', 'itzjak', 'isaac', 'isaak', 'יצחק', 'יִצְחָק'],
    significado: '"Se reirá". Hijo de Abraham y Sara, patriarca que continuó el pacto.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 21',
  },
  {
    hebreo: 'יַעֲקֹב',
    nombre: 'Jacob',
    transliteracion: 'Yaakov',
    aliases: ['yaakov', 'yakov', 'jacob', 'jakob', 'יעקב', 'יַעֲקֹב'],
    significado: '"Suplantador" o "El que agarra el talón". Padre de las doce tribus de Israel.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 25',
  },
  {
    hebreo: 'רָחֵל',
    nombre: 'Raquel',
    transliteracion: 'Rajel',
    aliases: ['rajel', 'raquel', 'rachel', 'rachel', 'rahel', 'רחל', 'רָחֵל'],
    significado: '"Oveja" o "Cordera". Matriarca amada de Yaakov, madre de José y Benjamín.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'לֵאָה',
    nombre: 'Lea',
    transliteracion: 'Leah',
    aliases: ['leah', 'lea', 'leah', 'leah', 'לֵאָה', 'לאה'],
    significado: '"Fatigada" o "Débil". Primera esposa de Yaakov, madre de seis tribus incluyendo Judá y Leví.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'יוֹסֵף',
    nombre: 'José',
    transliteracion: 'Yosef',
    aliases: ['yosef', 'yosef', 'jose', 'joseph', 'yusuf', 'יוסף', 'יוֹסֵף'],
    significado: '"Añadir" o "Aumentar". Hijo de Yaakov vendido a Egipto, quien se convirtió en visir y salvó a su familia.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 30',
  },
  {
    hebreo: 'בִּנְיָמִין',
    nombre: 'Benjamín',
    transliteracion: 'Binyamin',
    aliases: ['binyamin', 'benjamin', 'benyamin', 'binyamin', 'בנימין', 'בִּנְיָמִין'],
    significado: '"Hijo de mi mano derecha" o "Hijo del sur". Último hijo de Yaakov y Rajel, fundador de la tribu de Benjamín.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 35',
  },
  {
    hebreo: 'אֵלִיָּהוּ',
    nombre: 'Elías',
    transliteracion: 'Eliyahu',
    aliases: ['eliyahu', 'elias', 'elijah', 'eliyahu', 'eliyahu', 'אליהו', 'אֵלִיָּהוּ'],
    significado: '"YHVH es mi Dios". Profeta que desafió a los profetas de Baal en el Monte Carmelo.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: '1 Reyes 17',
  },
  {
    hebreo: 'יֵשׁוּעַ',
    nombre: 'Josué',
    transliteracion: 'Yeshua',
    aliases: ['yeshua', 'yehoshua', 'joshua', 'jesus', 'yeshu', 'ישוע', 'יֵשׁוּעַ', 'יהושע'],
    significado: '"YHVH es salvación". Líder que condujo a Israel a la Tierra Prometida tras Moisés.',
    genero: 'M',
    categoria: 'Líder',
    referencia: 'Josué 1',
  },
  {
    hebreo: 'שְׁמוּאֵל',
    nombre: 'Samuel',
    transliteracion: 'Shmuel',
    aliases: ['shmuel', 'samuel', 'shmuel', 'shmuel', 'שמואל', 'שְׁמוּאֵל'],
    significado: '"Dios escuchó". Último juez y primer profeta que ungió a los reyes Saúl y David.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: '1 Samuel 1',
  },
  {
    hebreo: 'שְׁלֹמֹה',
    nombre: 'Salomón',
    transliteracion: 'Shlomoh',
    aliases: ['shlomoh', 'shlomo', 'solomon', 'salomon', 'salomón', 'שלמה', 'שְׁלֹמֹה'],
    significado: '"Paz". Hijo de David, constructor del Primer Templo de Jerusalén.',
    genero: 'M',
    categoria: 'Rey',
    referencia: '1 Reyes 3',
  },
  {
    hebreo: 'אֶסְתֵּר',
    nombre: 'Ester',
    transliteracion: 'Ester',
    aliases: ['ester', 'esther', 'ester', 'hadassah', 'אסתר', 'אֶסְתֵּר'],
    significado: '"Estrella" o "Oculta". Reina de Persia que salvó al pueblo judío de la destrucción.',
    genero: 'F',
    categoria: 'Reina',
    referencia: 'Ester 2',
  },
  {
    hebreo: 'רוּת',
    nombre: 'Rut',
    transliteracion: 'Rut',
    aliases: ['rut', 'ruth', 'rut', 'rut', 'רות', 'רוּת'],
    significado: '"Compañera" o "Amiga". Moabita que se unió al pueblo de Israel y bisabuela del rey David.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Rut 1',
  },
  {
    hebreo: 'דְּבוֹרָה',
    nombre: 'Débora',
    transliteracion: 'Devorah',
    aliases: ['devorah', 'deborah', 'debora', 'devora', 'דבורה', 'דְּבוֹרָה'],
    significado: '"Abeja". Profetisa y jueza que lideró a Israel contra Sísara.',
    genero: 'F',
    categoria: 'Profetisa',
    referencia: 'Jueces 4',
  },
  {
    hebreo: 'חַוָּה',
    nombre: 'Eva',
    transliteracion: 'Javah',
    aliases: ['javah', 'chavah', 'eva', 'eve', 'havah', 'khavah', 'חוה', 'חַוָּה'],
    significado: '"Vida" o "Viviente". La primera mujer, madre de toda la humanidad.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: 'Génesis 3',
  },
  {
    hebreo: 'אָדָם',
    nombre: 'Adán',
    transliteracion: 'Adam',
    aliases: ['adam', 'adán', 'adam', 'adamah', 'אדם', 'אָדָם'],
    significado: '"Hombre" o "De la tierra" (adamah). El primer ser humano, creado a imagen del Eterno.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 2',
  },
  {
    hebreo: 'נֹחַ',
    nombre: 'Noé',
    transliteracion: 'Noaj',
    aliases: ['noaj', 'noah', 'noe', 'noé', 'noach', 'נח', 'נֹחַ'],
    significado: '"Descanso" o "Consuelo". Justo que construyó el arca y salvó a la humanidad del diluvio.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 6',
  },
  {
    hebreo: 'יִרְמְיָהוּ',
    nombre: 'Jeremías',
    transliteracion: 'Yirmeyahu',
    aliases: ['yirmeyahu', 'jeremiah', 'jeremias', 'yirmi', 'ירמיהו', 'יִרְמְיָהוּ'],
    significado: '"YHVH exaltará". Profeta del exilio babilónico, autor de Lamentaciones.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Jeremías 1',
  },
  {
    hebreo: 'יְחֶזְקֵאל',
    nombre: 'Ezequiel',
    transliteracion: 'Yechezkel',
    aliases: ['yechezkel', 'ezekiel', 'ezequiel', 'yehezkel', 'יחזקאל', 'יְחֶזְקֵאל'],
    significado: '"Dios fortalecerá". Profeta en el exilio babilónico, visionario del Tercer Templo.',
    genero: 'M',
    categoria: 'Profeta',
    referencia: 'Ezequiel 1',
  },
  {
    hebreo: 'יְהוֹשֻׁעַ',
    nombre: 'Josué',
    transliteracion: 'Yehoshua',
    aliases: ['yehoshua', 'yehoshua', 'joshua', 'joshua', 'יהושע', 'יְהוֹשֻׁעַ'],
    significado: '"YHVH es salvación". Líder que condujo a Israel a la Tierra Prometida.',
    genero: 'M',
    categoria: 'Líder',
    referencia: 'Josué 1',
  },
  {
    hebreo: 'גִּדְעוֹן',
    nombre: 'Gedeón',
    transliteracion: 'Gideon',
    aliases: ['gideon', 'gedeon', 'gideon', 'gedeon', 'גדעון', 'גִּדְעוֹן'],
    significado: '"Destructor" o "Talador". Juez que derrotó a los madianitas con 300 hombres.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 6',
  },
  {
    hebreo: 'שִׁמְשׁוֹן',
    nombre: 'Sansón',
    transliteracion: 'Shimshon',
    aliases: ['shimshon', 'samson', 'sansón', 'shimshon', 'shimson', 'שמשון', 'שִׁמְשׁוֹן'],
    significado: '"Como el sol". Nazareo de gran fuerza que libró a Israel de los filisteos.',
    genero: 'M',
    categoria: 'Juez',
    referencia: 'Jueces 13',
  },
  {
    hebreo: 'חַנָּה',
    nombre: 'Ana',
    transliteracion: 'Jannah',
    aliases: ['jannah', 'hannah', 'hana', 'anna', 'hanah', 'חנה', 'חַנָּה'],
    significado: '"Gracia" o "Favor". Madre de Samuel, modelo de oración y fe.',
    genero: 'F',
    categoria: 'Matriarca',
    referencia: '1 Samuel 1',
  },
  {
    hebreo: 'מִרְיָם',
    nombre: 'Miriam',
    transliteracion: 'Miryam',
    aliases: ['miryam', 'miriam', 'maryam', 'maria', 'miryam', 'מרים', 'מִרְיָם'],
    significado: '"Amargura" o "Rebeldía". Hermana de Moisés y Aharon, profetisa que lideró a las mujeres.',
    genero: 'F',
    categoria: 'Profetisa',
    referencia: 'Éxodo 15',
  },
  {
    hebreo: 'אַהֲרֹן',
    nombre: 'Aarón',
    transliteracion: 'Aharon',
    aliases: ['aharon', 'aaron', 'aaron', 'aharon', 'אהרן', 'אַהֲרֹן'],
    significado: '"Montañista" o "Exaltado". Primer kohen gadol, hermano de Moisés.',
    genero: 'M',
    categoria: 'Kohen',
    referencia: 'Éxodo 4',
  },
  {
    hebreo: 'יְהוּדָה',
    nombre: 'Judá',
    transliteracion: 'Yehudah',
    aliases: ['yehudah', 'judah', 'juda', 'judá', 'yehuda', 'יהודה', 'יְהוּדָה'],
    significado: '"Alabaré a YHVH". Fundador de la tribu real de la cual proviene el Mashiaj.',
    genero: 'M',
    categoria: 'Patriarca',
    referencia: 'Génesis 29',
  },
  {
    hebreo: 'אָסָף',
    nombre: 'Asaf',
    transliteracion: 'Asaf',
    aliases: ['asaf', 'asaph', 'asaf', 'asaf', 'אסף', 'אָסָף'],
    significado: '"Recoger" o "Juntar". Levita y cantor del Templo, autor de muchos Salmos.',
    genero: 'M',
    categoria: 'Levita',
    referencia: '1 Crónicas 16',
  },
]

export const categorias = [
  'Todos',
  'Patriarca',
  'Matriarca',
  'Profeta',
  'Profetisa',
  'Rey',
  'Reina',
  'Líder',
  'Juez',
  'Kohen',
  'Levita',
]