import type { Reflexion } from './reflexionesTypes'

// SHEMOT (Éxodo) — parashiot 13 a 23
export const REFLEXIONES_SHEMOT: Reflexion[] = [
  {
    id: 'shemot',
    nombre: 'Shemot',
    hebreo: 'שְׁמוֹת',
    lectura: 'Éxodo 1:1 – 6:1',
    titulo: 'La redención flota en aguas inciertas',
    citaHebreo: 'וַיָּקׇם מֶלֶךְ־חָדָשׁ עַל־מִצְרָיִם אֲשֶׁר לֹא־יָדַע אֶת־יוֹסֵף',
    citaEspanol: 'Y se levantó sobre Egipto un rey nuevo que no conocía a Yosef',
    fuenteCita: 'Shemot 1:8',
    cuerpo: [
      'La esclavitud de Israel comenzó con una amnesia: "un rey nuevo que no conocía a Yosef". Las naciones tienen memoria corta para las bondades recibidas. El Salvador de Egipto se convirtió, en una generación, en la amenaza de Egipto. El pueblo de Israel aprendió ahí su primera lección de historia: no construyas tu seguridad sobre la gratitud de los imperios.',
      'Las parteras Shifrá y Puá desobedecieron el decreto de muerte "porque temían a Elohim" (Shemot 1:17). Son las primeras heroínas de la resistencia civil de la historia. Mientras el palacio decretaba genocidio, dos mujeres en las salas de parto decidían la vida. La redención del mundo empezó en manos de parteras, no de generales.',
      'Moshé creció en el palacio del opresor, pero salió a ver las cargas de sus hermanos (Shemot 2:11). El Midrash (Shemot Rabbá 1:27) alaba ese gesto: "puso sus ojos y su corazón para angustiarse con ellos". No se puede liberar a un pueblo desde un palacio; hay que salir a mirar sus ladrillos.',
      'En la zarza, el Eterno se presentó con un nombre que es pura promesa: "Ehyé asher ehyé — Seré quien seré" (Shemot 3:14). No es filosofía; es compañía. El Talmud (Berajot 9b) lo lee así: "Seré con ellos en esta aflicción como seré con ellos en las futuras". El nombre del Eterno es una promesa de presencia en cada exilio.',
      'Una madre escondió a su hijo en un cesto de juncos y lo confió al río. No tenía ejército ni plan: tenía un cesto y fe. La redención siempre nace flotando en aguas inciertas, mecida por manos que no ven el futuro pero confían en Quien lo sostiene.',
    ],
    fuente: 'Midrash Shemot Rabbá 1:27',
  },
  {
    id: 'vaera',
    nombre: 'Vaerá',
    hebreo: 'וָאֵרָא',
    lectura: 'Éxodo 6:2 – 9:35',
    titulo: 'El desfile de los ídolos caídos',
    citaHebreo: 'וָאֵרָא אֶל־אַבְרָהָם אֶל־יִצְחָק וְאֶל־יַעֲקֹב בְּאֵל שַׁדָּי',
    citaEspanol: 'Y aparecí a Avraham, a Itzjak y a Yaakov como El Shaddai',
    fuenteCita: 'Shemot 6:3',
    cuerpo: [
      'Moshé se queja al Eterno: "Desde que vine a Paró, le ha ido mal a este pueblo" (Shemot 5:22). Y la respuesta del Cielo no es un calendario, sino un nombre: "Yo soy el Eterno, y aparecí a los padres como El Shaddai". Antes de liberar al pueblo, el Eterno revela Su identidad. La redención no comienza con la salida de Egipto; comienza con el conocimiento de Quien redime.',
      'Las cuatro expresiones de redención de esta parashá — "los sacaré, los libraré, los redimiré, los tomaré" (Shemot 6:6-7) — son la base de las cuatro copas del Séder de Pésaj. Cada copa que levantamos en la mesa es una de estas promesas hecha vino. La liturgia es memoria líquida.',
      'Las plagas no fueron castigos al azar. El Midrash enseña que cada una golpeaba un ídolo egipcio: el Nilo convertido en sangre humillaba al dios-río; las ranas, a la diosa-rana Heket; la oscuridad, a Ra, el dios sol. Fue un desfile ordenado de ídolos cayendo uno a uno, para que Egipto e Israel supieran que "no hay otro como el Eterno" (Shemot 9:14).',
      'Y entre plaga y plaga, la frase terrible: "Paró endureció su corazón". La libertad del alfarero sobre el barro incluye dejar que el corazón obstinado coseche su propia dureza. El corazón se entrena: cada "no" a la verdad hace más fácil el siguiente "no".',
      'Todo lo que adoramos como dios, el Eterno lo puede convertir en polvo. Los ídolos modernos no se llaman Heket ni Ra, pero también caen: el mercado, el prestigio, la pantalla. Vaerá nos pregunta cada año: ¿qué ídolo está esperando su plaga en tu vida?',
    ],
    fuente: 'Shemot 6:6-7 — las cuatro expresiones de redención',
  },
  {
    id: 'bo',
    nombre: 'Bo',
    hebreo: 'בֹּא',
    lectura: 'Éxodo 10:1 – 13:16',
    titulo: 'La puerta marcada por la fe',
    citaHebreo: 'וְהָיָה הַדָּם לָכֶם לְאֹת עַל־הַבָּתִּים',
    citaEspanol: 'Y la sangre os será por señal en las casas',
    fuenteCita: 'Shemot 12:13',
    cuerpo: [
      '"Ven ante Paró" — Moshé no fue enviado a negociar, sino a anunciar. Las diez plagas terminan no cuando Paró cede, sino cuando el propósito del Eterno se cumple. La historia no gira alrededor del trono de Egipto; gira alrededor de la palabra de Dios.',
      'La primera mitzvá dada a todo el pueblo fue el calendario: "Este mes os será principio de meses" (Shemot 12:2). Antes de salir de la esclavitud, Israel recibió el dominio de su tiempo. El esclavo no posee sus días; el hombre libre santifica su calendario. Por eso el calendario hebreo no es una curiosidad: es un acta de libertad.',
      'La sangre del cordero en los dinteles no salvaba por la virtud de los que dormían dentro, sino por su obediencia. "Veré la sangre y pasaré de largo" (Shemot 12:13). La noche más oscura de Egipto fue la más iluminada de Israel: mientras afuera caía el juicio, adentro las familias comían de pie, con el bastón en la mano, listas para salir.',
      'Y la orden de contarlo: "Lo contarás a tu hijo en aquel día" (Shemot 13:8). La memoria es mandamiento, no nostalgia. Cada Pésaj, el Séder repite la escena: padres que cuentan, hijos que preguntan. La tradición no es un museo; es una conversación de mesa que lleva tres mil años sin interrumpirse.',
      'La Pascua comienza siempre igual: con una puerta marcada por la fe y una noche de salida apresurada hacia la libertad. Toda liberación verdadera tiene esa forma: sangre en el dintel, pan sin levadura, zapatos puestos, y un pueblo que sale de noche hacia un desierto que no conoce pero que le pertenece.',
    ],
    fuente: 'Shemot 12:2 — la primera mitzvá nacional',
  },
  {
    id: 'beshalaj',
    nombre: 'Beshalaj',
    hebreo: 'בְּשַׁלַּח',
    lectura: 'Éxodo 13:17 – 17:16',
    titulo: 'El mar se abre al primer paso',
    citaHebreo: 'וַיָּאֹמֶר יְהוָה אֶל־מֹשֶׁה מַה־תִּצְעַק אֵלָי דַּבֵּר אֶל־בְּנֵי־יִשְׂרָאֵל וְיִסָּעוּ',
    citaEspanol: 'Y dijo el Eterno a Moshé: ¿Por qué clamas a Mí? Di a los hijos de Israel que avancen',
    fuenteCita: 'Shemot 14:15',
    cuerpo: [
      'Delante el mar, atrás el ejército, a los lados el desierto. El pueblo hizo lo que haría cualquiera: entró en pánico y añoró los calderos de Egipto. La esclavitud conocida siempre parece más segura que la libertad desconocida. Por eso el éxodo más difícil no es el de Egipto; es el de la mentalidad de esclavo.',
      'La tradición (Sotá 37a) cuenta que las aguas no se abrieron hasta que Najshón ben Aminadav entró al mar y el agua le llegó a las narices. El Eterno dijo: "¿Por qué clamas? Di a los hijos de Israel que avancen". Los milagros esperan a veces un primer paso hacia el agua. La fe no es ver el camino seco: es mojarse primero.',
      'El cántico del mar es la primera poesía colectiva de Israel: "Cantaré al Eterno, porque se ha exaltado; caballo y jinete arrojó al mar" (Shemot 15:1). La redención verdadera siempre termina en canción. Cuando el pueblo aprenda a cantar lo que antes lloraba, la liberación estará completa.',
      'En el desierto cayó el maná: pan del cielo, ración diaria, sin posibilidad de acumular (excepto para Shabat). El Eterno enseñó a un pueblo de esclavos la economía de la confianza: cada mañana, la provisión; cada noche, la gratitud. Quien acumulaba por miedo, amanecía con gusanos.',
      'Cuando no haya salida, recuerda: el Eterno es experto en abrir mares, no en cerrar puertas. Y los mares no se abren para los que oran desde la orilla, sino para los que aceptan mojarse los pies.',
    ],
    fuente: 'Talmud Bavlí, Sotá 37a',
  },
  {
    id: 'itro',
    nombre: 'Itro',
    hebreo: 'יִתְרוֹ',
    lectura: 'Éxodo 18:1 – 20:23',
    titulo: 'Haremos y escucharemos',
    citaHebreo: 'כֹּל אֲשֶׁר־דִּבֶּר יְהוָה נַעֲשֶׂה וְנִשְׁמָע',
    citaEspanol: 'Todo lo que el Eterno ha dicho, haremos y escucharemos',
    fuenteCita: 'Shemot 24:7',
    cuerpo: [
      'Antes del trueno del Sinaí, un suegro madianita le dio a Moshé el mejor consejo administrativo de la historia: "Esto que haces no es bueno; te desgastarás tú y el pueblo" (Shemot 18:17-18). Itro, un sacerdote pagano convertido, enseñó al profeta más grande a delegar. El Eterno también habla por bocas inesperadas, y la humildad consiste en escuchar la verdad venga de donde venga.',
      'El Sinaí no fue una cátedra: fue una boda. El Midrash lee el relato como una ceremonia nupcial: el monte como jupá, la Torá como ketubá, Israel como la novia que dice "sí". Los mandamientos no son un reglamento impuesto; son los votos de un matrimonio.',
      '"Haremos y escucharemos": Israel puso la acción antes que la comprensión. El Talmud (Shabat 88a) dice que por esa respuesta sesenta miríadas de ángeles descendieron a coronar al pueblo. Hay verdades que solo se entienden desde adentro de la obediencia: primero el paso, después el paisaje.',
      'Los diez dichos no comienzan con "no matarás": comienzan con "Yo soy el Eterno tu Elohim que te saqué de la tierra de Egipto" (Shemot 20:2). La moral de la Torá no cuelga del aire: cuelga de la redención. Obedecemos no por miedo al castigo, sino por gratitud a la liberación.',
      'Y noten el detalle: el Eterno habló desde el monte, pero el pueblo escuchó desde abajo. La Torá fue dada en un desierto, territorio de nadie, para que ningún pueblo pueda decir "es mía". La palabra del Eterno pertenece a todos los que se acercan a recibirla.',
    ],
    fuente: 'Talmud Bavlí, Shabat 88a',
  },
  {
    id: 'mishpatim',
    nombre: 'Mishpatim',
    hebreo: 'מִשְׁפָּטִים',
    lectura: 'Éxodo 21:1 – 24:18',
    titulo: 'La santidad de los detalles',
    citaHebreo: 'אֵלֶּה הַמִּשְׁפָּטִים אֲשֶׁר תָּשִׂים לִפְנֵיהֶם',
    citaEspanol: 'Y estas son las leyes que pondrás delante de ellos',
    fuenteCita: 'Shemot 21:1',
    cuerpo: [
      'Inmediatamente después del trueno del Sinaí, la Torá baja a lo concreto: el esclavo hebreo, el ojo por ojo, el buey que hirió al buey, el depósito que desapareció. El mensaje es claro: la santidad no vive solo en la cima del monte; vive en cómo pagamos, cómo devolvemos, cómo tratamos al que trabaja para nosotros.',
      'Rashi nota que la parashá comienza con la conjunción "y" — "Y estas son las leyes" — uniendo el Sinaí con los tribunales. Las leyes civiles de Israel no son un añadido secular: fueron dadas en el mismo Sinaí que los diez mandamientos. Para la Torá no existe la división entre lo religioso y lo civil: todo es sagrado, porque todo es de la vida.',
      '"Al extranjero no lo oprimirás, porque ustedes conocen el alma del extranjero, pues extranjeros fueron en la tierra de Egipto" (Shemot 23:9). Es el mandamiento más repetido de la Torá: la memoria de la propia humillación como escuela de justicia. El pueblo que fue oprimido no tiene permiso de convertirse en opresor.',
      'Las leyes del daño corporal parecen duras — "ojo por ojo" (Shemot 21:24) — pero el Talmud (Bavá Kama 83b) explica que los sabios las leyeron siempre como compensación monetaria. La Torá no busca venganza; busca restitución. La justicia bíblica no pregunta "¿cómo castigo?", sino "¿cómo reparo?".',
      'Una Torá que no protege al desamparado no es Torá: es religión de palabra vacía. La viuda, el huérfano y el extranjero son el termómetro de la parashá: si la comunidad los cuida, el Eterno habita ahí; si los olvida, ningún altar la salva.',
    ],
    fuente: 'Talmud Bavlí, Bavá Kama 83b',
  },
  {
    id: 'teruma',
    nombre: 'Terumá',
    hebreo: 'תְּרוּמָה',
    lectura: 'Éxodo 25:1 – 27:19',
    titulo: 'La morada se construye con corazones',
    citaHebreo: 'וְעָשׂוּ לִי מִקְדָּשׁ וְשָׁכַנְתִּי בְּתוֹכָם',
    citaEspanol: 'Y me harán un santuario, y habitaré entre ellos',
    fuenteCita: 'Shemot 25:8',
    cuerpo: [
      '"Que me hagan un santuario y habitaré entre ellos" — el verso no dice "en él" sino "entre ellos". El Eterno no busca un edificio para vivir; busca un pueblo entre el cual habitar. El Mishkán es solo el punto de encuentro: la morada verdadera es la comunidad reunida alrededor de Su presencia.',
      'La ofrenda para el Mishkán se pedía "de todo hombre cuyo corazón lo mueva" (Shemot 25:2). No impuesto, no cuota: impulso del corazón. El oro del santuario no se recaudó; se derramó. La morada del Eterno se construye solo con lo que el corazón dona — lo obligado sirve para muchas cosas, pero no para arquitectura sagrada.',
      'Los querubines del arca se miraban uno al otro, y el Eterno hablaba "de entre los dos querubines" (Shemot 25:22). El Talmud (Bavá Batrá 99a) nota la maravilla: la voz del Infinito surgía del espacio estrecho entre dos figuras. Así es la comunidad: la presencia no habita en cada uno por separado, sino en el espacio que creamos entre nosotros.',
      'El menorá, la mesa, el altar: cada utensilio del Mishkán tenía medidas exactas. La espiritualidad bíblica no es improvisación mística; es precisión amorosa. El Eterno habita en los detalles bien hechos tanto como en las grandes visiones.',
      'Y la pregunta que queda flotando desde el desierto hasta hoy: si el Eterno del universo cabía entre dos querubines, ¿cómo no va a caber en una casa de estudio de Los Teques? Donde dos o tres se reúnen en Su nombre, el espacio entre ellos se vuelve arca.',
    ],
    fuente: 'Talmud Bavlí, Bavá Batrá 99a',
  },
  {
    id: 'tetzave',
    nombre: 'Tetzavé',
    hebreo: 'תְּצַוֶּה',
    lectura: 'Éxodo 27:20 – 30:10',
    titulo: 'El aceite machacado para la luz',
    citaHebreo: 'שֶׁמֶן זַיִת זָךְ כָּתִית לַמָּאוֹר',
    citaEspanol: 'Aceite puro de oliva, machacado, para la luz',
    fuenteCita: 'Shemot 27:20',
    cuerpo: [
      'El aceite de la menorá debía ser "machacado para la luz": la aceituna solo entrega su luz cuando es prensada. El Midrash (Shemot Rabbá 36:1) aplica la imagen al pueblo de Israel: como el olivo, Israel da su mejor luz cuando es golpeado. Hay vidas quebrantadas que iluminan más que las vidas enteras.',
      'Tetzavé es la única parashá desde el nacimiento de Moshé donde su nombre no aparece. La tradición (Baál HaTurim) explica que Moshé había dicho "bórrame de Tu libro" al interceder por el pueblo, y las palabras de los justos pesan incluso cuando el Eterno las perdona. En esta parashá, el líder desaparece y solo queda el servicio. A veces la mayor gloria de un líder es hacerse invisible.',
      'Las vestiduras del Cohen Gadol eran "para gloria y para esplendor" (Shemot 28:2). El pectoral con doce piedras, una por tribu, sobre el corazón: el sacerdote no entraba al santuario sin llevar a todo el pueblo sobre su pecho. Quien sirve al Eterno no puede dejar afuera a nadie; el corazón del servidor es un censo permanente.',
      'En el borde del manto del Cohen Gadol colgaban campanillas de oro y granadas, "para que se oiga su sonido cuando entre al santuario" (Shemot 28:35). La santidad no se esconde: suena. Quien lleva la presencia de un pueblo sobre el corazón debe dejarse escuchar — la vida santa hace ruido de campanillas en un mundo silenciado.',
      'Si hoy te sientes machacado, quizás el Eterno está preparando tu mejor llama. La menorá no pregunta al olivo si quiere ser prensado; le pregunta si quiere alumbrar. Y la respuesta del olivo fiel es su propio brillo.',
    ],
    fuente: 'Midrash Shemot Rabbá 36:1',
  },
  {
    id: 'ki-tisa',
    nombre: 'Ki Tisá',
    hebreo: 'כִּי תִשָּׂא',
    lectura: 'Éxodo 30:11 – 34:35',
    titulo: 'El dios que cabe en un bolsillo',
    citaHebreo: 'וַיִּקָּהֵל הָעָם עַל־אַהֲרֹן וַיֹּאמְרוּ אֵלָיו קוּם עֲשֵׂה־לָנוּ אֱלֹהִים',
    citaEspanol: 'Y se reunió el pueblo contra Aarón y le dijeron: Levántate, haznos dioses',
    fuenteCita: 'Shemot 32:1',
    cuerpo: [
      'Cuarenta días sin Moshé y el pueblo fabricó un becerro de oro. No un ídolo ideológico: un sustituto de emergencia, un dios de bolsillo para calmar la ansiedad. La idolatría rara vez nace de la maldad; nace de la impaciencia. No soportamos al Dios invisible que se demora, y entonces fundimos nuestros pendientes en algo visible.',
      'Aarón cedió, recogió el oro, fundió el becerro — y declaró: "Fiesta para el Eterno mañana" (Shemot 32:5). Noten la trampa: el becerro no se presentó como otro dios, sino como una fiesta del mismo Dios. La idolatría más peligrosa no niega al Eterno; le construye una imagen "en Su nombre".',
      'Moshé bajó del monte, rompió las tablas — y luego hizo algo más grande que traerlas: intercedió. "Si no, bórrame de Tu libro" (Shemot 32:32). El líder que había visto la idolatría con sus propios ojos eligió morir con su pueblo antes que vivir sin él. El perdón del Eterno se encontró con un corazón dispuesto a ser borrado por amor.',
      'Y luego, la segunda revelación del Nombre, la más tierna de la Torá: "Eterno, Eterno, El misericordioso y compasivo, tardo a la ira y grande en clemencia y verdad" (Shemot 34:6). Las trece cualidades de la misericordia no fueron reveladas en el Sinaí de la gloria, sino después del becerro. El corazón de Dios se conoce mejor en el perdón que en el trueno.',
      'El Eterno escribe con mano lenta, pero con tinta eterna. Paciencia: el Dios invisible vale la espera. Lo que fabricamos para no esperar, termina fundiéndose en polvo — y lo que esperamos con fe, termina bajando del monte en dos tablas nuevas.',
    ],
    fuente: 'Shemot 34:6-7 — las trece cualidades de la misericordia',
  },
  {
    id: 'vayakhel',
    nombre: 'Vayakhel',
    hebreo: 'וַיַּקְהֵל',
    lectura: 'Éxodo 35:1 – 38:20',
    titulo: 'El día que hubo que frenar la generosidad',
    citaHebreo: 'וַיֹּאמְרוּ לֵאמֹר מַרְבִּים הָעָם לְהָבִיא',
    citaEspanol: 'Y dijeron: El pueblo trae más de lo necesario',
    fuenteCita: 'Shemot 36:5',
    cuerpo: [
      'La parashá comienza con una reunión — "vayakhel" — y una orden: guardar el Shabat antes de construir el Mishkán. Ni siquiera el santuario justifica trabajar en Shabat. El descanso no es una pausa en la obra sagrada: es la puerta de entrada a ella. Primero el Shabat, luego el Mishkán.',
      'Y entonces pasó algo único en toda la Torá: el pueblo trajo tanto que Moshé tuvo que mandar frenar la colecta. "El pueblo trae más de lo necesario" (Shemot 36:5). Es la única vez en la historia bíblica que hubo que detener la generosidad. Cuando el corazón despierta, la abundancia desborda.',
      'Noten el orden de la historia: esta parashá viene inmediatamente después del becerro de oro. El mismo pueblo que fundió sus pendientes para un ídolo ahora los trae para el santuario. No eran dos pueblos distintos: era el mismo oro, las mismas manos, distinto corazón. La diferencia entre la idolatría y la santidad no está en los materiales, sino en el destino de la entrega.',
      'Betzalel, el arquitecto del Mishkán, fue llenado "del espíritu de Elohim, en sabiduría, en entendimiento y en ciencia" (Shemot 35:31). La primera persona de la Biblia llena del Espíritu no fue un profeta ni un sacerdote: fue un artesano. El Eterno también se derrama sobre las manos que saben labrar, tejer, grabar y construir.',
      'Que nuestras comunidades conozcan algún día ese "problema": tener que decir basta porque la generosidad desbordó la obra. No se llega ahí con campañas de recaudación; se llega con corazones despiertos. El oro fluye solo cuando el corazón se enciende primero.',
    ],
    fuente: 'Shemot 36:5-7',
  },
  {
    id: 'pekudei',
    nombre: 'Pekudei',
    hebreo: 'פְקוּדֵי',
    lectura: 'Éxodo 38:21 – 40:38',
    titulo: 'La gloria visita el orden hecho con amor',
    citaHebreo: 'וַיְכַס הֶעָנָן אֶת־אֹהֶל מוֹעֵד וּכְבוֹד יְהוָה מָלֵא אֶת־הַמִּשְׁכָּן',
    citaEspanol: 'Y la nube cubrió la tienda de reunión, y la gloria del Eterno llenó el Mishkán',
    fuenteCita: 'Shemot 40:34',
    cuerpo: [
      'Pekudei comienza con una contabilidad: todo el oro, toda la plata, todo el bronce del Mishkán, contado pieza por pieza. El pueblo había dado con el corazón, y los administradores rindieron cuentas con exactitud. La transparencia no deshonra lo sagrado: lo protege. Donde hay ofrendas, debe haber números claros.',
      'Y cuando todo estuvo terminado, Moshé examinó la obra: "Y he aquí que la habían hecho como el Eterno había mandado… y Moshé los bendijo" (Shemot 39:43). El líder no inventó, no añadió, no decoró: verificó la obediencia y bendijo. La fidelidad al mandato es más preciosa que la creatividad.',
      'El Mishkán se levantó "en el primer mes, del segundo año, el día primero del mes" (Shemot 40:17): exactamente un año después de la salida de Egipto. La redención que comenzó con la sangre en los dinteles terminó con la gloria en el tabernáculo. El Eterno no libera a medio camino: lleva a Su pueblo del dintel a la Shejiná.',
      'Y entonces la nube descendió y "Moshé no podía entrar a la tienda de reunión, porque la nube reposaba sobre ella" (Shemot 40:35). Ni siquiera el arquitecto de la obra pudo entrar cuando la presencia la llenó. Hay momentos en que el Eterno toma posesión tan completamente de Su casa que hasta los constructores quedan afuera, adorando desde la puerta.',
      'La gloria no visita la improvisación; visita el orden hecho con amor. El Eterno habita también en los detalles pequeños: en cada gancho contado, en cada viga en su lugar, en cada cuenta rendida con honestidad. Prepara tu casa así, y la nube sabrá dónde descender.',
    ],
    fuente: 'Shemot 39:43',
  },
]

// VAYIKRÁ (Levítico) — parashiot 24 a 33
export const REFLEXIONES_VAYIKRA: Reflexion[] = [
  {
    id: 'vayikra',
    nombre: 'Vayikrá',
    hebreo: 'וַיִּקְרָא',
    lectura: 'Levítico 1:1 – 5:26',
    titulo: 'La llamada que comienza con amor',
    citaHebreo: 'וַיִּקְרָא אֶל־מֹשֶׁה וַיְדַבֵּר יְהוָה אֵלָיו מֵאֹהֶל מוֹעֵד',
    citaEspanol: 'Y llamó a Moshé, y le habló el Eterno desde la tienda de reunión',
    fuenteCita: 'Vayikrá 1:1',
    cuerpo: [
      'El tercer libro de la Torá comienza con una llamada: "Vayikrá — y llamó". La tradición nota que la alef final del verbo se escribe pequeña en el rollo de la Torá. Moshé, en su humildad, quería escribir "vayikár" (y se encontró) en vez de "vayikrá" (y llamó): como si el encuentro con el Eterno hubiera sido casual. La grandeza verdadera se avergüenza de sus propios títulos.',
      'Los sacrificios no alimentan al Eterno — "¿Acaso como yo carne de toros?" (Tehilim 50:13). Cada ofrenda era una manera de decir "mi vida es Tuya" con las manos. El animal en el altar era un espejo: el que ofrecía ponía sus manos sobre la cabeza de la víctima y confesaba. El sacrificio no transfería la culpa; la hacía visible para poder soltarla.',
      'El Midrash (Vayikrá Rabbá 1:3) enseña que antes de hablarle, el Eterno siempre llamaba a Moshé por su nombre, como gesto de afecto. Así se inicia todo encuentro verdadero: con un nombre pronunciado con amor. El Eterno no grita desde el cielo; llama por el nombre.',
      'Entre las ofrendas hay una quebradora: la ofrenda por el pecado involuntario. La Torá dedica capítulos enteros a los errores cometidos "por inadvertencia" (Vayikrá 4:2). El mensaje es revolucionario: se puede fallar sin querer, y aun así la Torá ofrece camino de reparación. La conciencia tranquila no se logra con perfección, sino con arrepentimiento bien encaminado.',
      'Hoy nuestros sacrificios son la plegaria, el arrepentimiento y la misericordia — como dijo Oseas: "ofreceremos los novillos de nuestros labios" (Oseas 14:3). Y siguen teniendo aroma que sube al cielo. El altar cambió de forma, no de dirección.',
    ],
    fuente: 'Midrash Vayikrá Rabbá 1:3',
  },
  {
    id: 'tzav',
    nombre: 'Tzav',
    hebreo: 'צַו',
    lectura: 'Levítico 6:1 – 8:36',
    titulo: 'El fuego que no se apaga',
    citaHebreo: 'אֵשׁ תָּמִיד תּוּקַד עַל־הַמִּזְבֵּחַ לֹא תִכְבֶּה',
    citaEspanol: 'Fuego continuo arderá sobre el altar; no se apagará',
    fuenteCita: 'Vayikrá 6:6',
    cuerpo: [
      'El fuego del altar debía arder continuamente: "no se apagará". Cada mañana el sacerdote removía las cenizas, añadía leña y avivaba las brasas. El fuego de ayer no sirve para hoy. Así la fe: no se hereda encendida, se aviva cada día, cada uno con su propia leña.',
      'Y noten la primera tarea del servicio sacerdotal diario: retirar la ceniza (Vayikrá 6:3). Antes de ofrecer algo nuevo, hay que sacar lo quemado de ayer. La vida espiritual también acumula ceniza: sacrificios viejos, fervores consumidos, restos de fuegos pasados. Quien no retira su ceniza termina adorando un altar lleno de restos en vez de fuego.',
      'El sacerdote sacaba la ceniza con vestiduras especiales y la llevaba "fuera del campamento, a un lugar limpio" (Vayikrá 6:4). Incluso la basura del altar era tratada con dignidad y llevada a un lugar limpio. En la casa del Eterno no hay tareas deshonrosas: hay cenizas que también se sirven con reverencia.',
      'La ofrenda del sacerdote, a diferencia de las demás, se quemaba por completo: "toda ofrenda de sacerdote será íntegramente quemada; no se comerá" (Vayikrá 6:16). Quien sirve al altar no puede beneficiarse de su propio servicio. El servidor verdadero da sin reservarse una porción.',
      'La llama continua del altar es el corazón de esta parashá: no el fuego espectacular del Sinaí, sino la brasa diaria, mantenida en silencio, mañana tras mañana. La santidad no es una explosión; es una constancia. "No se apagará" — esa es la promesa y el mandamiento.',
    ],
    fuente: 'Vayikrá 6:6',
  },
  {
    id: 'shemini',
    nombre: 'Sheminí',
    hebreo: 'שְּׁמִינִי',
    lectura: 'Levítico 9:1 – 11:47',
    titulo: 'El fuego extraño del entusiasmo sin instrucción',
    citaHebreo: 'וַיָּבִיאוּ לִפְנֵי יְהוָה אֵשׁ זָרָה אֲשֶׁר לֹא צִוָּה אֹתָם',
    citaEspanol: 'Y ofrecieron delante del Eterno fuego extraño, que Él no les había mandado',
    fuenteCita: 'Vayikrá 10:1',
    cuerpo: [
      'Era el octavo día, el día de la inauguración del Mishkán, el día más feliz del desierto. La gloria había descendido, el fuego del Eterno había consumido la ofrenda, el pueblo entero gritaba de gozo. Y en medio de la fiesta, dos hijos de Aarón entraron con "fuego extraño" y el altar los consumió. La tragedia llegó en el día más luminoso.',
      '¿Qué hicieron mal Nadav y Avihú? El texto dice: ofrecieron fuego "que Él no les había mandado". No fue rebeldía declarada; fue iniciativa no pedida. El entusiasmo sin instrucción puede ser peligroso en las cosas santas. No todo fervor es obediencia, y no toda llama encendida por el hombre agrada al Cielo.',
      'La respuesta de Aarón es una de las frases más desgarradoras de la Torá: "Y Aarón calló" (Vayikrá 10:3). Moshé le explicó, y el padre de los muertos calló. Hay dolor tan grande que solo cabe en el silencio. El Talmud (Zevajim 115b) dice que por ese silencio, Aarón recibió una revelación directa del Eterno. A veces el silencio del que sufre se convierte en el oído de Dios.',
      'La parashá termina con las leyes de los animales puros e impuros: "Seréis santos, porque santo soy Yo" (Vayikrá 11:44). La santidad baja del altar a la mesa: lo que entra por la boca también forma el alma. La Torá no separa lo espiritual de lo cotidiano; santifica hasta el menú.',
      'Acércate al Eterno con pasión, sí — pero con la pasión que Él pidió, no con la que se nos ocurre. La obediencia no mata el fervor; lo canaliza hacia el altar correcto.',
    ],
    fuente: 'Talmud Bavlí, Zevajim 115b',
  },
  {
    id: 'tazria',
    nombre: 'Tazría',
    hebreo: 'תַזְרִיעַ',
    lectura: 'Levítico 12:1 – 13:59',
    titulo: 'Nadie se diagnostica a solas',
    citaHebreo: 'וְרָאָהוּ הַכֹּהֵן',
    citaEspanol: 'Y lo mirará el sacerdote',
    fuenteCita: 'Vayikrá 13:3',
    cuerpo: [
      'Las leyes de la tzaraat — la lepra bíblica — ocupan dos parashiot enteras, y en ellas hay una regla sorprendente: la mancha debía ser examinada por el sacerdote. El enfermo no podía declararse a sí mismo ni puro ni impuro: "lo mirará el sacerdote". No somos jueces imparciales de nuestras propias manchas.',
      'La tradición (Arajín 16a) enseña que la tzaraat venía como consecuencia del lashón hará, la lengua maligna: Miriam habló de Moshé y fue cubierta de manchas; el que despedaza reputaciones termina él mismo despedazado. La piel delataba lo que el corazón escondía. Las enfermedades del alma siempre encuentran una superficie donde hacerse visibles.',
      'Y el castigo era el aislamiento: "fuera del campamento será su morada" (Vayikrá 13:46). El que había dividido con su lengua era separado de la comunidad. La medida correspondía a la medida: quien siembra distancia, cosecha distancia.',
      'Pero el sacerdote no solo diagnosticaba: también declaraba la sanación. El mismo que declaraba impuro tenía la autoridad de declarar puro. En la Torá, el juicio y la restauración viven en la misma boca. Por eso la comunidad necesita autoridades espirituales sanas: no policías del alma, sino médicos del alma.',
      'Necesitamos ojos externos, comunidad, espejo. Por eso el Beit Midrash existe: para que nadie se diagnostique a solas su propia lepra del alma. El autoanálisis sin comunidad es tan riesgoso como la automedicación: necesitamos quien nos mire con amor y nos diga la verdad.',
    ],
    fuente: 'Talmud Bavlí, Arajín 16a',
  },
  {
    id: 'metzora',
    nombre: 'Metzorá',
    hebreo: 'מְּצֹרָע',
    lectura: 'Levítico 14:1 – 15:33',
    titulo: 'Dos pájaros y una libertad',
    citaHebreo: 'וְשִׁלַּח אֶת־הַצִּפּוֹר הַחַיָּה אֶל־פְּנֵי הַשָּׂדֶה',
    citaEspanol: 'Y soltará el ave viva hacia el campo abierto',
    fuenteCita: 'Vayikrá 14:7',
    cuerpo: [
      'El rito de purificación del leproso sanado es una de las escenas más poéticas de la Torá: dos pájaros, madera de cedro, carmesí e hisopo. Un pájaro era sacrificado sobre agua viva; el otro, bañado en la sangre del primero, era soltado hacia el campo. Uno moría, otro volaba libre.',
      'El Midrash (Vayikrá Rabbá 16:7) lee los detalles como parábola: el leproso se había enaltecido como el cedro — el árbol más alto — y debía humillarse como el hisopo — la hierba más baja. La soberbia enferma; la humildad sana. Y el carmesí, hilo rojo, recuerda que la curación pasa por la sangre.',
      'El ave viva soltada al campo no es un detalle decorativo: es el retrato del sanado. Toda sanación es así — algo muere (la vieja vida) y algo vuela (la nueva). El que fue sanado no vuelve al campamento como antes: regresa como quien ha visto volar su propia libertad.',
      'Y noten que la Torá habla del "día de su purificación" (Vayikrá 14:2) como de una fecha cierta: la enfermedad tenía término. La lepra no era identidad, era proceso. Ninguna mancha es el nombre verdadero de una persona; es solo una temporada entre el diagnóstico y el vuelo.',
      'Cuando el Eterno te limpie, suelta el pájaro vivo y no mires atrás a la jaula. Hay gente que, sanada, sigue visitando su jaula todos los días: la culpa vieja, el apodo del pasado, la mancha que ya no existe. El rito ordena lo contrario: el ave vuela al campo, y el corazón debe volar con ella.',
    ],
    fuente: 'Midrash Vayikrá Rabbá 16:7',
  },
  {
    id: 'ajarei-mot',
    nombre: 'Ajarei Mot',
    hebreo: 'אַחֲרֵי מוֹת',
    lectura: 'Levítico 16:1 – 18:30',
    titulo: 'El chivo que lleva las cargas al desierto',
    citaHebreo: 'וְנָשָׂא הַשָּׂעִיר עָלָיו אֶת־כׇּל־עֲוֺנֹתָם אֶל־אֶרֶץ גְּזֵרָה',
    citaEspanol: 'Y el chivo llevará sobre sí todas las iniquidades a tierra inhabitada',
    fuenteCita: 'Vayikrá 16:22',
    cuerpo: [
      'Una vez al año, el Cohen Gadol entraba al Lugar Santísimo. Solo él, solo ese día, solo con incienso y sangre. La santidad tiene puertas, pero también tiene tiempos. Iom Kipur enseña que la intimidad con el Eterno no es acceso permanente sin reverencia: es encuentro preparado con ayuno, confesión y temor santo.',
      'Dos chivos eran presentados: uno para el Eterno, otro para Azazel. Sobre la cabeza del segundo, el sacerdote confesaba "todas las iniquidades de los hijos de Israel" (Vayikrá 16:21) y lo enviaba al desierto. La imagen es inolvidable: el pecado del pueblo, cargado sobre un animal, alejándose hacia la tierra inhabitada, hasta desaparecer del horizonte.',
      'El Talmud (Yomá 67b) cuenta que se ataba un hilo carmesí en la puerta del Templo, y si el pueblo era perdonado, el hilo se volvía blanco: "Aunque vuestros pecados sean como la grana, como la nieve serán emblanquecidos" (Isaías 1:18). El perdón del Eterno no es cosmético: es transformación de color, de esencia, de destino.',
      '"Porque en este día se hará expiación por ustedes para purificarlos; de todos sus pecados delante del Eterno serán purificados" (Vayikrá 16:30). El verso es la madre de todo el mensaje de Iom Kipur: la purificación no la logra el hombre; la concede el Eterno. Nosotros ayunamos, confesamos, nos postramos — pero quien limpia es Él.',
      'Hay cargas que no se resuelven analizándolas: se resuelven soltándolas al desierto donde ya no vuelven. El chivo de Azazel es la terapia más antigua de Israel: poner nombre a la culpa, cargarla fuera del campamento, y dejar que el desierto se la trague. Lo que confiesas y sueltas, no vuelve a visitarte.',
    ],
    fuente: 'Talmud Bavlí, Yomá 67b; Isaías 1:18',
  },
  {
    id: 'kedoshim',
    nombre: 'Kedoshim',
    hebreo: 'קְדֹשִׁים',
    lectura: 'Levítico 19:1 – 20:27',
    titulo: 'La santidad se mide en espigas',
    citaHebreo: 'קְדֹשִׁים תִּהְיוּ כִּי קָדוֹשׁ אֲנִי יְהוָה אֱלֹהֵיכֶם',
    citaEspanol: 'Santos seréis, porque santo soy Yo, el Eterno vuestro Elohim',
    fuenteCita: 'Vayikrá 19:2',
    cuerpo: [
      '"Santos seréis" — la orden fue dicha a toda la congregación, no a un grupo de élite. Rashi nota que esta parashá fue dicha "en plena asamblea" porque la mayoría de los preceptos esenciales de la Torá dependen de ella. La santidad no es para sacerdotes ni místicos: es para el campesino, el comerciante, la madre, el jornalero.',
      'Y la Torá define la santidad con una lista sorprendentemente concreta: honrar a los padres, no robar, no mentir, no difamar, no guardar rencor, pagar al jornalero a tiempo, no poner tropiezo delante del ciego. Ninguna de estas mitzvot se cumple en el Templo: todas se cumplen en la calle. La santidad bíblica no es ritual; es relacional.',
      'En el centro exacto del libro de Vayikrá, como corazón de la Torá, está la frase: "Amarás a tu prójimo como a ti mismo" (Vayikrá 19:18). El rabí Akiva la llamó "el gran principio de la Torá" (Sifrá Kedoshim). No es un adorno poético: es el resumen de la mitad de los mandamientos.',
      'Y luego, la ley de las espigas: al cosechar, el dueño del campo debía dejar las orillas sin segar y las espigas caídas para el pobre y el extranjero (Vayikrá 19:9-10). Noten la elegancia: el pobre no recibía limosna de mano ajena; recogía él mismo su porción. La Torá protege la dignidad del necesitado, no solo su estómago.',
      'La Torá mide la espiritualidad por la generosidad. Puedes ayunar, orar y estudiar — pero si no dejas las orillas de tu campo para el pobre, la santidad aún no ha llegado a tu bolsillo. Ser santo es dejar espigas.',
    ],
    fuente: 'Sifrá Kedoshim; Vayikrá 19:9-10',
  },
  {
    id: 'emor',
    nombre: 'Emor',
    hebreo: 'אֱמֹר',
    lectura: 'Levítico 21:1 – 24:23',
    titulo: 'Las citas del calendario del Rey',
    citaHebreo: 'אֵלֶּה מוֹעֲדֵי יְהוָה מִקְרָאֵי קֹדֶשׁ',
    citaEspanol: 'Estas son las fiestas señaladas del Eterno, santas convocaciones',
    fuenteCita: 'Vayikrá 23:2',
    cuerpo: [
      'Emor contiene el calendario completo de las moedim: Shabat, Pésaj, el conteo del Omer, Shavuot, Rosh HaShaná, Iom Kipur, Sucot. Son llamadas "moedim" — citas señaladas. La misma palabra que se usa para una cita entre dos personas. El tiempo también se puede santificar: cada fiesta es una cita que el Eterno agendó con Su pueblo.',
      'Noten que la lista comienza con el Shabat (Vayikrá 23:3), antes que todas las fiestas. El Shabat es la madre de las moedim: la cita semanal de la que todas las demás aprenden su ritmo. Quien no guarda la cita semanal difícilmente entenderá las anuales.',
      'Entre Pésaj y Shavuot, la Torá ordena contar el Omer: cuarenta y nueve días, uno por uno, "desde el día siguiente al descanso" (Vayikrá 23:15). La espiritualidad del conteo es profunda: la libertad de Egipto no se completa en la salida, sino en la llegada al Sinaí. Salir es el primer paso; contar los días es aprender a valorar el camino hacia la Torá.',
      'Sucot cierra el ciclo: siete días en cabañas frágiles, "para que sepan vuestros descendientes que en cabañas hice habitar a los hijos de Israel" (Vayikrá 23:43). El pueblo que recibió una tierra con ciudades que no construyó debe recordar cada año la fragilidad de las paredes. La seguridad no está en los muros: está en la nube que cubría el desierto.',
      'No llegues tarde a las citas del Rey. Las moedim no son folklore ni tradición familiar: son encuentros agendados por el Dueño del tiempo. Cada una tiene su hora, su mes y su propósito — y la agenda ya está publicada desde el Sinaí.',
    ],
    fuente: 'Vayikrá 23',
  },
  {
    id: 'behar',
    nombre: 'Behar',
    hebreo: 'בְּהַר',
    lectura: 'Levítico 25:1 – 26:2',
    titulo: 'Inquilinos, no dueños',
    citaHebreo: 'כִּי־לִי כׇּל־הָאָרֶץ כִּי־גֵרִים וְתוֹשָׁבִים אַתֶּם עִמָּדִי',
    citaEspanol: 'Porque Mía es toda la tierra; pues forasteros y peregrinos sois vosotros conmigo',
    fuenteCita: 'Vayikrá 25:23',
    cuerpo: [
      'Cada siete años, la tierra debía descansar: un Shabat para el suelo. "En el séptimo año será Shabat de reposo para la tierra" (Vayikrá 25:2). La Torá declara que la tierra también tiene alma, también se cansa, también merece su séptimo día. Quien no deja descansar la tierra, no entendió el Shabat propio.',
      'Y cada cincuenta años, el Yovel: la trompeta sonaba en Iom Kipur y "proclamaréis libertad en la tierra a todos sus moradores" (Vayikrá 25:10) — el verso que hoy está grabado en la Campana de la Libertad de Filadelfia. Los esclavos salían libres, las tierras volvían a sus familias, las deudas se disolvían. La Torá construyó en el calendario un reinicio económico: ninguna desigualdad podía volverse eterna.',
      'La lógica detrás es revolucionaria: "La tierra no se venderá a perpetuidad, porque Mía es la tierra; pues forasteros y peregrinos sois vosotros conmigo". Somos inquilinos del mundo, no dueños. El Eterno es el propietario; nosotros, administradores temporales. Esta frase debería colgar en cada oficina, cada escritura de propiedad, cada tarjeta de crédito.',
      'El sabático parecía suicida: ¿qué comeremos el séptimo año? Y el Eterno respondió: "Yo mandaré Mi bendición sobre vosotros en el sexto año, y dará fruto por tres años" (Vayikrá 25:21). La obediencia económica también es un acto de fe: confiar en que la bendición del sexto año alcanza para lo que la obediencia "desperdicia" en el séptimo.',
      'Vivir como inquilinos cambia la forma de pisar la tierra: con gratitud, con cuidado, con la mano abierta. El que se cree dueño, se aferra; el que sabe que es peregrino, comparte. Behar nos pregunta cada año: ¿eres dueño o administrador de lo que tienes?',
    ],
    fuente: 'Vayikrá 25:10 — el verso de la Campana de la Libertad',
  },
  {
    id: 'bejukotai',
    nombre: 'Bejukotai',
    hebreo: 'בְּחֻקֹּתַי',
    lectura: 'Levítico 26:3 – 27:34',
    titulo: 'La alianza más terca que nuestras caídas',
    citaHebreo: 'וְאַף־גַּם־זֹאת בִּהְיוֹתָם בְּאֶרֶץ אֹיְבֵיהֶם לֹא־מְאַסְתִּים',
    citaEspanol: 'Y aun así, estando ellos en la tierra de sus enemigos, no los desecharé',
    fuenteCita: 'Vayikrá 26:44',
    cuerpo: [
      'Bejukotai es la parashá de las bendiciones y las advertencias: si caminan en Mis estatutos, lluvia a su tiempo; si no, la lista terrible de las consecuencias. La Torá no endulza la verdad. La alianza es real, y por eso sus términos son reales: hay dirección, hay consecuencia, hay historia con sentido.',
      'Las bendiciones son escandalosamente generosas: "Perseguirán cinco de vosotros a ciento, y ciento de vosotros a diez mil" (Vayikrá 26:8). La aritmética del Eterno no es la nuestra: la obediencia multiplica el valor de cada persona. Un pueblo pequeño y fiel pesa más que un imperio numeroso y corrupto.',
      'Y en medio de las advertencias más duras, cuando el texto describe el exilio y la tierra desolada, aparece una de las frases más tiernas de la Torá: "Y aun así, estando ellos en la tierra de sus enemigos, no los desecharé ni los abominaré para consumirlos, para romper Mi pacto con ellos" (Vayikrá 26:44). La alianza es más terca que nuestras caídas.',
      'El profeta Iermeíahu citaría esta esperanza en medio de la destrucción de Jerusalén, y el pueblo la ha repetido en cada exilio desde entonces: babilónico, romano, español, europeo. Cada generación que sobrevivió es un testimonio viviente de este versículo. El pueblo de Israel no existe por accidente histórico; existe por un pacto que el Eterno se niega a romper.',
      'Esa es la única garantía inquebrantable de nuestra historia: no nuestra fidelidad, sino la Suya. Nosotros tropezamos, caemos, nos dispersamos — y Él sigue diciendo "no los desecharé". El pacto no depende de nuestra perfección; depende de Su carácter.',
    ],
    fuente: 'Vayikrá 26:44',
  },
]
