import type { Reflexion } from './reflexionesTypes'

// BERESHIT (Génesis) — parashiot 1 a 12
export const REFLEXIONES_BERESHIT: Reflexion[] = [
  {
    id: 'bereshit',
    nombre: 'Bereshit',
    hebreo: 'בראשית',
    lectura: 'Génesis 1:1 – 6:8',
    titulo: 'Antes de la luz, un propósito',
    citaHebreo: 'בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ',
    citaEspanol: 'En el principio creó Elohim los cielos y la tierra',
    fuenteCita: 'Bereshit 1:1',
    cuerpo: [
      'La Torá no comienza con un mandamiento, sino con un acto de creación. Antes de pedirnos nada, el Eterno nos muestra lo que Él hace: traer orden del caos, luz de la oscuridad, palabra del silencio. El primer mensaje de la Torá no es "debes", sino "Él puede".',
      'Dice el Midrash (Bereshit Rabbá 1:1) que la Torá era el plano con el que el Eterno construyó el mundo. Como un arquitecto que mira sus planos antes de levantar cada muro, el Creador miró la Torá antes de crear cada cosa. Esto significa que estudiar Torá no es solo religión: es leer el manual de instrucciones del universo.',
      'Y noten el orden del relato: primero la separación de la luz de la oscuridad, luego las aguas de las aguas, luego la tierra del mar. La creación avanza por distinciones. Así también la vida del hombre: crecer es aprender a distinguir — entre lo santo y lo común, entre la verdad y la mentira, entre el yo y el otro.',
      '"Y fue la tarde y fue la mañana: día uno" (Bereshit 1:5). El día hebreo comienza al atardecer porque así lo establece el texto: primero la oscuridad, luego la luz. Toda etapa luminosa de nuestra vida nació en una noche. Quien hoy atraviesa oscuridad, está en el primer capítulo de su creación.',
      'Cada año, cuando volvemos a Bereshit, el Eterno nos concede el mismo regalo que le dio al mundo: comenzar de nuevo. No hay fracaso tan grande que no quepa en un nuevo "en el principio". El mismo que dijo "haya luz" sigue pronunciándolo sobre los caos de nuestra vida.',
    ],
    fuente: 'Midrash Bereshit Rabbá 1:1',
  },
  {
    id: 'noaj',
    nombre: 'Noaj',
    hebreo: 'נֹחַ',
    lectura: 'Génesis 6:9 – 11:32',
    titulo: 'El arca de una sola persona',
    citaHebreo: 'אֶת־הָאֱלֹהִים הִתְהַלֶּךְ־נֹחַ',
    citaEspanol: 'Con Elohim caminó Noaj',
    fuenteCita: 'Bereshit 6:9',
    cuerpo: [
      'Noaj vivió en la generación más corrupta de la historia y, sin embargo, "caminó con Elohim". No se le pide que salve al mundo; se le pide que construya un arca. La fidelidad no siempre consiste en cambiar la época, sino en mantenerse íntegro dentro de ella.',
      'El arca tenía una ventana arriba y una puerta al costado (Bereshit 6:16). El Talmud (Sanhedrín 108b) nota el detalle: la luz entraba de arriba, la gente por el lado. Así la vida del justo: la luz viene del cielo, pero la hospitalidad se practica a ras de tierra.',
      'Ciento veinte años construyó Noaj, según la tradición. Cada tabla que clavaba era un sermón silencioso. La gente pasaba, se burlaba, preguntaba: y él seguía martillando. Hay convicciones que no se predican con palabras, sino con constancia.',
      'Después del diluvio, el Eterno firma Su pacto con un arco en las nubes (Bereshit 9:13). El arco de guerra colgado en el cielo, apuntando lejos de la tierra: la señal de que la ira tiene fin y la misericordia tiene memoria. "Me acordaré de Mi pacto", dice el verso — el Eterno mismo elige recordar para no destruir.',
      'Noaj no salvó al mundo; salvó una semilla. A veces creemos que nuestra fe es pequeña frente al diluvio de la historia, pero al Eterno le bastan un arca, una familia y una paloma para reiniciar la creación. Tu fidelidad, aunque parezca mínima, es el arca de alguien.',
    ],
    fuente: 'Talmud Bavlí, Sanhedrín 108b',
  },
  {
    id: 'lej-leja',
    nombre: 'Lej Lejá',
    hebreo: 'לֶךְ־לְךָ',
    lectura: 'Génesis 12:1 – 17:27',
    titulo: 'El mapa se revela caminando',
    citaHebreo: 'לֶךְ־לְךָ מֵאַרְצְךָ וּמִמּוֹלַדְתְּךָ וּמִבֵּית אָבִיךָ',
    citaEspanol: 'Vete de tu tierra, de tu parentela y de la casa de tu padre',
    fuenteCita: 'Bereshit 12:1',
    cuerpo: [
      '"Vete de tu tierra": el primer mandamiento dirigido a un padre de Israel fue un mandamiento de movimiento. Antes de promesas, antes de pactos, antes de descendencia: movimiento. La fe comienza cuando los pies se despegan de lo conocido.',
      'Rashi nota la construcción inusual: no dice "lej" (ve), sino "lej lejá" (vete para ti). El destino de Avraham era también su propio beneficio: cada paso de obediencia es, en secreto, un paso hacia uno mismo. Dejar la tierra del padre fue la manera de encontrar al Padre.',
      'El texto nunca dice que Avraham supiera a dónde iba: "a la tierra que te mostraré". El Eterno no entrega el mapa completo; entrega el próximo paso. Quien exige ver todo el camino antes de caminar, jamás sale de Harán.',
      'Y la promesa que acompaña la partida es generosa: "Serás bendición" (Bereshit 12:2). No solo "serás bendecido": serás bendición. El que obedece se convierte en canal, no en depósito. Las bendiciones que el Eterno derrama sobre los que parten están destinadas a atravesarlos.',
      'Todos tenemos una Harán: un lugar cómodo, heredado, conocido. La voz que llamó a Avraham sigue llamando: deja tu tierra, tu parentela, la casa de tu padre. No para perderte, sino para encontrarte. El mapa se revela caminando, no mirándolo.',
    ],
    fuente: 'Rashi sobre Bereshit 12:1',
  },
  {
    id: 'vayera',
    nombre: 'Vayerá',
    hebreo: 'וַיֵּרָא',
    lectura: 'Génesis 18:1 – 22:24',
    titulo: 'La puerta abierta al mediodía',
    citaHebreo: 'וַיֵּרָא אֵלָיו יְהוָה בְּאֵלֹנֵי מַמְרֵא',
    citaEspanol: 'Y se le apareció el Eterno en los encinares de Mamré',
    fuenteCita: 'Bereshit 18:1',
    cuerpo: [
      'Avraham estaba sentado a la puerta de su tienda "al calor del día" (Bereshit 18:1), recién circuncidado, dolorido, en la hora más incómoda. Y precisamente ahí — en la incomodidad — el Eterno se le apareció. Las teofanías no buscan nuestros mejores momentos; buscan nuestras puertas abiertas.',
      'El Talmud (Bavá Metziá 86b) enseña que el Eterno mismo visitaba al enfermo — era el tercer día de la circuncisión de Avraham — cuando llegaron los tres viajeros. Y Avraham interrumpió la visita divina para atender a los extraños. De ahí aprende la tradición: recibir al prójimo es aún mayor que recibir a la Shejiná.',
      'Luego viene el diálogo más audaz de la Biblia: Avraham regatea por Sodoma. ¿Cincuenta justos? ¿Cuarenta y cinco? ¿Treinta? ¿Diez? Y el Eterno, en vez de ofenderse, responde a cada número. La plegaria que intercede no irrita al Cielo: lo invita. Quien ama de verdad, discute con Dios por los demás.',
      'La Akedá cierra la parashá: el cuchillo levantado y la voz que lo detiene. Avraham aprendió en el Moriá que el Eterno no quiere la muerte del hijo, sino la entrega del padre. Hay sacrificios que el Cielo pide solo para devolvérnoslos transformados.',
      'La hospitalidad de Avraham abrió una tienda; su intercesión abrió los cielos; su obediencia abrió la historia. Tres puertas, una misma llave: la disponibilidad. Al calor del mediodía, cuando menos cómodo estás, mantén tu puerta abierta.',
    ],
    fuente: 'Talmud Bavlí, Bavá Metziá 86b',
  },
  {
    id: 'jaye-sara',
    nombre: 'Jaié Sará',
    hebreo: 'חַיֵּי שָׂרָה',
    lectura: 'Génesis 23:1 – 25:18',
    titulo: 'Los años que esperan',
    citaHebreo: 'וַיִּהְיוּ חַיֵּי שָׂרָה מֵאָה שָׁנָה וְעֶשְׂרִים שָׁנָה וְשֶׁבַע שָׁנִים',
    citaEspanol: 'Y fueron los años de la vida de Sará ciento veintisiete años',
    fuenteCita: 'Bereshit 23:1',
    cuerpo: [
      'La parashá se llama "La vida de Sará" y comienza contando su muerte. El Midrash enseña que la vida de los justos no se mide por su final, sino por su contenido: los ciento veintisiete años de Sará "fueron todos iguales en bondad" (Bereshit Rabbá 58:1). Vivir bien es llenar los años, no solo contarlos.',
      'Sará esperó noventa años por un hijo. Noventa años de sonrisas amables cuando le hablaban de la promesa, de silencios en las noches sin luna. Y sin embargo, cuando Itzjak nació, ella misma nombró la paradoja: "Risa me ha hecho Elohim" (Bereshit 21:6). La espera larga no mata la alegría: la destila.',
      'Avraham compra la cueva de Majpelá — la primera posesión legal de Israel en la tierra prometida. Y es una tumba. El primer pedazo de la promesa fue un lugar para enterrar a los muertos. La fe madura entiende que la herencia incluye también las despedidas.',
      'Eliezer viaja a buscar esposa para Itzjak y pide una señal: que la joven ofrezca agua a él y a sus camellos. Diez camellos, cientos de litros. Rivká no solo cumplió la señal: la desbordó. El carácter se revela en los gestos que nadie obliga.',
      'Los años que esperan no son años perdidos. Sará lo demuestra: la promesa que madura despacio llega con sabor más profundo. Si hoy estás en la sala de espera del Eterno, recuerda: los embarazos de las promesas no se miden en meses, sino en generaciones.',
    ],
    fuente: 'Midrash Bereshit Rabbá 58:1',
  },
  {
    id: 'toldot',
    nombre: 'Toldot',
    hebreo: 'תּוֹלְדֹת',
    lectura: 'Génesis 25:19 – 28:9',
    titulo: 'La primogenitura y el guiso',
    citaHebreo: 'וַיִּבְז עֵשָׂו אֶת־הַבְּכֹרָה',
    citaEspanol: 'Y menospreció Esaú la primogenitura',
    fuenteCita: 'Bereshit 25:34',
    cuerpo: [
      'Dos hijos luchaban en el vientre de Rivká antes de nacer, y el Eterno le explicó: "Dos naciones hay en tu seno" (Bereshit 25:23). La historia se decide antes de los hechos. Los grandes conflictos del hombre comienzan siempre en un vientre: el de las decisiones invisibles.',
      'Esaú llegó del campo, cansado, y vendió la primogenitura por un guiso de lentejas. El texto es quirúrgico: "comió y bebió, se levantó y se fue; y menospreció Esaú la primogenitura" (Bereshit 25:34). No hubo arrepentimiento dramático: solo digestión. Así se pierden las herencias: sin ruido, entre el hambre y la costumbre.',
      'Rashi nota que aquel día Avraham había muerto y las lentejas eran comida de duelo. Esaú volvía del campo, de la caza, de sus guerras; Yaakov estaba en casa, preparando la comida del luto. Uno vivía la vida como aventura; el otro, como memoria. Solo uno de los dos entendía qué significaba la primogenitura.',
      'Itzjak, anciano y de ojos nublados, quiso bendecir al hijo equivocado. Y sin embargo, la bendición llegó a su destino: "las manos son las manos de Esaú, pero la voz es la voz de Yaakov" (Bereshit 27:22). La tradición leyó ahí el destino de Israel: su fuerza no está en las manos armadas, sino en la voz que estudia, ora y bendice.',
      'Cada día se nos ofrece el mismo trueque: la primogenitura invisible por el guiso inmediato. La eternidad por el apetito. Esaú no era un malvado; era un hombre de impulsos. Y los impulsos, cuando gobiernan, venden lo eterno al precio de lo inmediato.',
    ],
    fuente: 'Rashi sobre Bereshit 25:29',
  },
  {
    id: 'vayetze',
    nombre: 'Vayetzé',
    hebreo: 'וַיֵּצֵא',
    lectura: 'Génesis 28:10 – 32:3',
    titulo: 'La piedra que se volvió puerta',
    citaHebreo: 'וַיִּפְגַּע בַּמָּקוֹם וַיָּלֶן שָׁם',
    citaEspanol: 'Y llegó a un lugar y pasó allí la noche',
    fuenteCita: 'Bereshit 28:11',
    cuerpo: [
      'Yaakov huía solo, de noche, con una piedra por almohada. Era el punto más bajo de su vida: había perdido su casa, su hermano lo quería muerto, y el futuro era un desierto. Y justo ahí, el texto dice, "llegó al lugar". El Midrash (Jullín 91b) enseña que ese "lugar" era el monte Moriá, el mismo de la Akedá, el futuro lugar del Templo. El exilio lo llevó, sin saberlo, al centro del mundo.',
      'El sueño de la escalera: ángeles que suben y bajan. Noten el orden — primero suben, luego bajan. Los ángeles de la tierra ascienden, los del cielo descienden. La oración y el estudio suben; la respuesta y la provisión bajan. La escalera está siempre en movimiento: ningún cielo está cerrado para el que sueña sobre una piedra.',
      'Al despertar, Yaakov exclamó: "El Eterno está en este lugar y yo no lo sabía" (Bereshit 28:16). Esa frase resume la mitad de la vida espiritual: el Eterno estaba ahí todo el tiempo; lo que cambió fueron los ojos de Yaakov. La santidad no se traslada; se descubre.',
      'En Harán, Yaakov trabajó veinte años para un suegro tramposo. Le cambiaron el salario diez veces, le dieron la esposa equivocada, le robaron lo posible. Y sin embargo, salió de allí con familia, rebaños y nombre. Hay temporadas que parecen robos y resultan ser escuelas: Laván no lo sabía, pero estaba pagando la matrícula del tercer patriarca.',
      'La piedra que fue almohada se convirtió en pilar, y el pilar en Beit El, la casa de Elohim. Las noches más duras pueden ser la puerta del cielo. Donde tú ves solo una piedra de cabecera, el Eterno ve un Beit El.',
    ],
    fuente: 'Talmud Bavlí, Jullín 91b',
  },
  {
    id: 'vayishlaj',
    nombre: 'Vayishlaj',
    hebreo: 'וַיִּשְׁלַח',
    lectura: 'Génesis 32:4 – 36:43',
    titulo: 'La lucha que da nombre',
    citaHebreo: 'לֹא יַעֲקֹב יֵאָמֵר עוֹד שִׁמְךָ כִּי אִם־יִשְׂרָאֵל',
    citaEspanol: 'No se llamará más tu nombre Yaakov, sino Israel',
    fuenteCita: 'Bereshit 32:29',
    cuerpo: [
      'Yaakov quedó solo a la orilla del Yaboc, la víspera de reencontrarse con Esaú. Veinte años de culpa lo esperaban del otro lado del río. Y entonces, "luchó un hombre con él hasta el alba" (Bereshit 32:25). Las batallas decisivas no se pelean de día ni en público: se pelean de noche y a solas.',
      'El misterioso luchador no pudo vencerlo, y entonces le tocó la articulación del muslo. Yaakov salió cojo del encuentro. Las victorias espirituales verdaderas siempre dejan marca: quien lucha con el Eterno no sale ileso, sale renombrado. Israel: "el que lucha con Dios y prevalece".',
      'La tradición (Bereshit Rabbá 77:2) pregunta por qué el ángel insistía en irse antes del alba: porque los ángeles deben cantar su turno ante el trono cada mañana. Yaakov retuvo al ángel hasta que le dio su bendición: ni el cielo pudo soltarse hasta bendecirlo. Hay oraciones que son combates, y combates que terminan en bendición.',
      'Al día siguiente, Yaakov vio a Esaú venir con cuatrocientos hombres. Había preparado regalos, estrategia, oración. Y Esaú corrió, lo abrazó y lloró. Veinte años de miedo se disolvieron en un abrazo. Cuántas de nuestras guerras existen solo en la imaginación: el enemigo que tememos también ha estado llorando a solas.',
      'Yaakov cruzó el Yaboc siendo Yaakov — "el que sujeta el talón" — y salió siendo Israel. Las batallas más importantes dejan cicatriz y bendición juntas. No salgas de la noche sin obtener el nombre que el Eterno quiere darte.',
    ],
    fuente: 'Midrash Bereshit Rabbá 77:2',
  },
  {
    id: 'vayeshev',
    nombre: 'Vayéshev',
    hebreo: 'וַיֵּשֶׁב',
    lectura: 'Génesis 37:1 – 40:23',
    titulo: 'El sueño que nadie pudo enterrar',
    citaHebreo: 'וַיַּחֲלֹם יוֹסֵף חֲלוֹם',
    citaEspanol: 'Y soñó Yosef un sueño',
    fuenteCita: 'Bereshit 37:5',
    cuerpo: [
      'Yosef tenía diecisiete años y dos sueños: gavillas inclinadas, estrellas postradas. Su error no fue soñar: fue contarlo sin tacto. Los sueños del Eterno son verdaderos, pero anunciarlos a destiempo puede costar una fosa. La sabiduría no solo recibe visiones; administra su calendario.',
      'Sus hermanos lo vendieron por veinte monedas de plata, y la caravana lo llevó a Egipto. En la fosa, el texto dice, "no había agua en ella" (Bereshit 37:24), y el Talmud (Shabat 22a) completa: agua no había, pero serpientes y escorpiones sí. Las fosas de la vida rara vez están vacías: están llenas de aquello que puede mordernos si nos quedamos quietos.',
      'En la casa de Potifar, Yosef prosperó "porque el Eterno estaba con él" (Bereshit 39:2). Luego, en la cárcel, lo mismo: "el Eterno estaba con Yosef" (Bereshit 39:21). El palacio y la prisión comparten el mismo versículo. La presencia del Eterno no depende de la dirección que tenga tu puerta.',
      'El jefe de los coperos fue restaurado y "no se acordó de Yosef, sino que lo olvidó" (Bereshit 40:23). Dos años más de cárcel por el olvido de un hombre. Pero el olvido humano era engranaje del calendario divino: si lo recuerda antes, Yosef sale libre y vuelve a casa; esperando dos años, sale libre y gobierna Egipto.',
      'Hay destinos que los hombres intentan enterrar y la tierra misma los devuelve floreciendo. La fosa no pudo, la casa de Potifar no pudo, la cárcel no pudo. Lo que el Eterno sembró en ti, nadie lo puede cavar fuera.',
    ],
    fuente: 'Talmud Bavlí, Shabat 22a',
  },
  {
    id: 'miketz',
    nombre: 'Miketz',
    hebreo: 'מִקֵּץ',
    lectura: 'Génesis 41:1 – 44:17',
    titulo: 'Del calabozo al trono en un día',
    citaHebreo: 'וַיְהִי מִקֵּץ שְׁנָתַיִם יָמִים וּפַרְעֹה חֹלֵם',
    citaEspanol: 'Y aconteció que al cabo de dos años, Paró soñó',
    fuenteCita: 'Bereshit 41:1',
    cuerpo: [
      '"Al cabo de dos años" — la Torá marca el tiempo exacto del olvido. El copero se había olvidado de Yosef, pero el Eterno no. Los relojes del Cielo no suenan antes ni después: suenan cuando la cosecha de la espera está madura. Egipto entero dormía tranquilo mientras la salvación del mundo conocido esperaba en una celda.',
      'Los sueños de Paró: siete vacas flacas que devoran a las gordas y siguen flacas. Nadie en la corte entendía el mensaje. Yosef, recién afeitado, lo descifró en minutos: los años de cárcel no habían apagado su don; lo habían afilado. La sabiduría nacida en la oscuridad ve mejor en la oscuridad.',
      'Y noten la honestidad de Yosef: "No es en mí; Elohim dará la respuesta de paz a Paró" (Bereshit 41:16). En el momento de su mayor gloria, su primer gesto fue quitar el foco de sí mismo. La grandeza verdadera no necesita atribuirse los milagros que interpreta.',
      'En una sola mañana, Yosef pasó del calabozo al palacio: salió de la fosa a los treinta años, como quien sale de un largo entierro. El Midrash (Bereshit Rabbá 89:1) ve aquí la prueba de que la redención del Eterno llega "en un abrir y cerrar de ojos". Los años de vacas flacas terminan cuando llega el momento de interpretar.',
      'El Eterno no desperdicia ni un solo día de espera. Cada año en la cárcel era una lección del idioma del trono: paciencia, administración, discernimiento de sueños ajenos. Cuando el trono llame, descubrirás que la cárcel era la escuela.',
    ],
    fuente: 'Midrash Bereshit Rabbá 89:1',
  },
  {
    id: 'vayigash',
    nombre: 'Vayigash',
    hebreo: 'וַיִּגַּשׁ',
    lectura: 'Génesis 44:18 – 47:27',
    titulo: 'Las manos que fueron mensajeras',
    citaHebreo: 'וְעַתָּה לֹא־אַתֶּם שְׁלַחְתֶּם אֹתִי הֵנָּה כִּי הָאֱלֹהִים',
    citaEspanol: 'Y ahora, no fueron ustedes quienes me enviaron aquí, sino Elohim',
    fuenteCita: 'Bereshit 45:8',
    cuerpo: [
      'Yehudá se acercó — "vayigash" — y ofreció su propia vida por Benjamín. El mismo Yehudá que años antes propuso vender a Yosef ahora se ofrece como esclavo por su hermano. Ese es el momento en que Yosef ya no puede contenerse: no fue el poder lo que lo quebró, fue ver que sus hermanos habían cambiado.',
      'El perdón de Yosef no niega el daño; lo reubica en un mapa más grande: "Ustedes pensaron mal contra mí, pero Elohim lo pensó para bien" (Bereshit 50:20). Las manos que lo vendieron eran manos humanas con intenciones humanas — y sin embargo, el Eterno las había convertido en mensajeras. El perdón maduro distingue entre la intención del hombre y el propósito de Dios.',
      'El Midrash (Bereshit Rabbá 93:2) nota que Yosef hizo salir a todos los egipcios antes de darse a conocer. La reconciliación familiar no necesita audiencia: necesita intimidad. Hay abrazos que solo pueden darse a puerta cerrada, sin testigos que conviertan el llanto en espectáculo.',
      'Yaakov, anciano, bajó a Egipto creyendo que terminaba sus días fuera de la tierra prometida. Y el Eterno le dijo en visión nocturna: "No temas descender a Egipto, porque allí te haré una gran nación" (Bereshit 46:3). A veces el destino nos lleva exactamente adonde no queríamos ir, porque la promesa necesitaba de ese suelo para germinar.',
      'El perdón no es negar el daño; es descubrir que el daño fue también mensajero. Cuando Yosef miró atrás, ya no vio una fosa: vio un puente.',
    ],
    fuente: 'Midrash Bereshit Rabbá 93:2',
  },
  {
    id: 'vayeji',
    nombre: 'Vayejí',
    hebreo: 'וַיְחִי',
    lectura: 'Génesis 47:28 – 50:26',
    titulo: 'Las manos cruzadas de la bendición',
    citaHebreo: 'וַיִּשְׁלַח יַעֲקֹב אֶת־יָדוֹ הַיְמִינוֹ וַיָּשֶׁת עַל־רֹאשׁ אֶפְרָיִם',
    citaEspanol: 'Y extendió Yaakov su mano derecha y la puso sobre la cabeza de Efraím',
    fuenteCita: 'Bereshit 48:14',
    cuerpo: [
      'Yaakov, muriendo, bendijo a los hijos de Yosef. Pero cruzó las manos: la derecha sobre Efraím, el menor; la izquierda sobre Menashé, el mayor. Yosef intentó corregirlo y su padre respondió: "Lo sé, hijo mío, lo sé" (Bereshit 48:19). El Eterno no firma nuestros órdenes de nacimiento ni nuestras lógicas de mérito.',
      'Cada viernes por la noche, los padres de Israel bendicen a sus hijos con las palabras de esta parashá: "Que Elohim te haga como Efraím y como Menashé" (Bereshit 48:20). Dos niños criados en Egipto, lejos de la tierra y del abuelo, que sin embargo no se asimilaron. Son el modelo de todo hijo de Israel en el exilio: es posible crecer en palacio sin olvidar la carpa.',
      'La bendición de Yaakov sobre Yehudá contiene una de las profecías más antiguas del Mashiaj: "No será quitado el cetro de Yehudá… hasta que venga Shiló" (Bereshit 49:10). La realeza de Israel fue anunciada en un lecho de muerte, entre hermanos reconciliados. Las promesas más grandes nacen en los momentos más frágiles.',
      'Yosef murió pidiendo algo extraño: "Cuando Elohim los visite, lleven mis huesos de aquí" (Bereshit 50:25). No pidió monumentos en Egipto, el país que gobernó: pidió ser enterrado en la tierra que no vio más. La fe se reconoce en el testamento: ¿dónde quieres que descansen tus huesos?',
      'El libro de Bereshit termina con un ataúd en Egipto. Parece un final triste, pero es una promesa en pausa: el pueblo bajará, el pueblo subirá, y los huesos de Yosef harán el viaje. Ningún exilio es el final del libro.',
    ],
    fuente: 'Bereshit 49:10 — profecía de Shiló',
  },
]
