import type { Reflexion } from './reflexionesTypes'

// BEMIDBAR (Números) — parashiot 34 a 43
export const REFLEXIONES_BEMIDBAR: Reflexion[] = [
  {
    id: 'bemidbar',
    nombre: 'Bemidbar',
    hebreo: 'בְּמִדְבַּר',
    lectura: 'Números 1:1 – 4:20',
    titulo: 'En el censo del Eterno nadie es un número',
    citaHebreo: 'שְׂאוּ אֶת־רֹאשׁ כׇּל־עֲדַת בְּנֵי־יִשְׂרָאֵל לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם בְּמִסְפַּר שֵׁמוֹת',
    citaEspanol: 'Levantad el censo de toda la congregación de los hijos de Israel… por número de nombres',
    fuenteCita: 'Bemidbar 1:2',
    cuerpo: [
      'El cuarto libro de la Torá comienza con un censo, y el verso guarda un detalle hermoso: el conteo se hace "por número de nombres". En el censo del Eterno nadie es una cifra: todos son un nombre. Las multitudes de Dios están hechas de personas, no de masas.',
      'Rashi nota que el Eterno cuenta a Su pueblo con frecuencia — al salir de Egipto, después del becerro, al levantar el Mishkán — "por Su amor hacia ellos". Como el pastor que cuenta sus ovejas no por burocracia sino por cariño, el Eterno cuenta porque cada uno le importa. Ser contado por Dios es ser amado por Dios.',
      'El campamento tenía un orden exacto: tres tribus a cada lado, y el Mishkán en el centro. La presencia en el medio, la vida ordenada alrededor. El Midrash (Bemidbar Rabbá 2:3) ve en este diseño el retrato de una vida bien ordenada: no importa cuántas tribus, cargas y banderas tengas — la pregunta es qué ocupa el centro de tu campamento.',
      'Los levitas no fueron contados entre las tribus: su herencia era el servicio, no el territorio. "Yo soy tu porción y tu heredad" (Bemidbar 18:20), le dice el Eterno a Aarón. Hay llamados donde la recompensa no es un pedazo de tierra, sino la cercanía misma. Quien sirve al altar recibe una herencia que no se puede medir en hectáreas.',
      'Que tu vida también acampe así: cada tribu en su lugar, cada carga en su orden, y la presencia en el centro. Cuando el Mishkán está en el medio, hasta el desierto se convierte en campamento organizado.',
    ],
    fuente: 'Rashi sobre Bemidbar 1:1; Midrash Bemidbar Rabbá 2:3',
  },
  {
    id: 'naso',
    nombre: 'Nasó',
    hebreo: 'נָשֹׂא',
    lectura: 'Números 4:21 – 7:89',
    titulo: 'El rostro inclinado hacia ti',
    citaHebreo: 'יְבָרֶכְךָ יְהוָה וְיִשְׁמְרֶךָ יָאֵר יְהוָה פָּנָיו אֵלֶיךָ וִיחֻנֶּךָּ',
    citaEspanol: 'El Eterno te bendiga y te guarde; el Eterno haga resplandecer Su rostro sobre ti y te tenga misericordia',
    fuenteCita: 'Bemidbar 6:24-25',
    cuerpo: [
      'En medio de censos y leyes de pureza, la Torá coloca la joya más preciada de la bendición bíblica: el Birkat Cohanim, la bendición sacerdotal. Quince palabras en hebreo que llevan más de tres mil años pronunciándose sobre el pueblo, cada Shabat, cada fiesta, cada padre sobre sus hijos los viernes por la noche. Son las palabras más antiguas que siguen vivas en labios de Israel.',
      'La estructura es una escalera: tres versos de tres, cinco y siete palabras. "Te bendiga y te guarde" — la provisión material. "Haga resplandecer Su rostro sobre ti" — la iluminación espiritual. "Alce Su rostro hacia ti y te dé paz" — la intimidad completa. La bendición sube de lo físico a lo espiritual, terminando en el regalo mayor: el shalom.',
      'El Talmud (Sotá 38a) enseña que los cohanim deben bendecir "con amor": un sacerdote que no ama al pueblo no puede bendecirlo. La bendición no es una fórmula mágica; es un acto de amor con palabras sagradas. Por eso el Eterno añade: "Pondrán Mi nombre sobre los hijos de Israel, y Yo los bendeciré" (Bemidbar 6:27). Los sacerdotes pronuncian; el Eterno bendice.',
      'En Jerusalén se encontraron en 1979 dos amuletos de plata del siglo VII a.e.c. — los textos bíblicos más antiguos jamás hallados, cuatrocientos años más viejos que los rollos del Mar Muerto — y contienen esta bendición. Antes del exilio babilónico, alguien llevaba estas palabras enrolladas al cuello. La bendición sacerdotal ha sobrevivido templos, exilios e imperios.',
      'Que nunca perdamos la costumbre de bendecir. Bendecir no es desear suerte: es poner el Nombre del Eterno sobre alguien y dejar que Él cumpla. Cada vez que pronuncias estas palabras sobre otro, te unes a una cadena de bendición que no se ha roto en tres mil años.',
    ],
    fuente: 'Talmud Bavlí, Sotá 38a; Bemidbar 6:27',
  },
  {
    id: 'behaalotja',
    nombre: 'Behaalotjá',
    hebreo: 'בְּהַעֲלֹתְךָ',
    lectura: 'Números 8:1 – 12:16',
    titulo: 'Lámparas que encienden lámparas',
    citaHebreo: 'בְּהַעֲלֹתְךָ אֶת־הַנֵּרֹת אֶל־מוּל פְּנֵי הַמְּנוֹרָה יָאִירוּ שִׁבְעַת הַנֵּרוֹת',
    citaEspanol: 'Cuando enciendas las lámparas, las siete lámparas alumbrarán hacia el frente de la menorá',
    fuenteCita: 'Bemidbar 8:2',
    cuerpo: [
      'Aarón debía "elevar" las lámparas de la menorá — la Torá no dice "encender" sino "hacer subir". Rashi explica que la llama debía levantarse hasta que ardiera por sí sola. Enseñar es exactamente eso: encender a otros hasta que ardan solos. El buen maestro no retiene la llama; la deja volar.',
      'La parashá incluye una institución sorprendente: el Pésaj Shení, la segunda Pascua. Unos hombres impuros por contacto con un muerto reclamaron: "¿Por qué hemos de quedar excluidos de ofrecer la ofrenda del Eterno?" (Bemidbar 9:7). Y el Eterno les dio una segunda fecha, un mes después. La Torá misma admite segundas oportunidades: quien llegó tarde por razones de la vida, tiene otra cita.',
      'La nube sobre el Mishkán dictaba los viajes del pueblo: "Al mandato del Eterno acampaban y al mandato del Eterno viajaban" (Bemidbar 9:23). A veces la nube se detenía un día; a veces, un año. El pueblo no sabía si levantaba campamento mañana o el año próximo. Aprender a vivir sin calendario propio fue la primera universidad de Israel: la fe no es conocer el itinerario, es mirar la nube.',
      'Moshé, agobiado, recibe setenta ancianos sobre quienes descansa el espíritu. Y cuando dos hombres profetizan en el campamento fuera de programa, Iehoshúa quiere detenerlos, y Moshé responde: "¿Tienes celos por mí? ¡Ojalá todo el pueblo del Eterno fuera profeta!" (Bemidbar 11:29). El líder verdadero no monopoliza el espíritu: se alegra cuando se derrama sin permiso.',
      'Así enseñamos en el Beit Midrash: lámparas que encienden lámparas. La gloria del maestro no es ser la única llama encendida, sino dejar un candelabro completo ardiendo.',
    ],
    fuente: 'Rashi sobre Bemidbar 8:2; Bemidbar 11:29',
  },
  {
    id: 'shelaj',
    nombre: 'Shelaj',
    hebreo: 'שְׁלַח־לְךָ',
    lectura: 'Números 13:1 – 15:41',
    titulo: 'Los gigantes y las uvas',
    citaHebreo: 'וַנְּהִי בְעֵינֵינוּ כַּחֲגָבִים וְכֵן הָיִינוּ בְּעֵינֵיהֶם',
    citaEspanol: 'Y éramos a nuestros propios ojos como langostas, y así éramos a sus ojos',
    fuenteCita: 'Bemidbar 13:33',
    cuerpo: [
      'Doce espías vieron la misma tierra: las mismas uvas, los mismos gigantes, las mismas murallas. Diez volvieron con un informe de miedo; dos, con un informe de fe. La diferencia no estuvo en los ojos, sino en el corazón que interpretaba lo que los ojos veían. La realidad es una; el informe, una decisión.',
      'La frase más reveladora del informe negativo es esta: "Éramos a nuestros propios ojos como langostas, y así éramos a sus ojos". Noten el orden: primero se vieron pequeños ellos mismos, y solo después supusieron que los otros los veían igual. El desprecio propio siempre se proyecta: quien se mira como langosta, imagina que el mundo lo ve como langosta.',
      'Caleb había callado al pueblo con otra matemática: "Subamos luego y tomémosla, porque podremos más que ellos" (Bemidbar 13:30). Y Iehoshúa añadió la teología del asunto: "Si el Eterno se agrada de nosotros, nos llevará a esta tierra" (Bemidbar 14:8). Los gigantes no cambiaron de tamaño, pero la fe cambió de escala.',
      'La consecuencia fue una generación entera dando vueltas en el desierto: "Conforme al número de los días en que explorasteis la tierra, cuarenta días, un año por cada día" (Bemidbar 14:34). El miedo no fue gratis: costó cuarenta años. Cuidado con los informes de la mayoría: a veces la multitud solo cuenta su propio miedo con buena retórica.',
      'Y la Torá cierra la parashá con los tzitzit, los flecos azules en las orillas del vestido: "para que se acuerden de todos los mandamientos del Eterno" (Bemidbar 15:39). El remedio contra los ojos que engañan es un recordatorio visible en la ropa. Los ojos mirarán siempre gigantes o uvas, según el corazón; los flecos están ahí para recordarle al corazón quién manda.',
    ],
    fuente: 'Bemidbar 13:33; 14:8',
  },
  {
    id: 'koraj',
    nombre: 'Kóraj',
    hebreo: 'קֹרַח',
    lectura: 'Números 16:1 – 18:32',
    titulo: 'La rebeldía vestida de democracia',
    citaHebreo: 'רַב־לָכֶם כִּי כׇל־הָעֵדָה כֻּלָּם קְדֹשִׁים וּבְתוֹכָם יְהוָה',
    citaEspanol: '¡Basta ya! Toda la congregación, todos ellos son santos, y el Eterno está entre ellos',
    fuenteCita: 'Bemidbar 16:3',
    cuerpo: [
      'Kóraj no discutió con argumentos teológicos: usó el lenguaje de la igualdad. "Toda la congregación es santa, ¿por qué os eleváis sobre la asamblea del Eterno?" Suena justo, suena democrático, suena espiritual. Pero el Mishná (Avot 5:17) distingue: "Toda controversia que es por el Cielo, perdurará; y la que no es por el Cielo, no perdurará. ¿Cuál es la que es por el Cielo? La de Hilel y Shammai. ¿Y la que no es por el Cielo? La de Kóraj y toda su asamblea."',
      'El problema de Kóraj no era su pregunta, sino su intención: no buscaba la santidad de la congregación; buscaba el puesto de Aarón. La rebeldía espiritual casi nunca dice su verdadero motivo. Se viste de justicia, de inclusión, de "todos somos iguales" — mientras por dentro arde la envidia del liderazgo ajeno.',
      'Moshé respondió con una prueba: que el Eterno mismo eligiera. Y la tierra abrió su boca y se tragó a los rebeldes (Bemidbar 16:32). La imagen es aterradora y justa: quien sembró división en el pueblo fue tragado por la misma tierra que pisaba. La división no construye: devora.',
      'Pero la Torá no termina ahí: al día siguiente, la vara de Aarón floreció y dio almendras (Bemidbar 17:23). El Eterno no solo castigó la usurpación: confirmó con vida el llamado. La vara seca que florece es la respuesta divina a toda disputa de legitimidad: lo que Él elige, florece; lo que el hombre usurpa, se seca.',
      'No toda crítica a la autoridad es profecía. Hay controversias por el Cielo — debates honestos que buscan la verdad, como las de Hilel y Shammai, cuyas palabras aún estudiamos — y hay controversias por el trono. La primera enriquece; la segunda, traga. Aprendamos a distinguirlas, sobre todo en nosotros mismos.',
    ],
    fuente: 'Mishná, Avot 5:17',
  },
  {
    id: 'jukat',
    nombre: 'Jukat',
    hebreo: 'חֻקַּת',
    lectura: 'Números 19:1 – 22:1',
    titulo: 'Los misterios que se obedecen',
    citaHebreo: 'זֹאת חֻקַּת הַתּוֹרָה',
    citaEspanol: 'Este es el estatuto de la Torá',
    fuenteCita: 'Bemidbar 19:2',
    cuerpo: [
      'La parashá abre con el precepto más misterioso de la Torá: la vaca roja. Sus cenizas purificaban al impuro, pero impurificaban al puro que las preparaba. Ni Salomón, el más sabio de los hombres, pretendió entenderla: "Dije: adquiriré sabiduría, pero ella se alejó de mí" (Kohelet 7:23), y la tradición lo aplica a este pasaje. Hay misterios de la Torá que no se explican: se obedecen.',
      'El Midrash (Bemidbar Rabbá 19:3) cuenta que un pagano preguntó al rabí Iojanán ben Zakkai por esta ley, llamándola hechicería. El rabí le respondió con paciencia, y luego explicó a sus alumnos: "La muerte no impurifica ni el agua purifica por sí mismas; es el decreto del Santo. Él dijo: estatuto he puesto, decreto he decretado, y no tienes permiso de transgredir Mi decreto." La obediencia no necesita permiso de la lógica.',
      'Y luego, la escena quebradora: las aguas de Merivá. El pueblo reclamó por sed, y Moshé golpeó la roca dos veces en lugar de hablarle. El agua brotó — el milagro funcionó — pero el precio fue devastador: "Por cuanto no creísteis en Mí… no entraréis esta congregación a la tierra" (Bemidbar 20:12). Cuarenta años de liderazgo perfecto no compraron una sola falla pública. La santidad del líder se mide con vara más alta.',
      'El Midrash nota la tragedia de la frase de Moshé: "¡Oíd, rebeldes!" (Bemidbar 20:10). No fue el golpe a la roca lo peor: fue la ira. El líder que pierde la paciencia con el pueblo pierde algo más que el caso: pierde la ternura que lo hacía portavoz. Uno puede acertar el milagro y fallar el corazón.',
      'No toda la sabiduría cabe en nuestra lógica, y eso también es un alivio: el Eterno no nos pidió entenderlo todo; nos pidió confiar. Y a los que guían: el agua puede brotar igual aunque tu corazón esté seco, pero el Eterno mira la roca y también las manos que la golpean.',
    ],
    fuente: 'Midrash Bemidbar Rabbá 19:3',
  },
  {
    id: 'balak',
    nombre: 'Balak',
    hebreo: 'בָּלָק',
    lectura: 'Números 22:2 – 25:9',
    titulo: 'El que vino a maldecir y salió bendiciendo',
    citaHebreo: 'מַה־טֹּבוּ אֹהָלֶיךָ יַעֲקֹב מִשְׁכְּנֹתֶיךָ יִשְׂרָאֵל',
    citaEspanol: '¡Cuán hermosas son tus tiendas, Yaakov; tus moradas, Israel!',
    fuenteCita: 'Bemidbar 24:5',
    cuerpo: [
      'Balak, rey de Moav, contrató al profeta más famoso de Oriente para maldecir a Israel. Bilam venía con el mejor precio, la mejor intención de daño, el mejor escenario: una colina desde donde divisaba el campamento. Y tres veces abrió la boca para maldecir, y tres veces salieron bendiciones. El Eterno convierte las maldiciones en bendiciones cuando ama a Su pueblo.',
      'La escena tiene un detalle delicioso: Bilam, el gran profeta, no ve al ángel en el camino, y su burra sí. El Talmud dice que el Eterno "abrió la boca de la burra" (Bemidbar 22:28). El animal veía lo que el vidente no veía. La soberbia espiritual es la peor miopía: uno puede tener dones, fama y hasta revelación, y estar más ciego que su montura.',
      'Y desde la colina, mirando las tiendas de Israel, al falso profeta se le escapó uno de los versículos más hermosos de la Torá: "¡Cuán hermosas son tus tiendas, Yaakov; tus moradas, Israel!" — las palabras con las que hasta hoy se abre la oración de la mañana en las sinagogas del mundo. El elogio más verdadero sobre Israel lo pronunció un enemigo. A veces los que vinieron a destruirnos terminan escribiendo nuestra liturgia.',
      'El Midrash (Bemidbar Rabbá 20:19) pregunta qué vio Bilam en las tiendas: que sus puertas no se miraban unas a otras. La privacidad, la decencia, el respeto por la intimidad del vecino: eso era la belleza de Israel. La santidad de un pueblo se reconoce desde afuera, en cómo ordena sus puertas.',
      'Ninguna maldición pronunciada contra el pueblo de la alianza llega a destino: "El Eterno tu Elohim no quiso escuchar a Bilam, y te convirtió la maldición en bendición, porque el Eterno tu Elohim te amaba" (Devarim 23:6). Esa es nuestra biografía en una línea: nos mandaron maldiciones y coleccionamos bendiciones.',
    ],
    fuente: 'Devarim 23:6; Midrash Bemidbar Rabbá 20:19',
  },
  {
    id: 'pinjas',
    nombre: 'Pinjás',
    hebreo: 'פִּינְחָס',
    lectura: 'Números 25:10 – 30:1',
    titulo: 'El celo y las hijas que reclamaron',
    citaHebreo: 'כֵּן בְּנוֹת צְלׇפְחָד דֹּבְרֹת נָתֹן תִּתֵּן לָהֶם אֲחֻזַּת נַחֲלָה',
    citaEspanol: 'Bien dicen las hijas de Tzelofjad; les darás posesión de heredad',
    fuenteCita: 'Bemidbar 27:7',
    cuerpo: [
      'Pinjás actuó con celo en un momento de crisis, y el Eterno le dio "Mi pacto de paz" (Bemidbar 25:12). La paradoja es difícil y la tradición la discute hace siglos: el celo violento recibe como recompensa un pacto de paz. Quizás la lección es que hay momentos donde la tibieza es el verdadero enemigo — y que el Eterno, conociendo el corazón de Pinjás, le regaló la paz que su acto no tenía, para que nunca más necesitara la lanza.',
      'Y en el mismo capítulo de la herencia aparece una de las escenas más luminosas de la Torá: las cinco hijas de Tzelofjad — Majlá, Noa, Joglá, Milcá y Tirtzá — se presentaron ante Moshé y reclamaron: "¿Por qué ha de ser quitado el nombre de nuestro padre por no tener hijo varón? Danos posesión entre los hermanos de nuestro padre" (Bemidbar 27:4). Cinco mujeres sin estatus legal reclamando justicia ante todo el liderazgo.',
      'Moshé llevó el caso al Eterno, y la respuesta fue rotunda: "Bien dicen las hijas de Tzelofjad". El texto hebreo pone el "kén — sí, correcto" al inicio: el Eterno abrió Su respuesta validándolas. Y la ley cambió ese día. La Torá también se corrige cuando la justicia llama — y la justicia a veces llama con voz de cinco hermanas valientes.',
      'El Talmud (Bavá Batrá 119b) las elogia: eran sabias, porque hablaron en el momento oportuno; eran rectas, porque hablaron solo por la herencia de su padre. La valentía bien educada cambia la legislación del Cielo. No se trata de gritar: se trata de presentarse con la razón en la mano y la dignidad en la voz.',
      'Y Pinjás cierra con el relevo: Moshé impone las manos sobre Iehoshúa ante todo el pueblo. El líder más grande acepta su sucesión sin drama. Las varas florecen, los celos se aplacan, las hijas heredan y los líderes pasan el bastón. Así madura un pueblo.',
    ],
    fuente: 'Bemidbar 27:7; Talmud Bavlí, Bavá Batrá 119b',
  },
  {
    id: 'matot',
    nombre: 'Matot',
    hebreo: 'מַּטּוֹת',
    lectura: 'Números 30:2 – 32:42',
    titulo: 'El altar invisible de la palabra dada',
    citaHebreo: 'אִישׁ כִּי־יִדֹּר נֶדֶר לַיהוָה… לֹא יַחֵל דְּבָרוֹ כְּכׇל־הַיֹּצֵא מִפִּיו יַעֲשֶׂה',
    citaEspanol: 'El hombre que haga voto al Eterno… no quebrantará su palabra; conforme a todo lo que salga de su boca hará',
    fuenteCita: 'Bemidbar 30:3',
    cuerpo: [
      'La Torá de los votos abre con un principio lapidario: "No quebrantará su palabra; conforme a todo lo que salga de su boca hará". La palabra dada es un altar invisible. En un mundo de promesas líquidas, de "te escribo luego", de "ya veremos", el pueblo de Israel se distingue por el peso de su sí.',
      'El profeta Iermeíahu resumiría el ideal: "El que jura: como vive el Eterno, en verdad, en justicia y en rectitud" (Iermeíahu 4:2). Y el Salmo pregunta quién puede subir al monte del Eterno, y responde: "El que jura en su daño y no se retracta" (Tehilim 15:4). Cumplir la palabra incluso cuando duele: esa es la firma del carácter santo.',
      'Las tribus de Reuvén y Gad pidieron quedarse al este del Jordán, donde había buen pasto. Moshé se indignó: "¿Irán vuestros hermanos a la guerra, y vosotros os quedaréis aquí?" (Bemidbar 32:6). La comodidad no puede comprar la deserción. Ninguna comunidad avanza si cada uno elige su pradera mientras los demás pelean.',
      'Pero la negociación que siguió es un modelo: Reuvén y Gad prometieron ir al frente "como vanguardia" hasta que cada tribu tuviera su heredad, y solo entonces volverían a sus tierras (Bemidbar 32:17-18). Y Moshé aceptó. La Torá no exige uniformidad: exige lealtad. Puedes vivir al otro lado del río, siempre que cuando suene la llamada cruces primero.',
      'Y así se hizo: los hombres de Reuvén y Gad cruzaron armados delante de sus hermanos (Iehoshúa 4:12). La palabra dada en Matot se cumplió en Iehoshúa. Que nuestro sí sea sí, y nuestro no, no — como enseñó el Mashiaj. La credibilidad es la moneda más cara del Reino: no la gastes en promesas livianas.',
    ],
    fuente: 'Tehilim 15:4; Iehoshúa 4:12',
  },
  {
    id: 'masei',
    nombre: 'Maséi',
    hebreo: 'מַסְעֵי',
    lectura: 'Números 33:1 – 36:13',
    titulo: 'El itinerario que el Eterno guarda',
    citaHebreo: 'אֵלֶּה מַסְעֵי בְנֵי־יִשְׂרָאֵל אֲשֶׁר־יָצְאוּ מֵאֶרֶץ מִצְרַיִם',
    citaEspanol: 'Estas son las jornadas de los hijos de Israel que salieron de la tierra de Egipto',
    fuenteCita: 'Bemidbar 33:1',
    cuerpo: [
      'Cuarenta y dos estaciones del desierto, listadas una por una, con sus nombres impronunciables: Ramsés, Sucot, Etam, Mara, Elim… La Torá dedica un capítulo entero a un itinerario. ¿Para qué? Rashi cita la parábola del Midrash: un rey cuyo hijo estuvo enfermo lo llevó lejos a curarse; al regreso, el padre le recordaba cada parada: "Aquí dormiste, aquí te dolió la cabeza, aquí te aliviaste". El Eterno repasa el viaje porque cada estación significó algo.',
      'Ninguna etapa fue inútil, ni las de avance ni las de retroceso. Mara, la de las aguas amargas, está en la lista igual que Elim, la de las doce fuentes y setenta palmeras. El desierto no fue un castigo de cuarenta años: fue una educación de cuarenta y dos estaciones, cada una con su lección.',
      'Y noten quién escribe el itinerario: "Moshé escribió sus salidas según sus jornadas, por mandato del Eterno" (Bemidbar 33:2). El líder registró cada parada por orden divina. El Eterno guarda el itinerario completo de nuestras peregrinaciones — y manda escribirlo. Tu vida también está siendo escrita, estación por estación.',
      'La parashá también traza las fronteras de la tierra y las ciudades de refugio: seis ciudades donde el que matara sin intención podía huir del vengador (Bemidbar 35:11-12). La Torá distingue el homicidio del accidente: la justicia bíblica mira la intención del corazón, no solo el resultado del hecho. Y hasta la venganza tiene carreteras reguladas y ciudades donde se detiene.',
      'Algún día leeremos nuestra propia lista y entenderemos cada parada: aquí dormiste, aquí te dolió, aquí te sanaste. Nada del camino fue desperdicio. El último capítulo de Bemidbar nos deja a las orillas del Jordán, con la tierra a la vista: el itinerario termina donde comienza la promesa.',
    ],
    fuente: 'Rashi sobre Bemidbar 33:1 (Midrash Tanjumá)',
  },
]

// DEVARIM (Deuteronomio) — parashiot 44 a 54
export const REFLEXIONES_DEVARIM: Reflexion[] = [
  {
    id: 'devarim',
    nombre: 'Devarim',
    hebreo: 'דְּבָרִים',
    lectura: 'Deuteronomio 1:1 – 3:22',
    titulo: 'La memoria es la puerta de la esperanza',
    citaHebreo: 'אֵלֶּה הַדְּבָרִים אֲשֶׁר דִּבֶּר מֹשֶׁה אֶל־כׇּל־יִשְׂרָאֵל',
    citaEspanol: 'Estas son las palabras que habló Moshé a todo Israel',
    fuenteCita: 'Devarim 1:1',
    cuerpo: [
      'El último libro de la Torá es un testamento: Moshé, a las puertas de la tierra prometida, repasa cuarenta años de desierto ante la nueva generación. Antes de entrar, hay que recordar. La memoria es la puerta de la esperanza: quien olvida el desierto no entiende la tierra.',
      'Moshé cuenta la distancia del viaje con ironía amarga: "Once días desde Horeb… hasta Kadesh Barnea" (Devarim 1:2). Once días. El trayecto que debía durar once días duró cuarenta años. La diferencia entre el calendario de Dios y el nuestro no es la distancia: es la obediencia. Cuántos viajes de once días hemos convertido en cuarenta años por nuestra incredulidad.',
      'El Midrash (Devarim Rabbá 1:8) nota que Moshé reprende al pueblo solo con insinuaciones — menciona lugares, no pecados. "Por los nombres de los lugares los amonestaba". La corrección digna no humilla: alude. El buen maestro no necesita abrir la herida para que el alumno recuerde; le basta nombrar el lugar.',
      'Y en medio del repaso, Moshé transmite a Iehoshúa la consigna que resonará en todo el libro siguiente: "No les temáis, porque el Eterno vuestro Elohim, Él peleará por vosotros" (Devarim 3:22). Las batallas de Israel nunca fueron de infantería: fueron de confianza. El que pelea por nosotros no ha cambiado de nombre.',
      'Esta parashá se lee siempre antes del 9 de Av, el día del luto por el Templo. El calendario lo sabe: antes de llorar la destrucción, hay que repasar el camino que nos trajo hasta aquí. La memoria honesta duele, pero es el único mapa confiable hacia el consuelo.',
    ],
    fuente: 'Midrash Devarim Rabbá 1:8',
  },
  {
    id: 'vaetjanan',
    nombre: 'Vaetjanán',
    hebreo: 'וָאֶתְחַנַּן',
    lectura: 'Deuteronomio 3:23 – 7:11',
    titulo: 'Escuchar antes que creer',
    citaHebreo: 'שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד',
    citaEspanol: 'Escucha, Israel: el Eterno nuestro Elohim, el Eterno uno es',
    fuenteCita: 'Devarim 6:4',
    cuerpo: [
      'Moshé suplicó: "Vaetjanán — y yo rogué". La tradición cuenta quinientas quince súplicas para entrar a la tierra, y la respuesta fue no. "Bástate; no me hables más de este asunto" (Devarim 3:26). Ni el más grande de los profetas obtiene todo lo que pide. Y aun así siguió orando. La oración no se mide por las respuestas afirmativas, sino por la persistencia del corazón que golpea.',
      'Pero el Eterno le concedió un consuelo: "Sube a la cumbre del Pisga y alza tus ojos" (Devarim 3:27). Moshé no pisaría la tierra, pero la vería. Hay promesas que se cumplen ante nuestros ojos aunque no bajo nuestros pies. Ver la promesa también es una forma de heredarla.',
      'Y entonces, el corazón de toda la fe de Israel: el Shemá. "Escucha, Israel: el Eterno nuestro Elohim, el Eterno uno es". Noten el primer mandamiento: no es "cree", es "escucha". La fe entra por el oído. Antes de declarar, hay que escuchar; antes de hablar de Dios, hay que oír a Dios.',
      'El Shemá ordena llevar estas palabras "sobre tu corazón", enseñarlas a los hijos, hablarlas al acostarte y al levantarte, atarlas en la mano y la frente, escribirlas en los dinteles (Devarim 6:6-9). La fe de Israel no es un sentimiento dominical: es una arquitectura diaria de recordatorios. Lo que se repite en la puerta, en la mano y en la mesa termina viviendo en el corazón.',
      'Esta parashá se lee en el Shabat del consuelo, después del 9 de Av. El pueblo que lloró la destrucción escucha ahora: "Escucha, Israel". El consuelo no llega primero con respuestas, sino con la voz que llama por nombre. Después de toda ruina, la primera medicina es volver a escuchar.',
    ],
    fuente: 'Devarim 6:4-9',
  },
  {
    id: 'eikev',
    nombre: 'Eikev',
    hebreo: 'עֵקֶב',
    lectura: 'Deuteronomio 7:12 – 11:25',
    titulo: 'El talón que toca el cielo',
    citaHebreo: 'וְהָיָה עֵקֶב תִּשְׁמְעוּן אֵת הַמִּשְׁפָּטִים הָאֵלֶּה',
    citaEspanol: 'Y será que porque escuchéis estos decretos…',
    fuenteCita: 'Devarim 7:12',
    cuerpo: [
      'La parashá abre con una palabra extraña: "eikev — porque", pero que en su raíz significa también "talón". El Midrash (Tanjumá Eikev 1) la lee así: los mandamientos que el hombre pisa con el talón, los que considera ligeros, esos mismo sostienen el mundo. "Y será que si guardáis los mandamientos ligeros, que el hombre suele pisar con el talón…". No hay mitzvá pequeña; hay corazones que aún no han aprendido a ver su luz.',
      'Moshé recuerda al pueblo la pedagogía del desierto: "Te humilló y te hizo tener hambre, y te alimentó del maná… para hacerte saber que no solo de pan vive el hombre, sino de todo lo que sale de la boca del Eterno" (Devarim 8:3). El hambre fue profesora: el maná no era comida, era currículo. Cuarenta años de desayuno milagroso para aprender una línea: la vida no se sostiene de provisiones, sino de Palabra.',
      'Y la advertencia más peligrosa de la Torá no es la pobreza, sino la abundancia: "Cuando comas y te sacies, y edifiques buenas casas y las habites… cuidado que no se eleve tu corazón y te olvides del Eterno" (Devarim 8:12-14). El desierto tiene sus tentaciones, pero el palacio tiene las suyas, más sutiles: el olvido. Nadie se vuelve ateo de hambre; muchos se vuelven ingratos de saciedad.',
      '"No por tu justicia ni por la rectitud de tu corazón entras a poseer la tierra" (Devarim 9:5). Moshé le quita al pueblo cualquier pedestal antes de entrar: la tierra es regalo, no salario. La gracia no es una idea nueva: es la estructura misma de la alianza desde el principio.',
      'La grandeza se construye con fidelidades diminutas. Los mandamientos de "talón" — el saludo, la mesa, la moneda devuelta, la palabra cumplida — son los escalones discretos por los que un alma sube sin hacer ruido. El talón que pisa con fidelidad termina tocando el cielo.',
    ],
    fuente: 'Midrash Tanjumá, Eikev 1; Devarim 8:3',
  },
  {
    id: 'ree',
    nombre: 'Reé',
    hebreo: 'רְאֵה',
    lectura: 'Deuteronomio 11:26 – 16:17',
    titulo: 'Dos montes y una elección diaria',
    citaHebreo: 'רְאֵה אָנֹכִי נֹתֵן לִפְנֵיכֶם הַיּוֹם בְּרָכָה וּקְלָלָה',
    citaEspanol: 'Mira, yo pongo hoy delante de vosotros la bendición y la maldición',
    fuenteCita: 'Devarim 11:26',
    cuerpo: [
      '"Mira": la parashá comienza con un imperativo visual. La fe de Israel no es ciega; se le ordena mirar. Y lo que se pone delante es una elección: bendición y maldición, vida y muerte. La Torá no nos deja espectadores. Cada día es un monte Gerizim y un monte Eval, y elegimos con los pies.',
      'Las dos montañas de la ceremonia tenían una lección geográfica: el Gerizim, verde y frondoso, daba la bendición; el Eval, pelado y árido, daba la maldición. La misma tierra, las mismas lluvias, distinta respuesta. La bendición no depende del paisaje sino de la dirección del corazón.',
      'La parashá ordena centralizar el culto "en el lugar que el Eterno escogiere para hacer habitar Su nombre" (Devarim 12:11). No en cada colina, no al gusto de cada uno. La adoración bíblica no es personalización infinita: es convergencia. Israel se distingue de los pueblos porque su culto tiene dirección, centro y nombre.',
      'Y luego, la economía del séptimo año y la mano abierta: "No endurecerás tu corazón ni cerrarás tu mano a tu hermano pobre, sino que le abrirás tu mano liberalmente" (Devarim 15:7-8). El texto es quirúrgico: primero menciona el corazón, después la mano. La mezquindad no empieza en el bolsillo: empieza en la calcificación del corazón. Abrir la mano es la cirugía externa de un corazón que ya se abrió.',
      'La libertad es el regalo más pesado que el Eterno nos dio, pero sin ella no hay amor verdadero. Un amor obligado no es amor; una obediencia sin alternativa no es obediencia. Por eso cada mañana el cartel sigue colgado delante de nosotros: bendición y maldición, elige.',
    ],
    fuente: 'Devarim 15:7-8',
  },
  {
    id: 'shoftim',
    nombre: 'Shoftim',
    hebreo: 'שֹׁפְטִים',
    lectura: 'Deuteronomio 16:18 – 21:9',
    titulo: 'Justicia, justicia',
    citaHebreo: 'צֶדֶק צֶדֶק תִּרְדֹּף',
    citaEspanol: 'Justicia, justicia perseguirás',
    fuenteCita: 'Devarim 16:20',
    cuerpo: [
      '"Justicia, justicia perseguirás": la repetición no es adorno. Los sabios la leen doble: justicia en los fines y justicia en los medios. No vale lograr un resultado justo por caminos torcidos. La Torá no conoce el "el fin justifica los medios": conoce el "los medios también son juzgados".',
      'Los jueces son advertidos: "No aceptarás regalo, porque el regalo ciega los ojos del sabio y pervierte las palabras del justo" (Devarim 16:19). Noten la precisión: no dice que el regalo corrompe al malvado, sino que ciega al sabio. La corrupción no empieza en el ladrón; empieza en el regalo pequeño aceptado por el bueno. Nadie se vende de golpe: se va cegando de a poco.',
      'La parashá limita también al rey: no multiplicará caballos, ni mujeres, ni oro, y escribirá su propia copia de la Torá para leerla todos los días de su vida (Devarim 17:16-19). En Israel, hasta el rey es estudiante. El poder no está por encima del texto: está sentado ante él, con un rollo abierto, cada día.',
      'Y aparece la promesa que la comunidad mesiánica guarda como joya: "Profeta de en medio de ti, de tus hermanos, como yo, te levantará el Eterno tu Elohim; a Él oiréis" (Devarim 18:15). La sucesión no se detiene en Moshé: la profecía tiene continuidad prometida. Israel espera la voz definitiva del profeta prometido, y lo espera con la Torah en la mano y el oído atento.',
      'La justicia bíblica no es una balanza fría: es una persecución. "Perseguirás" — verbo de movimiento, de empeño, de costo. La justicia no llega a los que esperan sentados; alcanza a los que la persiguen.',
    ],
    fuente: 'Devarim 17:18-19; 18:15',
  },
  {
    id: 'ki-tetze',
    nombre: 'Ki Tetzé',
    hebreo: 'כִּי־תֵצֵא',
    lectura: 'Deuteronomio 21:10 – 25:19',
    titulo: 'El Eterno en los detalles de la vida común',
    citaHebreo: 'לֹא־תִרְאֶה אֶת־שׁוֹר אָחִיךָ אוֹ אֶת־שֵׂיוֹ נִדָּחִים וְהִתְעַלַּמְתָּ מֵהֶם',
    citaEspanol: 'No verás el buey de tu hermano o su cordero extraviados y te esconderás de ellos',
    fuenteCita: 'Devarim 22:1',
    cuerpo: [
      'Setenta y cuatro mandamientos en una sola parashá: devolver lo perdido, ayudar al asno caído, no mezclar semillas, el peso justo, el nidal de la madre pájaro, el parapeto del tejado. La santidad se prueba en los tratos cotidianos, no en las ceremonias. El Eterno está en los detalles de la vida común.',
      '"No podrás esconderte" (Devarim 22:3) — la frase aparece dos veces. Ver el buey perdido del vecino y hacerse el distraído no es neutral: es una forma de robo. La Torá criminaliza la indiferencia. No basta con no hacer el mal: hay males que se cometen con la sola mirada hacia otro lado.',
      'La ley del nidal: si encuentras un nido con la madre sobre los polluelos, "no tomarás la madre sobre los hijos; la dejarás ir" (Devarim 22:6-7). ¿Por qué la Torá se detiene en una madre pájaro? El Midrash (Devarim Rabbá 6:1) lo llama "el más ligero de los mandamientos ligeros", y sin embargo su recompensa es la misma que la del honor a los padres: largos días. La compasión no tiene objetos pequeños: tiene entrenamiento diario.',
      'El parapeto del tejado (Devarim 22:8): quien construye casa debe poner baranda. La Torá legisla la prevención: no esperes el accidente para actuar; construye la protección antes. Toda casa — y toda comunidad, y todo corazón — necesita sus parapetos instalados antes de la caída.',
      'Y el cierre con Amalek: "Recuerda lo que te hizo Amalek en el camino… que te atacó por la retaguardia, a todos los débiles que quedaban atrás" (Devarim 25:17-18). La crueldad de Amalek no fue la guerra: fue elegir a los cansados. El mal se reconoce por su blanco preferido: el que va más lento. La comunidad santa se reconoce por lo contrario: cuida a los de la retaguardia.',
    ],
    fuente: 'Midrash Devarim Rabbá 6:1; Devarim 25:17-18',
  },
  {
    id: 'ki-tavo',
    nombre: 'Ki Tavó',
    hebreo: 'כִּי־תָבוֹא',
    lectura: 'Deuteronomio 26:1 – 29:8',
    titulo: 'La canasta y la confesión',
    citaHebreo: 'אֲרַמִּי אֹבֵד אָבִי וַיֵּרֶד מִצְרַיְמָה',
    citaEspanol: 'Un arameo errante fue mi padre, y descendió a Egipto',
    fuenteCita: 'Devarim 26:5',
    cuerpo: [
      'Las primicias se traían en canasta, y el que las entregaba recitaba una confesión que es la historia de Israel en miniatura: "Un arameo errante fue mi padre, y descendió a Egipto… y el Eterno nos sacó con mano fuerte" (Devarim 26:5-8). Esta declaración se convirtió en el corazón del Séder de Pésaj: toda gratitud comienza recordando de dónde venimos.',
      'Noten que la confesión se dice en primera persona: "mi padre", "nos afligieron", "nos sacó". El que trae las primicias no cuenta la historia de otros: se incluye. La memoria bíblica no es información sobre el pasado; es identificación con el pasado. Quien olvida que fue esclavo en Egipto termina haciendo esclavos.',
      'Y después de entregar la canasta, la orden sorprendente: "Te alegrarás en todo el bien que el Eterno tu Elohim te haya dado" (Devarim 26:11). La alegría es mandamiento, no sugerencia. El culto bíblico no es solo ayuno y temor: incluye la obligación de celebrar el bien recibido. Hay creyentes que dominan la confesión del pecado y suspenden la confesión de la bondad.',
      'La parashá también contiene la ceremonia de los montes Gerizim y Eval: seis tribus hacia la bendición, seis hacia la advertencia, y el pueblo respondiendo "Amén" a cada declaración (Devarim 27:12-26). El "amén" colectivo es la firma de la alianza: la comunidad entera suscribiendo, con una sola voz, los términos del pacto.',
      'Memoria humilde, corazón agradecido, manos generosas. Esa es la liturgia de Ki Tavó: traer lo primero, contar la historia completa, alegrarse del bien, y decir amén en comunidad. La fe que funciona es la que cabe en una canasta y en una confesión.',
    ],
    fuente: 'Devarim 26:5-11 — la confesión de las primicias',
  },
  {
    id: 'nitzavim',
    nombre: 'Nitzavim',
    hebreo: 'נִצָּבִים',
    lectura: 'Deuteronomio 29:9 – 30:20',
    titulo: 'No está en el cielo',
    citaHebreo: 'כִּי־קָרוֹב אֵלֶיךָ הַדָּבָר מְאֹד בְּפִיךָ וּבִלְבָבְךָ לַעֲשֹׂתוֹ',
    citaEspanol: 'Porque muy cerca de ti está la palabra, en tu boca y en tu corazón, para que la cumplas',
    fuenteCita: 'Devarim 30:14',
    cuerpo: [
      '"Ustedes están hoy de pie — nitzavim — todos ustedes delante del Eterno": y la lista baja desde los jefes hasta "el leñador y el aguador" (Devarim 29:9-10). La alianza no tiene invitados de segunda clase. En el día de la renovación del pacto, el último de la fila estaba tan de pie como el primero.',
      'Y luego, uno de los versículos más revolucionarios de la Torá: "Porque este mandamiento… no está en el cielo, para que digas: ¿quién subirá por nosotros al cielo?… sino que muy cerca de ti está la palabra, en tu boca y en tu corazón" (Devarim 30:11-14). La Torá no exige ascensos místicos ni intermediarios celestiales: ya bajó, ya está aquí, ya cabe en tu boca.',
      'El Talmud (Bavá Metziá 59b) cuenta la famosa disputa del horno de Ajnai: rabí Eliézer invocó milagros para sostener su opinión — un algarrobo se movió, el agua fluyó hacia atrás, las paredes se inclinaron, y hasta una voz del cielo habló — y los sabios respondieron citando este verso: "No está en el cielo". La Torá ya fue entregada: la interpretación quedó en manos de la comunidad que estudia, dialoga y decide. La halajá viva nació ese día.',
      '"He puesto delante de ti la vida y la muerte… escoge, pues, la vida" (Devarim 30:19). El versículo final de la parashá es un mandamiento de optimismo estructural: no solo se puede elegir la vida; se manda elegirla. En cada encrucijada, la Torá no se queda neutral: te grita hacia dónde.',
      'Nitzavim se lee siempre antes de Rosh HaShaná: el pueblo de pie, renovando la alianza antes del año nuevo. Así se entra a un año: no a la deriva, sino de pie, contados, juntos, con la palabra cerca del corazón.',
    ],
    fuente: 'Talmud Bavlí, Bavá Metziá 59b; Devarim 30:14',
  },
  {
    id: 'vayelej',
    nombre: 'Vayelej',
    hebreo: 'וַיֵּלֶךְ',
    lectura: 'Deuteronomio 31:1 – 31:30',
    titulo: 'El legado se entrega con coraje',
    citaHebreo: 'חִזְקוּ וְאִמְצוּ אַל־תִּירְאוּ וְאַל־תַּעַרְצוּ מִפְּנֵיהֶם כִּי יְהוָה אֱלֹהֶיךָ הוּא הַהֹלֵךְ עִמָּךְ',
    citaEspanol: 'Esforzaos y cobrad ánimo; no temáis ni os acobardéis delante de ellos, porque el Eterno tu Elohim es el que va contigo',
    fuenteCita: 'Devarim 31:6',
    cuerpo: [
      '"Tengo hoy ciento veinte años; ya no puedo salir ni entrar" (Devarim 31:2). Moshé anuncia su final sin drama ni autocompasión: presenta a su sucesor, escribe la Torá completa, la entrega a los sacerdotes y bendice al pueblo. Los grandes líderes no se aferran al cargo: preparan el relevo. La inmortalidad del líder no está en quedarse, sino en lo que deja funcionando.',
      'La consigna que Moshé deja a Iehoshúa es la misma que el Eterno repetirá tres veces al comienzo del libro siguiente: "Sé fuerte y valiente… porque el Eterno es el que va delante de ti; Él estará contigo, no te dejará ni te desamparará" (Devarim 31:8). El coraje bíblico no es ausencia de miedo: es la certeza de una compañía que no falla.',
      'Y la orden del Hakhel: cada siete años, en Sucot, todo el pueblo — "hombres, mujeres, niños y el extranjero" — se reunía a escuchar la lectura de la Torá (Devarim 31:10-12). La Torá no era propiedad de los escribas: era lectura pública, multitudinaria, con niños presentes "para que oigan y aprendan". La alfabetización de todo el pueblo fue siempre el proyecto.',
      'El Eterno le advierte a Moshé que el pueblo caerá, y le ordena escribir un cántico como testigo (Devarim 31:19). El remedio preventivo contra la infidelidad no es un ejército ni una ley: es una canción. Las letras se olvidan; las melodías quedan. Cuando todo lo demás falle, la canción testificará.',
      'El legado no se hereda con temor, sino con coraje. Todo lo que construimos — una comunidad, una familia, un Beit Midrash — debe poder sobrevivirnos. Si solo funciona mientras estamos, aún no es legado: es dependencia. Escribe tu Torá, forma a tu Iehoshúa, y entrega el bastón en vida.',
    ],
    fuente: 'Devarim 31:10-12; 31:19',
  },
  {
    id: 'haazinu',
    nombre: 'Haazinu',
    hebreo: 'הַאֲזִינוּ',
    lectura: 'Deuteronomio 32:1 – 32:52',
    titulo: 'Cuando la Torá se vuelve canción',
    citaHebreo: 'יַעֲרֹף כַּמָּטָר לִקְחִי תִּזַּל כַּטַּל אִמְרָתִי',
    citaEspanol: 'Gotee como la lluvia mi enseñanza; destile como el rocío mi palabra',
    fuenteCita: 'Devarim 32:2',
    cuerpo: [
      'El último mensaje de Moshé no fue un discurso: fue un cántico. Cuando las palabras comunes ya no alcanzan, la Torá se vuelve poesía. "Escucha, cielo, y hablaré; y oiga la tierra los dichos de mi boca" (Devarim 32:1). El cielo y la tierra son citados como testigos: los únicos que estarán presentes en toda la historia venidera.',
      'La metáfora central de la enseñanza es el agua suave: "Gotee como la lluvia mi enseñanza; destile como el rocío mi palabra; como llovizna sobre la grama" (Devarim 32:2). La enseñanza verdadera cae suave, empapa lento y hace brotar. El rocío no hace ruido como el aguacero, pero por la mañana todo está verde. Así enseña el maestro sabio: sin inundar, sin arrasar.',
      'El cántico repasa la historia con una imagen de ternura feroz: "Como el águila que despierta su nido, revolotea sobre sus pollos, extiende sus alas, los toma, los lleva sobre sus plumas; el Eterno solo lo condujo" (Devarim 32:11-12). El águila no empuja a sus polluelos al vacío por crueldad: los obliga a volar porque fueron hechos para el cielo. El desierto fue el vuelo de aprendizaje de un pueblo águila.',
      'Y la descripción del Eterno como "la Roca" aparece una y otra vez: "La Roca, cuya obra es perfecta" (Devarim 32:4). En un desierto de arenas movedizas, Israel aprendió que hay una Roca que no se mueve. Todo lo demás — Egipto, los imperios, los ídolos — es arena con buena publicidad.',
      'El cántico termina con Moshé subiendo al monte Nebó, a mirar la tierra que no pisará. Pero un pueblo que canta ya tiene la tierra dentro. Las canciones del Eterno cruzan fronteras que los pies no pueden cruzar.',
    ],
    fuente: 'Devarim 32:2; 32:11-12',
  },
  {
    id: 'vezot-haberaja',
    nombre: 'Vezot Haberajá',
    hebreo: 'וְזֹאת הַבְּרָכָה',
    lectura: 'Deuteronomio 33:1 – 34:12',
    titulo: 'Morir bendiciendo',
    citaHebreo: 'וְזֹאת הַבְּרָכָה אֲשֶׁר בֵּרַךְ מֹשֶׁה אִישׁ הָאֱלֹהִים אֶת־בְּנֵי יִשְׂרָאֵל לִפְנֵי מוֹתוֹ',
    citaEspanol: 'Y esta es la bendición con que Moshé, hombre de Elohim, bendijo a los hijos de Israel antes de su muerte',
    fuenteCita: 'Devarim 33:1',
    cuerpo: [
      'El último acto de Moshé no fue reclamar, fue bendecir. Tribu por tribu, nombre por nombre, el líder que sabía que no entraría a la tierra repartió bendiciones sobre los que sí entrarían. Morir bendiciendo es la cima de la madurez espiritual: celebrar el futuro de otros aunque no te incluya.',
      'La bendición sobre Leví contiene una frase escandalosa de entrega: quien "dijo de su padre y de su madre: no los vi, y a sus hermanos no reconoció… guardaron Tu palabra y conservaron Tu pacto" (Devarim 33:9). La consagración total reordena todos los afectos. No porque la familia no importe, sino porque hay llamados que se sirven con la vida entera.',
      '"Y bendijo a Iehoshúa": el relevo se completó en público, "y los hijos de Israel le oyeron" (Devarim 34:9). La sucesión legítima no necesita conspiración: se hace a la luz, con imposición de manos y espíritu de sabiduría. Las comunidades sanas heredan sin trauma porque sus líderes entregan sin sombra.',
      'Moshé subió al Nebó, y el Eterno le mostró toda la tierra: "Esta es la tierra que juré a Avraham, a Itzjak y a Yaakov… te he hecho verla con tus ojos, pero no pasarás allá" (Devarim 34:4). Y murió allí, "según la palabra del Eterno" — la tradición dice: besado por la boca del Eterno. El siervo más grande tuvo el funeral más íntimo: solo él y su Dios, y una tumba que nadie conoce para que nadie la adore.',
      'A veces la promesa se cumple en los que vienen después de nosotros. Y eso también es victoria. Moshé vio la tierra desde el monte, y desde entonces cada generación que entra, estudia y construye es una respuesta a su mirada. "No se ha levantado más en Israel profeta como Moshé" (Devarim 34:10) — y sin embargo, su obra sigue entrando a la tierra cada día.',
    ],
    fuente: 'Devarim 34:4-10',
  },
]
