import type { Tarjeta } from './tarjetasTypes'
export const TARJETAS_FESTIVIDADES: Tarjeta[] = [
  {
    id: 94,
    category: "festividad",
    hebTitle: "חנוכה",
    latTitle: "Janucá",
    title: "La Llama de Janucá",
    ref: "Talmud Shabat 21b",
    hebrewText: "נֵר יְהוָה נִשְׁמַת אָדָם",
    translation: "\"La lámpara de Dios es el alma del hombre\" (Proverbios 20:27)",
    analysis: "Janucá no conmemora un milagro bélico, sino <strong>el milagro de la persistencia</strong>. Una pequeña cantidad de aceite alcanzó para ocho días. La luz no se mide por su cantidad, sino por su <em>voluntad de arder</em>. Cada alma es una llama que puede durar más allá de lo esperado.",
    conclusion: "No necesitas mucho aceite para iluminar mucho tiempo. Solo necesitas arder con entrega.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 95,
    category: "festividad",
    hebTitle: "ראש השנה",
    latTitle: "Rosh Hashaná",
    title: "El Shofar del Despertar",
    ref: "Rosh Hashaná 16a",
    hebrewText: "תִּקְעוּ בַחֹדֶשׁ שׁוֹפָר",
    translation: "\"Tocad el shofar en la luna nueva\" (Salmos 81:4)",
    analysis: "El sonido del shofar no es música; es <strong>un grito sin palabras</strong>. En Rosh Hashaná, el <em>teki'á</em> (toque largo) y el <em>teru'á</em> (toque quebrado) representan la dualidad del ser humano: la aspiración a la unidad y el reconocimiento de la fragmentación.",
    conclusion: "El shofar no llama a Dios: llama a tu propia conciencia.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 96,
    category: "festividad",
    hebTitle: "יום כיפור",
    latTitle: "Iom Kipur",
    title: "El Ayuno que Purifica",
    ref: "Levítico 16:30",
    hebrewText: "כִּי-בַיּוֹם הַזֶּה יְכַפֵּר עֲלֵיכֶם",
    translation: "\"Porque en este día se hará expiación por vosotros\"",
    analysis: "Iom Kipur no es un día de castigo, sino de <strong>liberación</strong>. Ayunar no es un acto de mortificación, sino de <em>desapego</em> — una pausa para recordar que el ser humano no vive solo de pan. El perdón es una <strong>reconexión con la propia esencia</strong>.",
    conclusion: "Ayunar es vaciarse para que pueda entrar lo esencial.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 97,
    category: "festividad",
    hebTitle: "סוכות",
    latTitle: "Sucot",
    title: "La Sucá como Matriz",
    ref: "Levítico 23:42-43",
    hebrewText: "בַּסֻּכֹּת תֵּשְׁבוּ שִׁבְעַת יָמִים",
    translation: "\"En sucot habitaréis siete días\"",
    analysis: "La <em>sucá</em> es la <strong>morada de la vulnerabilidad</strong>. Sus paredes pueden ser frágiles, su techo debe dejar ver las estrellas. Habitar en la sucá es recordar que toda seguridad es ilusoria; solo la <em>bitajón</em> (confianza) en lo trascendente es refugio verdadero.",
    conclusion: "La verdadera protección no está en los muros, sino en la confianza que los habita.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 98,
    category: "festividad",
    hebTitle: "פסח",
    latTitle: "Pesaj",
    title: "El Pan de la Aflicción (Pesaj)",
    ref: "Deuteronomio 16:3",
    hebrewText: "לֶחֶם עֹנִי",
    translation: "\"Pan de aflicción\"",
    analysis: "La <em>matzá</em> es el pan de la <em>aflicción</em> (עוני), pero también de la <em>respuesta</em> (עניה). Es el pan que no tuvo tiempo de leudar, símbolo de la <strong>prisa de la redención</strong>. Comer matzá es tragar la historia: cada miga contiene la salida de Egipto.",
    conclusion: "La libertad se come con prisa, pero se digiere con gratitud.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 99,
    category: "festividad",
    hebTitle: "שבועות",
    latTitle: "Shavuot",
    title: "La Corona de la Torá (Shavuot)",
    ref: "Éxodo 19:1-20:23",
    hebrewText: "נַעֲשֶׂה וְנִשְׁמָע",
    translation: "\"Haremos y escucharemos\"",
    analysis: "En el Monte Sinaí, Israel declara <em>na'aseh ve-nishmá</em> (haremos y escucharemos). Primero la acción, luego la comprensión. Shavuot celebra la entrega de la Torá, pero también la <strong>aceptación de una responsabilidad</strong>. La Torá no se recibe: se <em>asume</em>.",
    conclusion: "No esperes entender para actuar. Actúa para entender.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 100,
    category: "festividad",
    hebTitle: "פורים",
    latTitle: "Purim",
    title: "La Alegría de Purim",
    ref: "Ester 9:22",
    hebrewText: "יְמֵי מִשְׁתֶּה וְשִׂמְחָה",
    translation: "\"Días de banquete y alegría\"",
    analysis: "Purim es la <strong>fiesta de la alegría</strong> en medio de la diáspora. El nombre de Dios no aparece en el libro de Ester, pero Su presencia se siente en los <strong>giros de la historia</strong>. La alegría de Purim es la <strong>certeza de que lo invisible sigue obrando</strong> incluso cuando no se ve.",
    conclusion: "La alegría es el testimonio de que Dios sigue presente, incluso en el silencio.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 101,
    category: "festividad",
    hebTitle: "שבת",
    latTitle: "Shabbat",
    title: "El Shabbat como Santuario",
    ref: "Éxodo 31:13",
    hebrewText: "אַךְ אֶת-שַׁבְּתֹתַי תִּשְׁמֹרוּ",
    translation: "\"Mis shabbatot guardaréis\"",
    analysis: "El Shabbat no es un día de descanso: es un <strong>santuario en el tiempo</strong>. Es el único santuario que no puede ser destruido por un enemigo. En Shabbat, el mundo material se detiene para que el <strong>alma pueda respirar</strong> y recordar su origen.",
    conclusion: "El Shabbat no es un día: es un espacio sagrado en el tiempo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 102,
    category: "festividad",
    hebTitle: "ראש השנה",
    latTitle: "Rosh Hashaná II",
    title: "El Día del Recuerdo (Rosh Hashaná II)",
    ref: "Levítico 23:24",
    hebrewText: "זִכְרוֹן תְּרוּעָה",
    translation: "\"Día de recuerdo con sonido de shofar\"",
    analysis: "Rosh Hashaná es el <strong>día del recuerdo</strong> (Yom Hazikarón). No solo Dios recuerda al hombre: el hombre es <strong>convocado a recordar</strong> su propósito. El shofar no es solo un sonido: es un <strong>despertador de la memoria</strong> olvidada.",
    conclusion: "El recuerdo no es nostalgia: es un llamado a despertar.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 103,
    category: "festividad",
    hebTitle: "חנוכה",
    latTitle: "Janucá II",
    title: "La Fiesta de las Luces (Janucá II)",
    ref: "Talmud Shabat 21b",
    hebrewText: "נֵר אֶחָד לְכָל בַּיִת",
    translation: "\"Una vela para cada casa\"",
    analysis: "La luz de Janucá se coloca en la <strong>puerta de la casa</strong>, para que sea visible desde fuera. No es una luz privada: es una <strong>luz que se comparte</strong>. Cada vela encendida es un <strong>testimonio público</strong> de que la oscuridad no tiene la última palabra.",
    conclusion: "La luz no se enciende para uno mismo: se enciende para ser vista.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 104,
    category: "festividad",
    hebTitle: "יום כיפור",
    latTitle: "Iom Kipur II",
    title: "El Día del Perdón (Iom Kipur II)",
    ref: "Levítico 16:30",
    hebrewText: "לִפְנֵי יְהוָה תִּטְהָרוּ",
    translation: "\"Ante Adonai seréis purificados\"",
    analysis: "Iom Kipur es el <strong>día del perdón</strong>, pero el perdón no es automático: es un <strong>proceso de arrepentimiento</strong> que comienza con el reconocimiento del error. La purificación no es mágica: es el <strong>resultado de la introspección</strong> y el cambio de dirección.",
    conclusion: "El perdón no se recibe: se construye con pasos de arrepentimiento.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 105,
    category: "festividad",
    hebTitle: "פסח",
    latTitle: "Pesaj II",
    title: "La Fiesta de la Liberación (Pesaj II)",
    ref: "Éxodo 12:14",
    hebrewText: "חֻקַּת עוֹלָם תְּחָגֻּהוּ",
    translation: "\"Ley perpetua la celebraréis\"",
    analysis: "Pesaj no es solo un recuerdo: es un <strong>evento que se revive</strong> en cada generación. La liberación de Egipto no es una historia antigua: es un <strong>arquetipo de toda liberación</strong>. Celebrar Pesaj es <strong>reclamar la libertad</strong> como un derecho y un deber.",
    conclusion: "La libertad no es un recuerdo: es una celebración perpetua.",
    signature: "— Moré Imanuel ben Efraim",
  },
]
