import type { Tarjeta } from './tarjetasTypes'
export const TARJETAS_HALAJA: Tarjeta[] = [
  {
    id: 128,
    category: "halaja",
    hebTitle: "יין נסך",
    latTitle: "Iein Neséj",
    title: "El Vino de No Judíos: ¿Una Prohibición que Caducó?",
    ref: "Avodá Zará 29b-31b; Shulján Aruj, Iore Deá 123",
    hebrewText: "יֵינוֹ שֶׁל עוֹבֵד כּוֹכָבִים וּמַזָּלוֹת אָסוּר בַּהֲנָאָה",
    translation: "\"El vino de un adorador de estrellas y constelaciones está prohibido para cualquier beneficio\"",
    analysis: "La fuente talmúdica (Avodá Zará 29b-31b) establece una distinción entre <em>iein neséj</em> (vino usado para libaciones idolátricas) y <em>stam ieinam</em> (vino común de no judíos). El Shulján Aruj (Iore Deá 123) codifica que todo vino tocado por un no judío queda prohibido, incluso sin evidencia de uso idolátrico.\n\nLa Mishná (Avodá Zará 2:3) explica: \"No se debe vender vino a un no judío, ni se debe aceptar vino de él\". El Talmud (Avodá Zará 31b) añade: \"¿Por qué prohibieron el vino de los no judíos? Porque lleva a la asimilación y al matrimonio mixto\".\n\nRambam (Mishné Torá, Hiljot Maajalot Asurot 11:7-8) explica que la prohibición tenía dos propósitos: 1) Evitar la idolatría: el vino podía ser usado para libaciones a dioses paganos; 2) Evitar la asimilación: compartir vino era un acto de familiaridad que llevaba a relaciones más profundas.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. La categoría <em>oved kojabim u-mazalot</em> (akum) ha desaparecido. En el mundo moderno, la mayoría de los no judíos no adoran astros ni constelaciones. El concepto de \"idolatría\" en el sentido talmúdico ya no se aplica al vecino que compra vino en el mismo supermercado.\n\n2. El contexto social ha cambiado. Compartir una botella de vino con un colega de trabajo hoy no conlleva automáticamente riesgo de asimilación o matrimonio mixto. La prohibición original buscaba evitar un fenómeno social que hoy opera de manera muy diferente.\n\n3. La producción es industrial, no ritual. El vino que compramos en el supermercado no es producido con intención idolátrica. Es un producto comercial, no un objeto de culto.",
    conclusion: "La prohibición del vino de no judíos, en su aplicación estricta, responde a un contexto que ya no existe. No se trata de \"anular\" la ley, sino de reconocer que el propósito de la ley (evitar asimilación, preservar identidad) puede cumplirse hoy de otras maneras.\n\nComprar vino en un supermercado no te asimila. La identidad judía se preserva en el Shabbat, en el estudio, en la comunidad, no en el temor a una botella de vino.\n\nEl principio evolutivo es: la ley debe servir a la vida, no la vida a la ley.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 129,
    category: "halaja",
    hebTitle: "הבערת אש בשבת",
    latTitle: "Hav'ará Esh BeShabbat",
    title: "La Electricidad en Shabbat: ¿Es Fuego?",
    ref: "Shulján Aruj, Oraj Jaim 318; Mishná Berurá 318:39",
    hebrewText: "הַמַּבְעִיר אֵשׁ בְּשַׁבָּת — חַיָּב",
    translation: "\"Quien enciende fuego en Shabbat — es culpable\"",
    analysis: "La Torá (Éxodo 35:3) dice: \"No encenderéis fuego en todas vuestras moradas en el día de Shabbat\". La Mishná (Shabbat 73a) enumera <em>hav'ará</em> (encender fuego) como una de las 39 categorías de trabajo prohibidas.\n\nEl Shulján Aruj (Oraj Jaim 318) define <em>hav'ará</em> como \"la creación de una llama que produce calor o luz\". La Mishná Berurá (318:39) aclara que \"todo aquello que produce calor o luz con una chispa\" está incluido.\n\nLos primeros poskim discutieron la electricidad. El Jazon Ish (Oraj Jaim 50:9) sostuvo que la electricidad es como <em>hav'ará</em> porque produce luz y calor. El Rav Shlomo Zalman Auerbach (Minjat Shlomo 1:9) argumentó que la electricidad no es fuego en el sentido halájico porque no implica combustión, sino que es un fenómeno físico distinto.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. La electricidad es omnipresente. En la época del Talmud, el \"fuego\" era algo que se encendía con una chispa o una brasa. Hoy, la electricidad es una fuerza que está presente en todos los hogares, incluso sin \"encenderla\" (los electrodomésticos están conectados permanentemente).\n\n2. La prohibición original era sobre \"crear\" fuego. El texto bíblico dice \"no encenderéis\" — es decir, el acto de iniciar una llama. Pero ¿\"abrir\" un circuito eléctrico es \"crear fuego\"? ¿O es simplemente \"permitir\" que la electricidad fluya?\n\n3. El uso de electricidad en Shabbat hoy. Muchos judíos usan <em>timer</em> (Shabbat clock) para luces y electrodomésticos. ¿Es esto un \"encendido\" directo o una acción indirecta? Algunos poskim permiten el uso de electricidad para necesidades básicas (calefacción, refrigeración) porque el contexto de vida moderna lo requiere.",
    conclusion: "La prohibición de encender fuego en Shabbat fue originalmente una salvaguarda contra la creación de luz y calor con intención humana. Sin embargo, la electricidad no es fuego en el sentido halájico tradicional — no implica combustión, no produce humo, y su \"encendido\" es un acto conceptual, no físico.\n\nEl principio evolutivo es: el Shabbat es un día de descanso, no de ansiedad. Si encender una luz te permite descansar mejor, si usar un electrodoméstico te facilita el Shabbat, quizás el espíritu de la ley está siendo preservado mejor que la letra.\n\nLa pregunta no es \"¿qué está prohibido?\" sino \"¿qué me acerca al Shabbat como santuario en el tiempo?\"",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 130,
    category: "halaja",
    hebTitle: "הלכות צניעות",
    latTitle: "Hiljot Tzeniut",
    title: "La Modestia: ¿Cubrir el Cuerpo o Cubrir el Alma?",
    ref: "Shulján Aruj, Even HaEzer 21; Rambam, Hiljot Issurei Biá 21:2-5",
    hebrewText: "וְהַצְנֵעַ לֶכֶת עִם-אֱלֹהֶיךָ",
    translation: "\"Y caminar humildemente con tu Dios\" (Miqueas 6:8)",
    analysis: "El concepto de <em>tzeniut</em> (modestia) tiene dos fuentes principales en la tradición: 1) Texto bíblico: Miqueas 6:8 establece <em>tzeniut</em> como un principio espiritual: caminar humildemente con Dios, no es una ley de vestimenta, sino una actitud interior; 2) Desarrollo rabínico: El Shulján Aruj (Even HaEzer 21) y el Rambam (Hiljot Issurei Biá 21:2-5) desarrollaron normas específicas sobre la vestimenta: cabello cubierto para mujeres casadas, ropa que cubre codos y rodillas, y la prohibición de ropa que \"atraiga la atención\" (ropa ajustada, transparente o de colores llamativos).\n\n<strong>Pero ¿cuál era el contexto original?</strong>\n\nLa halajá sobre vestimenta se desarrolló en un contexto donde: 1) La distinción de género era fundamental en la sociedad; 2) La sexualidad estaba regulada por normas comunitarias estrictas; 3) La identidad judía se expresaba también a través de la ropa (diferenciación de otras culturas).\n\nRambam (Guía de los Perplejos 3:33) explica que las leyes de vestimenta buscan \"alejar al hombre de la lujuria y la liviandad, y llevarlo a la santidad y la pureza\".\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. El concepto de \"atraer atención\" es subjetivo. Lo que en el siglo XVI era \"llamativo\", en el siglo XXI puede ser perfectamente normal. La moda cambia, la cultura cambia, y la halajá no puede fijar un estándar inmutable de lo que es \"modesto\".\n\n2. La mujer moderna es agente, no objeto. Las leyes de tzeniut tradicionales a menudo se centraban en regular la vestimenta femenina, como si la responsabilidad de la pureza recayera unilateralmente sobre la mujer. Hoy entendemos que la dignidad y el respeto son responsabilidad de todos.\n\n3. El propósito original era la santidad, no el control. La santidad no se logra cubriendo el cuerpo sino viviendo con integridad. Una persona puede estar vestida \"modestamente\" y tener un alma inmodesta, o vestirse \"modernamente\" y tener un corazón lleno de santidad.",
    conclusion: "La <em>tzeniut</em> en su esencia no es una ley de vestimenta: es una actitud del alma. Es la capacidad de estar presente sin necesidad de ocupar todo el espacio. Es saber cuándo mostrarse y cuándo retirarse. Es la dignidad de la presencia frente a la exposición vacía.\n\nLa pregunta no es \"¿cuánta piel cubres?\" sino \"¿cuánta presencia ocupas?\"\n\nEl principio evolutivo es: la modestia verdadera no se mide con una cinta métrica, sino con la calidad de la presencia del alma.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 131,
    category: "halaja",
    hebTitle: "תפילה בלשון המובן",
    latTitle: "Tefilá BeLashon HaMuván",
    title: "La Oración en Idioma Local: ¿Hebreo o el Corazón?",
    ref: "Shulján Aruj, Oraj Jaim 101:4; Mishná Berurá 101:6",
    hebrewText: "וְשִׁחֲרוּנִי וְחַיִּים",
    translation: "\"Buscadme y viviréis\" (Amós 5:4)",
    analysis: "La Mishná (Sotá 7:1) permite la oración en cualquier idioma: \"Estas son dichas en cualquier lengua: la sección de Sotá, la declaración de las primicias, y la lectura del Shemá y la oración\". El Shulján Aruj (Oraj Jaim 101:4) codifica: \"Se puede rezar en cualquier idioma que uno entienda\".\n\n<strong>Pero ¿por qué la oración en hebreo se volvió normativa?</strong>\n\nEl Rambam (Mishné Torá, Hiljot Tefilá 1:4) explica: \"La oración debe ser en hebreo porque es la lengua de los ángeles\" — pero también añade que \"si uno no entiende hebreo, debe rezar en su lengua propia\".\n\nEl problema es que, con el tiempo, la práctica se volvió rígida: muchos judíos rezan el texto hebreo sin entenderlo, convirtiendo la oración en un ejercicio mecánico.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. La comprensión es el propósito de la oración. La oración no es magia: es diálogo. Si no entiendes lo que dices, ¿cómo puedes dirigirte a Dios con el corazón? El Talmud (Berajot 31a) dice: \"La oración requiere atención\" (<em>kavaná</em>). Sin comprensión, no hay atención.\n\n2. El hebreo ya no es lengua vernácula. En la época del Segundo Templo, el hebreo era la lengua común de Judea. Hoy, la mayoría de los judíos hablan español, inglés, francés, ruso, etc. La oración en hebreo se ha convertido en un acto de \"mantener la tradición\" más que de \"expresar el corazón\".\n\n3. La Torá es para todos, no solo para eruditos. La oración no debe ser un privilegio de quienes estudiaron hebreo. Cada alma tiene derecho a dirigirse a su Creador en la lengua de su corazón.",
    conclusion: "La halajá siempre ha permitido la oración en la lengua local. La rigidez del hebreo como único idioma válido es una construcción posterior que no tiene base sólida en la fuente original.\n\nEl principio evolutivo es: Dios entiende todos los idiomas. La pregunta no es \"¿en qué lengua rezas?\" sino \"¿con qué corazón rezas?\"",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 132,
    category: "halaja",
    hebTitle: "תולעים בירקות",
    latTitle: "Tolaim BeYerakot",
    title: "Insectos en Vegetales: ¿Obsesión o Precaución?",
    ref: "Shulján Aruj, Iore Deá 84:8-10",
    hebrewText: "וְהִבְדַּלְתֶּם בֵּין הַטָּמֵא וּבֵין הַטָּהֹר",
    translation: "\"Y distinguiréis entre lo impuro y lo puro\" (Levítico 11:47)",
    analysis: "La Torá prohíbe comer insectos (Levítico 11:20-23). El Shulján Aruj (Iore Deá 84:8-10) codifica que los vegetales deben ser inspeccionados para eliminar cualquier insecto visible.\n\n<strong>Pero ¿cuál es el problema hoy?</strong>\n\n1. Los insectos son microscópicos. Muchos insectos (ácaros, pulgones) son casi invisibles a simple vista. ¿Cómo puede una persona común inspeccionar adecuadamente? La exigencia se ha vuelto prácticamente imposible.\n\n2. La agricultura moderna usa pesticidas. En la época talmúdica, los vegetales crecían en campos abiertos con insectos visibles. Hoy, la agricultura industrial usa pesticidas que eliminan la mayoría de los insectos. El riesgo real es mínimo.\n\n3. Hay un enfoque desproporcionado. Muchas comunidades judías han desarrollado una ansiedad obsesiva con los insectos, mientras que descuidan aspectos éticos mucho más importantes de la kashrut (como el trato ético a los animales).",
    conclusion: "La prohibición de insectos tiene sentido cuando son visibles y evitables. Cuando la inspección se vuelve obsesiva y el riesgo es mínimo, la ley se convierte en una carga que aleja de la espiritualidad.\n\nEl principio evolutivo es: la kashrut debe acercar a Dios, no generar ansiedad. Si un vegetal ha sido lavado y no tiene insectos visibles, es suficiente. El resto es prudencia excesiva que pierde de vista el propósito.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 133,
    category: "halaja",
    hebTitle: "נשים ותלמוד תורה",
    latTitle: "Nashim VeTalmud Torá",
    title: "Mujeres y Estudio de Torá: ¿Un Privilegio o un Derecho?",
    ref: "Talmud, Sotá 20a; Shulján Aruj, Iore Deá 246:6",
    hebrewText: "אֵין מְלַמְּדִין אֶת הַבַּת תּוֹרָה",
    translation: "\"No se enseña a la hija la Torá\" (Talmud Sotá 20a)",
    analysis: "El Talmud (Sotá 20a) declara: \"Quien enseña a su hija la Torá, es como si le enseñara liviandad\" (o \"cosas vanas\"). El Shulján Aruj (Iore Deá 246:6) codifica esta opinión: \"La mujer no está obligada al estudio de la Torá, y quien enseña a su hija la Torá es como si le enseñara cosas vanas\".\n\n<strong>Pero ¿cuál era el contexto?</strong>\n\n1. El Talmud habla de un contexto específico. Rashi (comentario a Sotá 20a) explica que la \"liviandad\" se refiere a que la mujer podría usar el conocimiento bíblico para justificar conductas inapropiadas. Esto refleja una visión de su época.\n\n2. La mujer no tenía acceso a la educación formal. En la sociedad talmúdica, las mujeres no estudiaban en las academias. La educación femenina era doméstica y práctica.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. La mujer moderna es educada. Hoy las mujeres estudian en universidades, son profesionales y líderes. No hay razón para excluir a la mujer del estudio de la Torá.\n\n2. El propósito del estudio es para todos. La Torá dice \"Tú eres testigo\" (Deuteronomio 30:19) — la alianza es con todo Israel, hombres y mujeres. La mujer tiene el mismo derecho a conocer la palabra de Dios.\n\n3. Grandes mujeres de la tradición. La Torá misma presenta a mujeres sabias: Miriam, Débora, Juldá (la profetisa), Bruría (la esposa de Rabí Meir). La tradición tiene ejemplos de mujeres que estudiaban y enseñaban.",
    conclusion: "La prohibición de enseñar Torá a las mujeres responde a un contexto social que ya no existe. Hoy, la mujer tiene la misma capacidad y el mismo derecho al estudio de la Torá que el hombre.\n\nEl principio evolutivo es: la Torá es un legado para todo el pueblo de Israel. La educación no debe ser un privilegio de género, sino un derecho de cada alma que busca a Dios.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 134,
    category: "halaja",
    hebTitle: "ברכת המזון",
    latTitle: "Birkat Hamazón",
    title: "Birkat Hamazón sin Comida: ¿Gratitud o Formalidad?",
    ref: "Shulján Aruj, Oraj Jaim 185",
    hebrewText: "וְאָכַלְתָּ וְשָׂבָעְתָּ וּבֵרַכְתָּ",
    translation: "\"Y comerás y te saciarás y bendecirás\" (Deuteronomio 8:10)",
    analysis: "La Torá (Deuteronomio 8:10) establece la obligación de bendecir después de comer: \"Y comerás y te saciarás y bendecirás\". El Shulján Aruj (Oraj Jaim 185) codifica que esta bendición (<em>Birkat Hamazón</em>) debe recitarse después de una comida con pan (<em>se'udá</em>).\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. La estructura de la comida ha cambiado. En la época talmúdica, la comida principal era el pan. Hoy, muchas personas tienen comidas sin pan (ensaladas, sushi, comidas rápidas). ¿La bendición debe ser recitada solo por el pan?\n\n2. La gratitud es el principio, no la formalidad. El texto bíblico no dice \"bendecirás por el pan\", sino \"bendecirás porque te saciaste\". El principio es la gratitud, no el tipo de alimento.\n\n3. La fragmentación de las comidas. Hoy, las personas comen varias veces al día, no siempre comidas formales. ¿Cuántas bendiciones deben recitarse? ¿Cuándo empieza y termina una \"comida\"?",
    conclusion: "La halajá ha sido flexible: el Shulján Aruj (Oraj Jaim 184) permite recitar <em>Birkat Hamazón</em> incluso si no se comió pan, siempre que la comida haya sido significativa (una cantidad mínima de alimentos).\n\nEl principio evolutivo es: la gratitud no depende del tipo de alimento, sino de la conciencia de haber recibido. Si te saciaste, bendice. El tipo de comida es secundario.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 135,
    category: "halaja",
    hebTitle: "שמיטה בזמן הזה",
    latTitle: "Shmitá BaZman HaZeh",
    title: "Shmitá Hoy: ¿Ley Agrícola o Conciencia Ecológica?",
    ref: "Levítico 25:1-7; Shulján Aruj, Joshen Mishpat 67",
    hebrewText: "וְשָׁבְתָה הָאָרֶץ שַׁבָּת לַיהוָה",
    translation: "\"Y la tierra descansará un Shabbat para Adonai\" (Levítico 25:2)",
    analysis: "La Torá establece el año sabático (<em>Shmitá</em>): cada siete años, la tierra debe descansar. No se puede sembrar, ni cosechar, ni podar. La tierra es de Dios, no del hombre.\n\n<strong>Pero ¿cuál era el contexto?</strong>\n\n1. La agricultura era la base de la economía. En la época bíblica, la tierra era la principal fuente de sustento. La <em>Shmitá</em> era un acto de fe radical: dejar de cultivar y confiar en que Dios proveería.\n\n2. La tierra en Israel era productiva. La tierra de Israel era fértil y podía sostener a la población incluso en años de descanso.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. Hoy, la agricultura industrial es global. La <em>Shmitá</em> en Israel se ha vuelto problemática: los agricultores necesitan producir para sobrevivir en una economía competitiva. Muchos recurren a la <em>heter mejirá</em> (venta simbólica de la tierra a un no judío) para evitar la prohibición.\n\n2. El principio de la tierra como propiedad de Dios. El principio profundo de la <em>Shmitá</em> es recordar que la tierra no es del hombre, sino de Dios. ¿Cómo se aplica esto en una economía industrializada?\n\n3. Fuera de Israel, la <em>Shmitá</em> no se aplica. La <em>Shmitá</em> solo se aplica en la Tierra de Israel. Pero el principio de dar descanso a la tierra y confiar en Dios tiene un valor universal.",
    conclusion: "La <em>Shmitá</em> es un recordatorio de que la tierra no es nuestra, sino de Dios. La <em>heter mejirá</em> es una solución técnica, pero el espíritu de la ley sigue siendo relevante: confiar en Dios y dar descanso a la creación.\n\nEl principio evolutivo es: la <em>Shmitá</em> no es solo un año, sino una actitud. Es aprender a confiar en lugar de controlar, a descansar en lugar de producir sin límite.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 136,
    category: "halaja",
    hebTitle: "גיור",
    latTitle: "Giyur",
    title: "Conversión: ¿Puerta o Muralla?",
    ref: "Talmud Yevamot 47a-b; Shulján Aruj, Iore Deá 268",
    hebrewText: "וְגֵר לֹא תִלְחָץ",
    translation: "\"Y al extranjero no oprimirás\" (Éxodo 22:20)",
    analysis: "La Torá establece una relación especial con el <em>ger</em> (converso / extranjero): \"Amarás al extranjero como a ti mismo\" (Levítico 19:34). El Talmud (Yevamot 47a-b) detalla el proceso de conversión: debe ser aceptada por un tribunal (<em>bet din</em>) y requiere circuncisión, inmersión en mikvé y aceptación de las mitzvot.\n\n<strong>Pero ¿cuál es el problema hoy?</strong>\n\n1. La conversión se ha burocratizado. En el Estado de Israel, las conversiones están controladas por el Rabinato, que exige un nivel de observancia que muchos conversos no pueden mantener. El resultado: miles de personas viven en Israel como \"no judíos\" aunque son descendientes de judíos.\n\n2. El principio de \"no oprimir al extranjero\". La Torá ordena no oprimir al extranjero. Cuando el proceso de conversión se vuelve excluyente y deshumanizante, ¿estamos cumpliendo con este mandato?\n\n3. La conversión como proceso espiritual, no burocrático. La conversión es un cambio del alma: el deseo de pertenecer al pueblo de Dios. Cuando se convierte en un examen de conocimientos, pierde su esencia.",
    conclusion: "La conversión debe ser un proceso espiritual, no burocrático. La Torá no quiere excluir, sino incluir. El <em>ger</em> debe ser amado, no temido.\n\nEl principio evolutivo es: la puerta del judaísmo debe ser lo suficientemente ancha para el que busca sinceramente, y lo suficientemente firme para proteger la identidad del pueblo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 137,
    category: "halaja",
    hebTitle: "תשובה ופסיכולוגיה",
    latTitle: "Teshuvá VePsicología",
    title: "Teshuvá: ¿Arrepentimiento o Terapia del Alma?",
    ref: "Rambam, Hiljot Teshuvá 2:2-4",
    hebrewText: "וְשַׁבְתָּ עַד-יְהוָה",
    translation: "\"Y te volverás a Adonai\" (Deuteronomio 30:2)",
    analysis: "Rambam (Hiljot Teshuvá 2:2-4) describe el proceso de arrepentimiento: 1) Reconocer el error; 2) Arrepentirse sinceramente; 3) Confesar el error; 4) Resolver no repetirlo; 5) Pedir perdón a la persona ofendida. Este es el proceso halájico de la <em>teshuvá</em>.\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. La psicología moderna ha profundizado nuestra comprensión del \"cambio\". Sabemos que el cambio de comportamiento no es solo un acto de voluntad, sino que requiere trabajar las causas profundas (traumas, patrones de conducta, etc.).\n\n2. La culpa y la vergüenza pueden ser paralizantes. La <em>teshuvá</em> tradicional a veces se vive con culpa y vergüenza, lo que puede llevar a la parálisis en lugar del cambio. La psicología nos enseña que el cambio requiere autocompasión, no autocrítica.\n\n3. El proceso de cambio es gradual. La <em>teshuvá</em> no es un acto único, sino un proceso que puede tomar tiempo. La psicología moderna nos ayuda a entender que el cambio requiere paciencia y acompañamiento.",
    conclusion: "La <em>teshuvá</em> no es solo un acto ritual: es un proceso de sanación del alma. La psicología moderna puede ayudarnos a entender mejor cómo funciona el cambio y cómo hacerlo sostenible.\n\nEl principio evolutivo es: el arrepentimiento no es un castigo, sino una terapia del alma. No se trata de sufrir por el error, sino de sanar y crecer.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 138,
    category: "halaja",
    hebTitle: "נתיחה שלאחר המוות",
    latTitle: "Netijá SheLeAjar HaMavet",
    title: "Autopsias: ¿Profanación o Pikuaj Nefesh?",
    ref: "Shulján Aruj, Iore Deá 363",
    hebrewText: "כִּי-עָפָר אַתָּה",
    translation: "\"Porque polvo eres\" (Génesis 3:19)",
    analysis: "La halajá establece que el cuerpo humano debe ser enterrado completo, sin ser profanado. El Shulján Aruj (Iore Deá 363) prohíbe la autopsia, excepto en casos donde pueda salvar una vida inmediata.\n\n<strong>Pero ¿cuál es el contexto?</strong>\n\n1. La autopsia en la antigüedad era una profanación. En la época talmúdica, las autopsias eran realizadas por médicos no judíos en contextos de explotación o falta de respeto. La halajá rechazaba la autopsia como un acto de deshonra al muerto.\n\n2. El cuerpo es una vasija del alma. La tradición enseña que el cuerpo es sagrado porque fue un recipiente del alma. Profanar el cuerpo es una falta de respeto.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. La autopsia moderna salva vidas. Hoy, la autopsia puede ayudar a diagnosticar enfermedades genéticas, avanzar en la investigación médica y salvar vidas. ¿Es correcto prohibirla cuando puede salvar a otros?\n\n2. El principio de \"salvar una vida\" (<em>pikuaj nefesh</em>). El Talmud enseña que salvar una vida es más importante que casi todas las mitzvot. Si una autopsia puede salvar vidas, ¿no debería permitirse?\n\n3. La donación de órganos. La donación de órganos es una forma de autopsia que salva vidas. ¿Debe permitirse? Algunos poskim la permiten, otros la prohíben.",
    conclusion: "La autopsia no es una profanación del cuerpo cuando tiene un propósito sagrado: salvar vidas. La halajá debe distinguir entre la autopsia como investigación y la autopsia como herramienta terapéutica.\n\nEl principio evolutivo es: la vida es más sagrada que la muerte. Si una autopsia puede salvar vidas, es un acto de <em>pikuaj nefesh</em> y debe permitirse.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 139,
    category: "halaja",
    hebTitle: "עקידת יצחק",
    latTitle: "Akedat Itzjak",
    title: "La Atadura de Itzjak: ¿Obediencia o Evolución de la Conciencia?",
    ref: "Génesis 22; Rambam, Guía de los Perplejos 3:24",
    hebrewText: "וַיַּעֲקֹד אֶת-יִצְחָק",
    translation: "\"Y ató a Itzjak\" (Génesis 22:9)",
    analysis: "La <em>Akedá</em> (Génesis 22) es la historia de cómo Dios prueba a Avraham pidiéndole que ofrezca a su hijo Itzjak como sacrificio. Avraham obedece, pero en el último momento un ángel detiene su mano.\n\n<strong>Pero ¿qué interpretación se ha dado?</strong>\n\n1. La interpretación tradicional: La <em>Akedá</em> es el modelo de la obediencia absoluta a Dios. Avraham está dispuesto a sacrificar a su hijo por amor a Dios. Es la cumbre de la fe.\n\n2. Rambam (Guía de los Perplejos 3:24): La <em>Akedá</em> no es sobre la obediencia, sino sobre el amor. Avraham ama tanto a Dios que está dispuesto a entregar lo que más ama.\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. La lectura crítica de la historia. Muchos comentaristas modernos preguntan: ¿Qué clase de Dios pide el sacrificio de un hijo? ¿No es esta una imagen de Dios que debemos superar?\n\n2. El desarrollo de la conciencia ética. La Torá misma rechaza el sacrificio humano (Levítico 18:21). La <em>Akedá</em> puede leerse como el momento en que Dios dice: \"Basta. No quiero sacrificios humanos. Quiero misericordia\".\n\n3. El sacrificio ya no es literal. El Templo fue destruido, los sacrificios cesaron. Hoy, \"ofrecer\" a Dios significa ofrecer nuestro corazón, no nuestra carne.",
    conclusion: "La <em>Akedá</em> no es un modelo de obediencia ciega, sino un proceso de evolución espiritual. Dios no quiere sacrificios humanos; quiere corazones entregados.\n\nEl principio evolutivo es: la relación con Dios no se basa en el sacrificio, sino en la confianza y el amor. La <em>Akedá</em> es el momento en que Dios dice: \"No necesito que mueras por Mí; necesito que vivas para Mí\".",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 140,
    category: "halaja",
    hebTitle: "איסור ריבית",
    latTitle: "Issur Ribbit",
    title: "Usura e Interés: ¿Explotación o Herramienta Económica?",
    ref: "Shulján Aruj, Iore Deá 159-177",
    hebrewText: "אֶת-כַּסְפְּךָ לֹא-תִתֵּן לוֹ בְּנֶשֶׁךְ",
    translation: "\"No darás tu dinero con interés\" (Levítico 25:37)",
    analysis: "La Torá prohíbe prestar dinero con interés a otro judío (Éxodo 22:24, Levítico 25:36-37, Deuteronomio 23:20-21). El Shulján Aruj (Iore Deá 159-177) desarrolla extensas normas sobre el <em>ribbit</em> (usura).\n\n<strong>Pero ¿cuál es el contexto original?</strong>\n\n1. El préstamo en la antigüedad era para sobrevivir. En la época bíblica, la gente pedía préstamos para no morir de hambre. Cobrar interés a un hermano que está pasando hambre era considerado una crueldad.\n\n2. El interés era una forma de explotación. Cobrar interés a los pobres era considerado una opresión. La Torá protege a los más vulnerables.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. Hoy, los préstamos son para inversión, no para sobrevivir. En la economía moderna, los préstamos son herramientas para crear riqueza, no para evitar el hambre. ¿Es la misma situación?\n\n2. El interés es parte del sistema financiero. Los bancos cobran interés porque el dinero tiene valor en el tiempo. ¿Cómo se aplica la prohibición en la economía moderna?\n\n3. Las <em>heter iská</em> (permisos de inversión). La halajá ha desarrollado mecanismos para permitir transacciones que involucran interés, como la <em>heter iská</em>, donde el préstamo se convierte en una inversión compartida. Esto muestra que la halajá evoluciona para adaptarse a las necesidades económicas.",
    conclusion: "La prohibición del interés protege a los vulnerables de la explotación. Hoy, el principio sigue siendo válido: no debemos explotar al necesitado.\n\nEl principio evolutivo es: el interés no está prohibido en sí mismo, sino cuando se convierte en explotación. En una economía moderna, el interés es una herramienta legítima, siempre que no oprima a los pobres.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 141,
    category: "halaja",
    hebTitle: "לשון הרע ברשתות חברתיות",
    latTitle: "Lashon Hará BeRashot Jevratiot",
    title: "Lashon Hará en Redes Sociales: El Chisme en la Era Digital",
    ref: "Shulján Aruj, Joshen Mishpat 18:1-5; Jafetz Jaim, Hiljot Lashon Hará 1:1-4",
    hebrewText: "לֹא-תֵלֵךְ רָכִיל",
    translation: "\"No andarás chismeando\" (Levítico 19:16)",
    analysis: "La Torá prohíbe el <em>lashon hará</em> (lengua mala): el acto de hablar mal de otros, incluso si es verdad. El Jafetz Jaim (Hiljot Lashon Hará 1:1-4) desarrolla extensas leyes sobre lo que constituye <em>lashon hará</em>, cuándo está prohibido y cuándo permitido.\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. El alcance de la palabra se ha ampliado. En la época talmúdica, el <em>lashon hará</em> se transmitía de boca a boca. Hoy, un tuit o un comentario puede llegar a miles de personas en segundos. El daño es exponencial.\n\n2. La cultura del \"compartir\" y el \"dar like\". Las redes sociales nos invitan a compartir opiniones, juicios y comentarios. A menudo, esto se convierte en <em>lashon hará</em> sin que nos demos cuenta. Dar \"like\" a un comentario negativo es una forma de participar en el chisme.\n\n3. El anonimato facilita la falta de responsabilidad. En internet, las personas dicen cosas que nunca dirían en persona. La falta de identidad reduce la barrera moral.",
    conclusion: "El <em>lashon hará</em> en redes sociales es la misma falta moral que la del chisme tradicional, pero con un alcance y daño mucho mayores. La prohibición de Levítico 19:16 se aplica hoy con más urgencia que nunca.\n\nEl principio evolutivo es: la palabra en la era digital tiene el mismo poder, pero mayor alcance. Lo que decimos en línea, lo decimos al mundo. La responsabilidad es mayor.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 142,
    category: "halaja",
    hebTitle: "יום כיפור וחולה",
    latTitle: "Iom Kipur VeJolé",
    title: "Ayuno en Iom Kipur con Enfermedad: ¿Sacrificio o Pikuaj Nefesh?",
    ref: "Shulján Aruj, Oraj Jaim 618; Mishná Berurá 618",
    hebrewText: "וַחֲיִיתֶם בָּהֶם",
    translation: "\"Y viviréis por ellos\" (Levítico 18:5)",
    analysis: "El ayuno en Iom Kipur es una de las mitzvot más importantes del calendario judío. Está escrito: \"Os afligiréis\" (Levítico 23:27). El Shulján Aruj (Oraj Jaim 618) establece que cualquier persona que esté enferma debe consultar a un médico para saber si puede ayunar.\n\n<strong>Pero ¿cuál es la regla general?</strong>\n\n1. El principio de <em>pikuaj nefesh</em> (salvar una vida). El Talmud (Yoma 85b) enseña: \"El Shabbat es para vosotros, no vosotros para el Shabbat\". El mismo principio aplica al ayuno: si alguien está en peligro, debe comer.\n\n2. El ayuno no debe ser peligroso. La Mishná Berurá (618:7) dice: \"Si hay duda sobre si el ayuno causará daño, debe consultar a un médico\". La vida es más sagrada que el ayuno.\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. Hoy sabemos más sobre enfermedades. La medicina moderna puede diagnosticar y tratar condiciones que antes eran desconocidas. Las personas con diabetes, enfermedades cardíacas, o deshidratación crónica deben tener cuidado.\n\n2. El ayuno no es un fin en sí mismo. El propósito del ayuno es la <em>teshuvá</em>, no el sufrimiento. Si el ayuno impide la <em>teshuvá</em> (porque te debilita o te enferma), entonces debe evitarse.",
    conclusion: "El ayuno en Iom Kipur es una mitzvá importante, pero la vida es más importante. Si el ayuno te pone en peligro, debes comer. La salud es un mandato divino.\n\nEl principio evolutivo es: la vida es más sagrada que el ayuno. El ayuno es un medio para la <em>teshuvá</em>, no un fin en sí mismo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 143,
    category: "halaja",
    hebTitle: "כיסוי ראש",
    latTitle: "Kisui Rosh",
    title: "Kipá: ¿Señal de Temor o Símbolo de Identidad?",
    ref: "Shulján Aruj, Oraj Jaim 2:6; Mishná Berurá 2:9",
    hebrewText: "כַּבֵּד אֶת-ה'",
    translation: "\"Honra a Adonai\" (Proverbios 3:9)",
    analysis: "La costumbre de cubrir la cabeza (kipá) no está explícitamente en la Torá. El Talmud (Shabbat 156b) menciona que los sabios cubrían su cabeza para recordar la presencia de Dios. El Shulján Aruj (Oraj Jaim 2:6) dice: \"No se debe caminar con la cabeza descubierta\".\n\n<strong>Pero ¿cuál es el contexto original?</strong>\n\n1. La kipá como señal de temor. La kipá es una señal de que Dios está sobre nosotros. Es un recordatorio de que estamos siempre en presencia de lo sagrado.\n\n2. La costumbre, no la ley. La kipá es una costumbre, no una ley bíblica. En la época talmúdica, cubrir la cabeza era una señal de respeto y temor.\n\n<strong>¿Qué ha cambiado?</strong>\n\n1. La kipá como identidad, no solo como temor. Hoy, la kipá se ha convertido en un símbolo de identidad judía, no solo de temor a Dios. Es una señal visible de pertenencia al pueblo.\n\n2. La kipá y la modernidad. En sociedades laicas, llevar kipá puede ser un acto de valentía o de marginalización. ¿La kipá es una obligación o una opción?\n\n3. La evolución del símbolo. La kipá ha evolucionado: desde la pequeña kipá de tela hasta la kipá de terciopelo o crochet. Cada comunidad tiene su estilo, pero el significado sigue siendo el mismo: recordar que hay un ojo que ve y un oído que oye.",
    conclusion: "La kipá no es una ley bíblica, sino una costumbre que ha sido adoptada como identidad judía. Su propósito es recordarnos que vivimos en presencia de Dios.\n\nEl principio evolutivo es: la kipá es un recordatorio visual de la presencia divina. No es una obligación rígida, sino una práctica espiritual que nos conecta con lo sagrado.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 144,
    category: "halaja",
    hebTitle: "מצה ללא גלוטן",
    latTitle: "Matzá LeLo Gluten",
    title: "Matzá sin Gluten: ¿Sigue siendo Matzá?",
    ref: "Shulján Aruj, Oraj Jaim 453; Mishná Berurá 453",
    hebrewText: "וּמַצּוֹת",
    translation: "\"Y matzot\" (Éxodo 12:39)",
    analysis: "La Torá ordena comer <em>matzá</em> (pan sin levadura) en Pesaj (Éxodo 12:15). El Shulján Aruj (Oraj Jaim 453) establece que la <em>matzá</em> debe ser de uno de los cinco granos (trigo, cebada, espelta, centeno, avena).\n\n<strong>Pero ¿cuál es el problema hoy?</strong>\n\n1. Las personas celíacas no pueden comer trigo. Para los celíacos, la <em>matzá</em> de trigo es peligrosa. ¿Cómo pueden cumplir con la mitzvá?\n\n2. La <em>matzá</em> sin gluten existe. Hoy, hay <em>matzá</em> de harina de arroz, harina de patata y otras harinas sin gluten. Pero ¿cumple con la halajá?\n\n3. El principio de \"aflicción\" y \"pan de la aflicción\". La <em>matzá</em> se llama \"pan de la aflicción\" (Deuteronomio 16:3). La intención es recordar la prisa de la salida de Egipto y la vida de opresión. No es un problema de trigo, sino de conciencia.",
    conclusion: "La <em>matzá</em> sin gluten no es <em>matzá</em> en el sentido halájico tradicional, pero el propósito de la <em>matzá</em> (recordar la salida de Egipto) puede cumplirse con otros alimentos.\n\nEl principio evolutivo es: la <em>matzá</em> es un símbolo, no un fin en sí mismo. Si una persona no puede comer trigo, el recuerdo de la liberación puede expresarse de otras maneras (una comida especial, un relato de la historia, etc.).",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 145,
    category: "halaja",
    hebTitle: "יין לקידוש",
    latTitle: "Iain LiKidush",
    title: "Vino para Kidush: ¿Seco o Dulce?",
    ref: "Shulján Aruj, Oraj Jaim 272; Mishná Berurá 272",
    hebrewText: "זָכוֹר אֶת-יוֹם הַשַּׁבָּת",
    translation: "\"Recuerda el día del Shabbat\" (Éxodo 20:8)",
    analysis: "El <em>Kidush</em> (bendición sobre el vino) en Shabbat y festividades requiere vino. El Shulján Aruj (Oraj Jaim 272:6) establece que el vino debe ser \"bueno\" y \"de calidad\".\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. El gusto ha cambiado. En la época talmúdica, el vino era principalmente seco. Hoy, muchas personas prefieren vino dulce o semi-seco. ¿El vino dulce es \"vino\" para el <em>Kidush</em>?\n\n2. La calidad no es cuestión de precio. El Shulján Aruj habla de \"vino de calidad\", pero no define precio o tipo. Un vino dulce puede ser de excelente calidad y cumplir con el requisito.\n\n3. La intención de la bendición. El <em>Kidush</em> es una bendición sobre el vino para honrar el Shabbat. El vino es un vehículo para la bendición, no el centro de ella.",
    conclusion: "El vino para el <em>Kidush</em> debe ser vino (producto de la uva), pero no hay una exigencia de tipo específico. El vino dulce es aceptable.\n\nEl principio evolutivo es: la bendición no depende del sabor, sino de la intención. El vino dulce puede ser tan sagrado como el vino seco.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 146,
    category: "halaja",
    hebTitle: "מזוזה בדירות מודרניות",
    latTitle: "Mezuzá BeDirot Moderniot",
    title: "Mezuzá en Edificios Modernos: ¿Dónde se Coloca?",
    ref: "Shulján Aruj, Iore Deá 285",
    hebrewText: "וּכְתַבְתָּם עַל-מְזוּזוֹת",
    translation: "\"Y las escribirás en los postes\" (Deuteronomio 6:9)",
    analysis: "La Torá (Deuteronomio 6:9) ordena colocar una <em>mezuzá</em> en los postes de las puertas. El Shulján Aruj (Iore Deá 285) detalla las leyes de la <em>mezuzá</em>: debe colocarse en el lado derecho de la entrada, inclinada hacia adentro.\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. Las entradas compartidas. En los edificios modernos, la entrada principal es compartida por varios departamentos. ¿Debe tener mezuzá cada puerta o solo la entrada del edificio?\n\n2. La definición de \"casa\". ¿Un departamento es una \"casa\" para la mezuzá? Sí, pero ¿dónde se coloca cuando no hay un \"poste\" visible (puertas de vidrio, estructuras modernas)?\n\n3. El principio de la mezuzá. La mezuzá es un recordatorio de la presencia de Dios en el hogar. Es un símbolo de que la casa es un santuario, un lugar de paz y santidad.",
    conclusion: "La mezuzá en edificios modernos debe colocarse en la entrada de cada departamento, no solo en la entrada del edificio. Si la puerta no tiene un poste visible, el pergamino puede colocarse en el marco de la puerta.\n\nEl principio evolutivo es: la mezuzá es un recordatorio de que el hogar es sagrado. No importa el tipo de puerta, el símbolo debe estar presente.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 147,
    category: "halaja",
    hebTitle: "תהילים ובריאות הנפש",
    latTitle: "Tehilim UVriut HaNefesh",
    title: "Tehilim y Salud Mental: Los Salmos como Terapia del Alma",
    ref: "Tehilim (Salmos) varios",
    hebrewText: "שִׁירוּ לַיהוָה",
    translation: "\"Cantad a Adonai\" (Salmos 96:1)",
    analysis: "Los Salmos (<em>Tehilim</em>) son una colección de oraciones y poemas atribuidos al Rey David. Se recitan tradicionalmente en momentos de alegría, de dolor y de necesidad. Muchos los usan como una forma de oración y conexión con Dios.\n\n<strong>Pero ¿qué ha cambiado?</strong>\n\n1. La salud mental es un tema importante. Hoy, la psicología y la salud mental son áreas centrales de la vida moderna. Los Salmos ofrecen una herramienta para el bienestar emocional.\n\n2. La oración como terapia. La recitación de Salmos puede ser una forma de terapia espiritual: expresar emociones, encontrar consuelo en las palabras de David, y conectarse con lo trascendente.\n\n3. El uso de Salmos para la ansiedad. Muchas personas recitan Salmos 23 (\"El Señor es mi pastor\") o Salmos 121 (\"Alzo mis ojos a los montes\") para calmar la ansiedad y encontrar paz.",
    conclusion: "Los Salmos no son solo un texto litúrgico, sino también una herramienta de sanación emocional. La tradición reconoce su poder para calmar el alma y conectar con Dios.\n\nEl principio evolutivo es: la palabra de Dios es medicina para el alma. Los Salmos son una forma de oración que puede usarse para encontrar paz en tiempos de ansiedad y sufrimiento.",
    signature: "— Moré Imanuel ben Efraim",
  },
]
