import type { Tarjeta } from './tarjetasTypes'
export const TARJETAS_PARASHA: Tarjeta[] = [
  {
    id: 1,
    category: "parasha",
    hebTitle: "פרשת בראשית",
    latTitle: "Parashat Bereshit",
    title: "Bereshit",
    ref: "Génesis 1:1–6:8",
    hebrewText: "בְּרֵאשִׁית בָּרָא אֱלֹהִים",
    translation: "\"En el principio creó Dios\"",
    analysis: "La Torá comienza con la letra <em>bet</em> (ב), la segunda del alfabeto. No con la primera, <em>alef</em> (א), que simboliza la unidad divina. Dios eligió comenzar con la <strong>dualidad</strong> porque la creación solo puede sostenerse en la relación: cielo y tierra, luz y oscuridad, hombre y mujer. El principio no es el uno, sino el <strong>encuentro</strong>.",
    conclusion: "El mundo no comenzó con un punto, sino con un abrazo entre opuestos.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 2,
    category: "parasha",
    hebTitle: "פרשת נח",
    latTitle: "Parashat Noaj",
    title: "Noaj",
    ref: "Génesis 6:9–11:32",
    hebrewText: "אִישׁ צַדִּיק תָּמִים הָיָה",
    translation: "\"Era un hombre justo y perfecto en sus generaciones\"",
    analysis: "Noaj es llamado <em>tzadik</em> (justo) en su generación. No fue el más grande de los profetas, sino aquel que <strong>caminó con Dios</strong> en medio de una humanidad corrupta. El arca no fue un barco de salvación solo para él, sino un <strong>útero flotante</strong> para la vida futura.",
    conclusion: "No necesitas cambiar el mundo entero. Solo necesitas construir un arca para lo que amas.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 3,
    category: "parasha",
    hebTitle: "פרשת לך לך",
    latTitle: "Parashat Lej Lejá",
    title: "Lej Lejá",
    ref: "Génesis 12:1–17:27",
    hebrewText: "לֶךְ-לְךָ מֵאַרְצְךָ",
    translation: "\"Vete de tu tierra\"",
    analysis: "La primera orden a Avraham es <em>lej lejá</em> — \"vete para ti\". No es una huida, sino un <strong>viaje hacia la propia identidad</strong>. La bendición divina no es un destino geográfico, sino una <strong>promesa de ser bendición</strong>.",
    conclusion: "El verdadero viaje no es hacia afuera, sino hacia aquello que eres llamado a ser.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 4,
    category: "parasha",
    hebTitle: "פרשת וירא",
    latTitle: "Parashat Vayerá",
    title: "Vayerá",
    ref: "Génesis 18:1–22:24",
    hebrewText: "וַיֵּרָא אֵלָיו יְהוָה",
    translation: "\"Y se le apareció Adonai\"",
    analysis: "Dios se aparece a Avraham mientras él está convaleciente. Pero Avraham <strong>interrumpe la presencia divina</strong> para atender a tres viajeros. La Torá enseña que <strong>recibir huéspedes es más importante que recibir a la Shejiná</strong>.",
    conclusion: "La visita de Dios no se recibe en soledad: se recibe en la hospitalidad.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 5,
    category: "parasha",
    hebTitle: "פרשת חיי שרה",
    latTitle: "Parashat Jayei Sará",
    title: "Jayei Sará",
    ref: "Génesis 23:1–25:18",
    hebrewText: "וַיִּהְיוּ חַיֵּי שָׂרָה",
    translation: "\"Y fueron los años de la vida de Sara\"",
    analysis: "La parashá comienza con la muerte de Sara y termina con la muerte de Avraham. Entre ambas, <strong>la vida</strong>. El texto no narra la muerte como final, sino como <strong>transición</strong>.",
    conclusion: "A veces la primera posesión de una promesa es una tumba. Pero la vida sigue.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 6,
    category: "parasha",
    hebTitle: "פרשת תולדות",
    latTitle: "Parashat Toledot",
    title: "Toledot",
    ref: "Génesis 25:19–28:9",
    hebrewText: "וְאֵלֶּה תּוֹלְדֹת יִצְחָק",
    translation: "\"Y estas son las generaciones de Itzjak\"",
    analysis: "Itzjak es el único patriarca que no sale de la Tierra Prometida. Su vida es <strong>vertical</strong>: no viaja, <strong>cava pozos</strong>. Él no conquista nuevos territorios, sino que <strong>redescubre</strong> los pozos que su padre cavó.",
    conclusion: "La tradición no es un museo: es un pozo que debe ser cavado por cada generación.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 7,
    category: "parasha",
    hebTitle: "פרשת ויצא",
    latTitle: "Parashat Vayetze",
    title: "Vayetze",
    ref: "Génesis 28:10–32:3",
    hebrewText: "וַיֵּצֵא יַעֲקֹב",
    translation: "\"Y salió Iaakov\"",
    analysis: "Iaakov sale de Beer Sheva hacia Jarán. En el camino, <strong>duerme con piedras como almohada</strong> y sueña con una escalera. El exilio no es solo geográfico: es espiritual. Pero donde sea que Iaakov esté, <strong>Dios está presente</strong>.",
    conclusion: "El exilio no es ausencia de Dios: es el lugar donde la escalera se hace visible.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 8,
    category: "parasha",
    hebTitle: "פרשת וישלח",
    latTitle: "Parashat Vayishlaj",
    title: "Vayishlaj",
    ref: "Génesis 32:4–36:43",
    hebrewText: "וַיִּשְׁלַח יַעֲקֹב מַלְאָכִים",
    translation: "\"Y envió Iaakov mensajeros\"",
    analysis: "Iaakov se prepara para enfrentar a Esav. Envía mensajeros, hace regalos, divide su campamento. Pero antes del encuentro, <strong>lucha con un ángel</strong> y recibe el nombre <em>Israel</em> — \"el que lucha con Dios\".",
    conclusion: "No temas luchar con lo que te supera. De esa lucha nace tu nombre verdadero.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 9,
    category: "parasha",
    hebTitle: "פרשת וישב",
    latTitle: "Parashat Vayeshev",
    title: "Vayeshev",
    ref: "Génesis 37:1–40:23",
    hebrewText: "וַיֵּשֶׁב יַעֲקֹב",
    translation: "\"Y habitó Iaakov\"",
    analysis: "Iaakov quiere <strong>descansar</strong> en paz, pero la historia no lo permite. Iosef es vendido por sus hermanos, y el sueño del padre se rompe. La parashá enseña que <strong>el descanso es una ilusión</strong> cuando los sueños no se comparten.",
    conclusion: "El descanso no se encuentra en la estabilidad, sino en la reconciliación de los sueños.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 10,
    category: "parasha",
    hebTitle: "פרשת מקץ",
    latTitle: "Parashat Miketz",
    title: "Miketz",
    ref: "Génesis 41:1–44:17",
    hebrewText: "וַיְהִי מִקֵּץ",
    translation: "\"Y sucedió al cabo de\"",
    analysis: "Iosef pasa dos años más en prisión antes de que el faraón sueñe. La palabra <em>miketz</em> (\"al cabo de\") indica que el <strong>tiempo de espera ha terminado</strong>. Iosef no solo interpreta sueños: <strong>gestiona la abundancia y la escasez</strong>.",
    conclusion: "Los sueños no son para admirarlos: son para construir silos antes de la hambruna.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 11,
    category: "parasha",
    hebTitle: "פרשת ויגש",
    latTitle: "Parashat Vayigash",
    title: "Vayigash",
    ref: "Génesis 44:18–47:27",
    hebrewText: "וַיִּגַּשׁ אֵלָיו יְהוּדָה",
    translation: "\"Y se acercó a él Iehudá\"",
    analysis: "Iehudá se acerca a Iosef para ofrecerse como esclavo a cambio de Biniamín. Este <strong>acercamiento</strong> (vayigash) es el momento de <strong>reconciliación</strong>. La familia se reconstruye cuando alguien está dispuesto a <strong>perderlo todo</strong> por el otro.",
    conclusion: "La reconciliación no llega con discursos: llega cuando alguien se ofrece a sí mismo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 12,
    category: "parasha",
    hebTitle: "פרשת ויחי",
    latTitle: "Parashat Vayejí",
    title: "Vayejí",
    ref: "Génesis 47:28–50:26",
    hebrewText: "וַיְחִי יַעֲקֹב",
    translation: "\"Y vivió Iaakov\"",
    analysis: "Iaakov vive 17 años en Egipto, pero su corazón está en la Tierra Prometida. Antes de morir, <strong>bendice a sus hijos</strong> y les revela su futuro. La bendición no es un deseo: es una <strong>visión profética</strong>.",
    conclusion: "Vivir no es acumular años: es bendecir antes de partir.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 13,
    category: "parasha",
    hebTitle: "פרשת שמות",
    latTitle: "Parashat Shemot",
    title: "Shemot",
    ref: "Éxodo 1:1–6:1",
    hebrewText: "וְאֵלֶּה שְׁמוֹת",
    translation: "\"Y estos son los nombres\"",
    analysis: "La parashá comienza con los <strong>nombres</strong> de los hijos de Israel y termina con el <strong>nombre</strong> de Dios revelado a Moshé. Los nombres no son etiquetas: son <strong>identidad</strong>. Dios no se revela como \"el que es\", sino como <em>Ehieh Asher Ehieh</em>.",
    conclusion: "La liberación comienza cuando un nombre es recordado y pronunciado.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 14,
    category: "parasha",
    hebTitle: "פרשת וארא",
    latTitle: "Parashat Vaerá",
    title: "Vaerá",
    ref: "Éxodo 6:2–9:35",
    hebrewText: "וָאֵרָא אֶל-אַבְרָהָם",
    translation: "\"Y me aparecí a Avraham\"",
    analysis: "Dios se presenta a Moshé con un nombre que los patriarcas no conocieron. Las plagas no son castigos: son <strong>señales</strong> que desmontan la cosmovisión egipcia. Cada plaga es un <strong>golpe a un dios</strong> del panteón egipcio.",
    conclusion: "Para salir de Egipto, primero hay que desmontar sus dioses.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 15,
    category: "parasha",
    hebTitle: "פרשת בא",
    latTitle: "Parashat Bo",
    title: "Bo",
    ref: "Éxodo 10:1–13:16",
    hebrewText: "בֹּא אֶל-פַּרְעֹה",
    translation: "\"Ven a Faraón\"",
    analysis: "La palabra <em>bo</em> (\"ven\") es la última invitación antes del punto de no retorno. La plaga de las tinieblas es la <strong>oscuridad que se siente</strong>. La sangre en los dinteles es la <strong>marca de la fe</strong>.",
    conclusion: "La redención no espera: se toma en la oscuridad de la noche.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 16,
    category: "parasha",
    hebTitle: "פרשת בשלח",
    latTitle: "Parashat Beshalaj",
    title: "Beshalaj",
    ref: "Éxodo 13:17–17:16",
    hebrewText: "וַיְהִי בְּשַׁלַּח פַּרְעֹה",
    translation: "\"Y sucedió que cuando Faraón dejó ir\"",
    analysis: "El Mar Rojo se abre, el pueblo cruza y los egipcios perecen. Pero la libertad no es solo <strong>salir de Egipto</strong>: es <strong>entrar en el desierto</strong>. El maná cae del cielo, pero el pueblo <strong>prueba y se queja</strong>.",
    conclusion: "Salir de Egipto es fácil. Aprender a confiar en el desierto es el verdadero desafío.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 17,
    category: "parasha",
    hebTitle: "פרשת יתרו",
    latTitle: "Parashat Itró",
    title: "Itró",
    ref: "Éxodo 18:1–20:23",
    hebrewText: "וַיִּשְׁמַע יִתְרוֹ",
    translation: "\"Y oyó Itró\"",
    analysis: "Itró, un sacerdote madianita, <strong>oye</strong> lo que Dios hizo por Israel y viene a reconocer al Dios de Moshé. La Torá se entrega en el Sinaí, pero antes, un <strong>extranjero enseña a Moshé a delegar</strong>.",
    conclusion: "La sabiduría puede venir de donde menos se espera. La Torá lo reconoce.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 18,
    category: "parasha",
    hebTitle: "פרשת משפטים",
    latTitle: "Parashat Mishpatim",
    title: "Mishpatim",
    ref: "Éxodo 21:1–24:18",
    hebrewText: "וְאֵלֶּה הַמִּשְׁפָּטִים",
    translation: "\"Y estas son las normas\"",
    analysis: "Después de la revelación en el Sinaí, vienen los <strong>mishpatim</strong> (leyes civiles). No son una caída de lo espiritual a lo mundano: son la <strong>aplicación de la justicia divina</strong> en la vida cotidiana.",
    conclusion: "La justicia social no es un agregado: es el núcleo de la Torá.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 19,
    category: "parasha",
    hebTitle: "פרשת תרומה",
    latTitle: "Parashat Terumá",
    title: "Terumá",
    ref: "Éxodo 25:1–27:19",
    hebrewText: "וְיִקְחוּ-לִי תְּרוּמָה",
    translation: "\"Y tomarán para mí una ofrenda\"",
    analysis: "Dios pide una <em>terumá</em> (ofrenda elevada) de todo corazón generoso. El Mishkán (Tabernáculo) no es un templo de piedra, sino un <strong>espacio portátil</strong> donde Dios habita entre el pueblo.",
    conclusion: "El hogar de Dios se construye con corazones generosos, no con piedras eternas.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 20,
    category: "parasha",
    hebTitle: "פרשת תצוה",
    latTitle: "Parashat Tetzavé",
    title: "Tetzavé",
    ref: "Éxodo 27:20–30:10",
    hebrewText: "וְאַתָּה תְּצַוֶּה",
    translation: "\"Y tú ordenarás\"",
    analysis: "El <em>ner tamid</em> (luz perpetua) debe arder continuamente. El aceite de oliva puro es la <strong>luz que nunca se apaga</strong>. Las vestiduras del sumo sacerdote llevan los nombres de las tribus sobre el corazón.",
    conclusion: "El liderazgo no es brillar: es asegurar que la luz nunca se apague.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 21,
    category: "parasha",
    hebTitle: "פרשת כי תשא",
    latTitle: "Parashat Ki Tisá",
    title: "Ki Tisá",
    ref: "Éxodo 30:11–34:35",
    hebrewText: "כִּי תִשָּׂא",
    translation: "\"Cuando eleves\"",
    analysis: "El censo se hace con <em>mitad de shekel</em>—todos iguales ante el recuento. Pero el pueblo <strong>construye el becerro de oro</strong> mientras Moshé está en la cumbre. La ruptura es profunda, pero <strong>Moshé intercede</strong> y recibe las segundas tablas.",
    conclusion: "El perdón no borra el error: revela la paciencia divina.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 22,
    category: "parasha",
    hebTitle: "פרשת ויקהל",
    latTitle: "Parashat Vayakhel",
    title: "Vayakhel",
    ref: "Éxodo 35:1–38:20",
    hebrewText: "וַיַּקְהֵל מֹשֶׁה",
    translation: "\"Y congregó Moshé\"",
    analysis: "Moshé <strong>congrega</strong> a todo el pueblo para construir el Mishkán. La asamblea no es para castigar, sino para <strong>invitar a la participación</strong>. Todos contribuyen, cada uno con su talento.",
    conclusion: "Lo sagrado se construye con manos de todos, no con la soledad de uno solo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 23,
    category: "parasha",
    hebTitle: "פרשת פקודי",
    latTitle: "Parashat Pekudei",
    title: "Pekudei",
    ref: "Éxodo 38:21–40:38",
    hebrewText: "אֵלֶּה פְקוּדֵי",
    translation: "\"Estos son los recuentos\"",
    analysis: "La parashá termina con la <strong>cuenta final</strong> del Mishkán y su <strong>inauguración</strong>. La nube cubre la Tienda de Reunión y la gloria de Dios la llena. El libro de Éxodo cierra con el <strong>éxito de la construcción</strong>.",
    conclusion: "Cuando el pueblo construye con generosidad, la gloria divina lo habita.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 24,
    category: "parasha",
    hebTitle: "פרשת ויקרא",
    latTitle: "Parashat Vayikrá",
    title: "Vayikrá",
    ref: "Levítico 1:1–5:26",
    hebrewText: "וַיִּקְרָא אֶל-מֹשֶׁה",
    translation: "\"Y llamó a Moshé\"",
    analysis: "Dios <strong>llama</strong> a Moshé desde la Tienda de Reunión. El libro de Vayikrá comienza con los <strong>sacrificios</strong>. La palabra <em>korban</em> (ofrenda) viene de <em>karav</em> (acercarse). El sacrificio es el <strong>puente entre el corazón y lo alto</strong>.",
    conclusion: "No ofrecemos para darle a Dios: ofrecemos para acercarnos a Él.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 25,
    category: "parasha",
    hebTitle: "פרשת צו",
    latTitle: "Parashat Tzav",
    title: "Tzav",
    ref: "Levítico 6:1–8:36",
    hebrewText: "צַו אֶת-אַהֲרֹן",
    translation: "\"Ordena a Aarón\"",
    analysis: "Dios <strong>ordena</strong> a Aarón y a sus hijos sobre los sacrificios. El fuego en el altar debe <strong>mantenerse encendido</strong> continuamente. La orden no es una obligación vacía: es una <strong>invitación al servicio constante</strong>.",
    conclusion: "La llama que nunca se apaga es el servicio que nunca termina.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 26,
    category: "parasha",
    hebTitle: "פרשת שמיני",
    latTitle: "Parashat Sheminí",
    title: "Sheminí",
    ref: "Levítico 9:1–11:47",
    hebrewText: "וַיְהִי בַּיּוֹם הַשְּׁמִינִי",
    translation: "\"Y sucedió en el octavo día\"",
    analysis: "El <strong>octavo día</strong> es el día de la <strong>consagración</strong> del Mishkán. Pero la alegría se quiebra con la muerte de Nadav y Avihú, que ofrecen <em>esh zará</em> (fuego extraño). La santidad exige <strong>distinción y límites</strong>.",
    conclusion: "La santidad requiere cercanía, pero también límites.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 27,
    category: "parasha",
    hebTitle: "פרשת תזריע",
    latTitle: "Parashat Tazría",
    title: "Tazría",
    ref: "Levítico 12:1–13:59",
    hebrewText: "אִשָּׁה כִּי תַזְרִיעַ",
    translation: "\"Cuando una mujer conciba\"",
    analysis: "La parashá trata sobre el <strong>parto</strong> y las <strong>enfermedades de la piel</strong>. La pureza e impureza no son morales: son <strong>estados espirituales</strong> que marcan la vida comunitaria. El cuerpo humano es un <strong>campo de expresión de lo sagrado</strong>.",
    conclusion: "El cuerpo no es un obstáculo para la santidad: es su vehículo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 28,
    category: "parasha",
    hebTitle: "פרשת מצורע",
    latTitle: "Parashat Metzorá",
    title: "Metzorá",
    ref: "Levítico 14:1–15:33",
    hebrewText: "וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה",
    translation: "\"Y habló Adonai a Moshé\"",
    analysis: "La parashá continúa con las leyes de la <strong>impureza</strong> y el <strong>proceso de purificación</strong>. El <em>metzorá</em> no es solo una persona enferma: es aquel que ha sido <strong>separado de la comunidad</strong>.",
    conclusion: "La purificación no es instantánea: es un camino de retorno.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 29,
    category: "parasha",
    hebTitle: "פרשת אחרי מות",
    latTitle: "Parashat Ajaré Mot",
    title: "Ajaré Mot",
    ref: "Levítico 16:1–18:30",
    hebrewText: "אַחֲרֵי מוֹת",
    translation: "\"Después de la muerte\"",
    analysis: "La parashá comienza con la muerte de los hijos de Aarón y describe el <strong>servicio de Iom Kipur</strong>. El sumo sacerdote entra en el <strong>Santo de los Santos</strong> una vez al año. La expiación es un <strong>ritual anual</strong> de renovación.",
    conclusion: "La cercanía a Dios no es un derecho: es un servicio renovado cada año.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 30,
    category: "parasha",
    hebTitle: "פרשת קדושים",
    latTitle: "Parashat Kedoshim",
    title: "Kedoshim",
    ref: "Levítico 19:1–20:27",
    hebrewText: "קְדֹשִׁים תִּהְיוּ",
    translation: "\"Santos seréis\"",
    analysis: "El llamado a la santidad comienza con <em>kedoshim tihiyú</em>. La santidad no es una abstracción: es <strong>amor al prójimo, honestidad en el comercio, respeto por el anciano</strong>. Lo sagrado se construye en lo <strong>cotidiano</strong>.",
    conclusion: "La santidad no es un estado: es una práctica diaria.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 31,
    category: "parasha",
    hebTitle: "פרשת אמור",
    latTitle: "Parashat Emor",
    title: "Emor",
    ref: "Levítico 21:1–24:23",
    hebrewText: "וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה",
    translation: "\"Y dijo Adonai a Moshé\"",
    analysis: "El texto detalla las leyes para los <strong>sacerdotes</strong>, las <strong>festividades</strong> y el <strong>pan del rostro</strong>. Las festividades no son días de descanso vacíos: son <strong>momentos sagrados</strong> que marcan el tiempo del pueblo.",
    conclusion: "El tiempo no es vacío: es un pergamino que escribimos con cada festividad.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 32,
    category: "parasha",
    hebTitle: "פרשת בהר",
    latTitle: "Parashat Behar",
    title: "Behar",
    ref: "Levítico 25:1–26:2",
    hebrewText: "בְּהַר סִינַי",
    translation: "\"En el monte Sinaí\"",
    analysis: "El <em>Shmitá</em> (año sabático) y el <em>Yovel</em> (jubileo) son leyes de <strong>descanso de la tierra</strong> y <strong>retorno de la propiedad</strong>. La tierra no es del hombre: es de Dios. La libertad del esclavo y la devolución de la tierra son <strong>economía de la justicia</strong>.",
    conclusion: "La tierra descansa para que la justicia pueda caminar.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 33,
    category: "parasha",
    hebTitle: "פרשת בחוקותי",
    latTitle: "Parashat Bejukotai",
    title: "Bejukotai",
    ref: "Levítico 26:3–27:34",
    hebrewText: "אִם-בְּחֻקֹּתַי",
    translation: "\"Si en mis estatutos\"",
    analysis: "La parashá cierra con las <strong>bendiciones por la obediencia</strong> y las <strong>maldiciones por la desobediencia</strong>. No es un sistema de recompensa y castigo: es una <strong>consecuencia lógica</strong> de la relación con Dios.",
    conclusion: "El final del libro no es un cierre: es una promesa de retorno.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 34,
    category: "parasha",
    hebTitle: "פרשת במדבר",
    latTitle: "Parashat Bamidbar",
    title: "Bamidbar",
    ref: "Números 1:1–4:20",
    hebrewText: "וַיְדַבֵּר יְהוָה בְּמִדְבַּר",
    translation: "\"Y habló Adonai en el desierto\"",
    analysis: "Dios habla en el <strong>desierto</strong>, no en la tierra prometida. El censo no es un inventario militar: es una <strong>organización de la presencia</strong> divina en medio del pueblo. El desierto es el lugar de la <strong>dependencia y la organización</strong>.",
    conclusion: "El desierto no es vacío: es el lugar donde Dios cuenta a su pueblo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 35,
    category: "parasha",
    hebTitle: "פרשת נשא",
    latTitle: "Parashat Nasó",
    title: "Nasó",
    ref: "Números 4:21–7:89",
    hebrewText: "נָשֹׂא",
    translation: "\"Levanta\"",
    analysis: "La parashá trata sobre los <strong>levitas</strong> y el <strong>servicio del Mishkán</strong>, la <strong>sotá</strong> y el <strong>voto de nazir</strong>. La bendición sacerdotal — <em>yevarejeja Adonai</em> — es el <strong>centro espiritual</strong> del texto.",
    conclusion: "La bendición no es una fórmula: es una elevación del alma.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 36,
    category: "parasha",
    hebTitle: "פרשת בהעלותך",
    latTitle: "Parashat Behaalotjá",
    title: "Behaalotjá",
    ref: "Números 8:1–12:16",
    hebrewText: "בְּהַעֲלֹתְךָ",
    translation: "\"Cuando enciendas\"",
    analysis: "La parashá comienza con el <strong>encendido de la menorá</strong> y termina con la <strong>queja del pueblo</strong> por la carne. La luz de la menorá ilumina el camino, pero la <strong>ingratitud</strong> oscurece el alma.",
    conclusion: "La luz se enciende, pero la queja la apaga.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 37,
    category: "parasha",
    hebTitle: "פרשת שלח",
    latTitle: "Parashat Shlaj Lejá",
    title: "Shlaj Lejá",
    ref: "Números 13:1–15:41",
    hebrewText: "שְׁלַח-לְךָ",
    translation: "\"Envía para ti\"",
    analysis: "Los <strong>espías</strong> son enviados a explorar la tierra. Diez traen un informe negativo, solo Iehoshúa y Caleb confían en la promesa. La parashá enseña que <strong>la percepción determina la realidad</strong>.",
    conclusion: "No es la tierra lo que tememos: es nuestra propia mirada.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 38,
    category: "parasha",
    hebTitle: "פרשת קרח",
    latTitle: "Parashat Koraj",
    title: "Koraj",
    ref: "Números 16:1–18:32",
    hebrewText: "וַיִּקַּח קֹרַח",
    translation: "\"Y tomó Koraj\"",
    analysis: "Koraj lidera una rebelión contra Moshé y Aarón. La <strong>autoridad</strong> de Moshé es cuestionada, pero la tierra <strong>abre su boca</strong> y traga a los rebeldes. La parashá advierte contra la <strong>ambición desmedida</strong>.",
    conclusion: "La rebelión no es contra el líder: es contra el orden divino.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 39,
    category: "parasha",
    hebTitle: "פרשת חקת",
    latTitle: "Parashat Jukat",
    title: "Jukat",
    ref: "Números 19:1–22:1",
    hebrewText: "זֹאת חֻקַּת",
    translation: "\"Esta es la ley\"",
    analysis: "La <em>pará adumá</em> (vaca roja) es un <strong>misterio</strong> que purifica la impureza de la muerte. Moshé golpea la roca en lugar de hablarle, y el <strong>agua fluye</strong>, pero él pierde la entrada a la tierra.",
    conclusion: "El misterio purifica, pero la obediencia decide el destino.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 40,
    category: "parasha",
    hebTitle: "פרשת בלק",
    latTitle: "Parashat Balak",
    title: "Balak",
    ref: "Números 22:2–25:9",
    hebrewText: "וַיַּרְא בָּלָק",
    translation: "\"Y vio Balak\"",
    analysis: "Balak, rey de Moav, contrata a Bilam para maldecir a Israel. Pero Bilam solo puede <strong>bendecir</strong>. El texto es una <strong>ironía divina</strong>: el enemigo que viene a maldecir termina profetizando la gloria de Israel.",
    conclusion: "El que viene a maldecir se convierte en profeta de bendición.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 41,
    category: "parasha",
    hebTitle: "פרשת פינחס",
    latTitle: "Parashat Pinjás",
    title: "Pinjás",
    ref: "Números 25:10–30:1",
    hebrewText: "פִּינְחָס",
    translation: "\"Pinjás\"",
    analysis: "Pinjás actúa con <strong>celo</strong> y detiene la plaga. Su acción le otorga el <strong>pacto de paz</strong> y el <strong>sacerdocio eterno</strong>. El celo no es violencia: es <strong>compromiso radical</strong> con la santidad.",
    conclusion: "El celo por la santidad puede ser el camino hacia la paz.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 42,
    category: "parasha",
    hebTitle: "פרשת מטות",
    latTitle: "Parashat Matot",
    title: "Matot",
    ref: "Números 30:2–32:42",
    hebrewText: "מַטּוֹת",
    translation: "\"Tribus\"",
    analysis: "La parashá trata sobre los <strong>votos</strong> y la <strong>guerra contra Madián</strong>. El voto es una <strong>palabra que ata</strong>; la guerra es una <strong>decisión colectiva</strong>. La tierra se conquista con <strong>palabras y acciones</strong> compartidas.",
    conclusion: "La conquista de la tierra comienza con el cumplimiento de la palabra.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 43,
    category: "parasha",
    hebTitle: "פרשת מסעי",
    latTitle: "Parashat Masei",
    title: "Masei",
    ref: "Números 33:1–36:13",
    hebrewText: "מַסְעֵי",
    translation: "\"Etapas\"",
    analysis: "La parashá recorre las <strong>42 etapas</strong> del viaje de Israel por el desierto. Cada etapa es un <strong>lugar de aprendizaje</strong>, no solo geográfico. Las ciudades de refugio son un <strong>recordatorio</strong> de que la justicia debe ser accesible.",
    conclusion: "Cada etapa del viaje es un paso en el camino de la vida.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 44,
    category: "parasha",
    hebTitle: "פרשת דברים",
    latTitle: "Parashat Devarim",
    title: "Devarim",
    ref: "Deuteronomio 1:1–3:22",
    hebrewText: "אֵלֶּה הַדְּבָרִים",
    translation: "\"Estas son las palabras\"",
    analysis: "Moshé comienza su <strong>discurso de despedida</strong> recordando el viaje desde el Sinaí. Las palabras de Moshé son <strong>repetición y reinterpretación</strong>. No es un simple recuerdo: es una <strong>relectura</strong> de la historia.",
    conclusion: "La palabra de Moshé no es un recuerdo: es una renovación.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 45,
    category: "parasha",
    hebTitle: "פרשת ואתחנן",
    latTitle: "Parashat Vaetjanán",
    title: "Vaetjanán",
    ref: "Deuteronomio 3:23–7:11",
    hebrewText: "וָאֶתְחַנַּן",
    translation: "\"Y supliqué\"",
    analysis: "Moshé <strong>suplica</strong> entrar a la tierra, pero Dios le niega. La oración de Moshé es el modelo de la <strong>oración sincera</strong> que no es escuchada. El <em>Shemá Israel</em> es el <strong>corazón de la fe</strong>.",
    conclusion: "El que no entra a la tierra, entrega la Torá para que otros entren.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 46,
    category: "parasha",
    hebTitle: "פרשת עקב",
    latTitle: "Parashat Eikev",
    title: "Eikev",
    ref: "Deuteronomio 7:12–11:25",
    hebrewText: "וְהָיָה עֵקֶב",
    translation: "\"Y será, por causa del talón\"",
    analysis: "<em>Eikev</em> deriva de <em>akev</em> (talón). Las mitzvot que el hombre \"pisa\" con su talón —las que considera menores— son las que sostienen el mundo. La <strong>grandeza</strong> se construye con <strong>fidelidades diminutas</strong>.",
    conclusion: "Lo que el mundo pisa como polvo sostiene las estrellas.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 47,
    category: "parasha",
    hebTitle: "פרשת ראה",
    latTitle: "Parashat Re'é",
    title: "Re'é",
    ref: "Deuteronomio 11:26–16:17",
    hebrewText: "רְאֵה אָנֹכִי",
    translation: "\"Mira, yo pongo\"",
    analysis: "Moshé pone delante del pueblo la <strong>bendición y la maldición</strong>. La elección es <strong>libre y consciente</strong>. La parashá contiene las leyes del <strong>diezmo</strong>, el <strong>año sabático</strong> y las <strong>festividades de peregrinación</strong>.",
    conclusion: "Ver es elegir. No ver es perderse.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 48,
    category: "parasha",
    hebTitle: "פרשת שופטים",
    latTitle: "Parashat Shoftim",
    title: "Shoftim",
    ref: "Deuteronomio 16:18–21:9",
    hebrewText: "שֹׁפְטִים",
    translation: "\"Jueces\"",
    analysis: "La justicia es el <strong>fundamento</strong> de la sociedad. <em>Tzedek, tzedek tirdof</em> — \"justicia, justicia perseguirás\". La repetición no es retórica: es <strong>urgencia</strong>. La <strong>Torá es ley</strong> antes que teología.",
    conclusion: "La justicia no es un ideal: es una persecución constante.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 49,
    category: "parasha",
    hebTitle: "פרשת כי תצא",
    latTitle: "Parashat Ki Tetze",
    title: "Ki Tetze",
    ref: "Deuteronomio 21:10–25:19",
    hebrewText: "כִּי-תֵצֵא",
    translation: "\"Cuando salgas\"",
    analysis: "Las leyes de la guerra y la familia, la <strong>mujer cautiva</strong>, el <strong>hijo rebelde</strong>. La Torá no es solo espiritual: es <strong>ley de vida cotidiana</strong>. La guerra no es glorificada: es <strong>regulada</strong>.",
    conclusion: "La Torá baja a la guerra y al hogar para santificarlo todo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 50,
    category: "parasha",
    hebTitle: "פרשת כי תבוא",
    latTitle: "Parashat Ki Tavó",
    title: "Ki Tavó",
    ref: "Deuteronomio 26:1–29:8",
    hebrewText: "כִּי-תָבוֹא",
    translation: "\"Cuando entres\"",
    analysis: "La parashá describe la <strong>ceremonia de los primeros frutos</strong> y las <strong>bendiciones y maldiciones</strong> en el monte Ebal y Guerizim. La entrada a la tierra es un <strong>acto de gratitud</strong>, no de conquista.",
    conclusion: "Entrar a la tierra es entrar en la gratitud.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 51,
    category: "parasha",
    hebTitle: "פרשת נצבים",
    latTitle: "Parashat Nitzavim",
    title: "Nitzavim",
    ref: "Deuteronomio 29:9–30:20",
    hebrewText: "אַתֶּם נִצָּבִים",
    translation: "\"Estáis firmes\"",
    analysis: "Todo Israel está <strong>de pie</strong> ante Dios para renovar la alianza. La Torá no está en el cielo: está <strong>en la boca y en el corazón</strong> para cumplirla. No es inalcanzable: es <strong>cercana y posible</strong>.",
    conclusion: "La Torá no está en el cielo: está en la boca del que la pronuncia.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 52,
    category: "parasha",
    hebTitle: "פרשת וילך",
    latTitle: "Parashat Vayelej",
    title: "Vayelej",
    ref: "Deuteronomio 31:1–31:30",
    hebrewText: "וַיֵּלֶךְ מֹשֶׁה",
    translation: "\"Y fue Moshé\"",
    analysis: "Moshé <strong>va</strong> hacia su muerte, pero <strong>entrega</strong> la Torá a Iehoshúa y a los levitas. La Torá no es un libro: es un <strong>testimonio vivo</strong> que será leído en cada <em>Hakhel</em>.",
    conclusion: "Moshé se va, pero la palabra queda.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 53,
    category: "parasha",
    hebTitle: "פרשת האזינו",
    latTitle: "Parashat Ha'azinu",
    title: "Ha'azinu",
    ref: "Deuteronomio 32:1–32:52",
    hebrewText: "הַאֲזִינוּ",
    translation: "\"Escuchad\"",
    analysis: "Moshé canta su <strong>último poema</strong>. El cielo y la tierra son testigos. La canción es un <strong>resumen de la historia</strong> de Israel: fidelidad y fracaso, castigo y redención. La historia se recuerda mejor cuando se canta.",
    conclusion: "La historia que no se canta, se olvida.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 54,
    category: "parasha",
    hebTitle: "פרשת וזאת הברכה",
    latTitle: "Parashat Vezot HaBerajá",
    title: "Vezot HaBerajá",
    ref: "Deuteronomio 33:1–34:12",
    hebrewText: "וְזֹאת הַבְּרָכָה",
    translation: "\"Y esta es la bendición\"",
    analysis: "Moshé <strong>bendice</strong> a cada tribu antes de morir. La bendición no es un adiós: es un <strong>legado</strong>. Moshé sube al monte Nebo, ve la tierra y <strong>muere en el beso de Dios</strong>. La Torá termina con la <strong>muerte del profeta</strong> y el <strong>nacimiento de la palabra escrita</strong>.",
    conclusion: "El libro termina con una muerte, pero la palabra sigue viva.",
    signature: "— Moré Imanuel ben Efraim",
  },
]
