import type { Tarjeta } from './tarjetasTypes'
export const TARJETAS_MIDDOT: Tarjeta[] = [
  {
    id: 70,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "El Espejo del Prójimo",
    ref: "Levítico 19:18",
    hebrewText: "וְאָהַבְתָּ לְרֵעֲךָ כָּמוֹךָ",
    translation: "\"Y amarás a tu prójimo como a ti mismo\"",
    analysis: "No se trata de amar al otro <em>desde</em> tu ego, sino de reconocer en él tu propia estructura espiritual. El <em>re'a</em> (רֵעַ, prójimo) comparte raíz con <em>ra'ah</em> (רָאָה, ver): amar al otro es <strong>ver en él tu propio reflejo divino</strong>.",
    conclusion: "No ames al otro porque te convenga: ámalo porque es tu espejo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 71,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "El Tiempo Sagrado",
    ref: "Concepto hebraico",
    hebrewText: "זְמַן",
    translation: "Zeman — Tiempo designado / Tiempo hecho",
    analysis: "En hebreo no existe \"tener tiempo\". Se dice <em>la'asot zeman</em> — \"hacer tiempo\". El tiempo no es un recurso que poseemos; es una dimensión que <strong>co-creamos</strong> con nuestras acciones. El Shabbat no descansa porque sea sábado: es sábado porque alguien decidió santificarlo.",
    conclusion: "No digas \"no tengo tiempo\". Dí: \"aún no he hecho tiempo para esto\".",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 72,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Palabra antes del Acto",
    ref: "Análisis léxico hebreo",
    hebrewText: "דָּבָר",
    translation: "Davar — Palabra / Cosa / Asunto",
    analysis: "En hebreo, \"palabra\" y \"cosa\" son la misma palabra: <em>davar</em>. No hay distinción léxica entre decir y crear. Cuando Dios habla, sucede. Cuando el hombre habla sin intención, descrea. La ética del <em>lashon hara</em> no es puritanismo: es <strong>física espiritual</strong>.",
    conclusion: "Habla como si cada palabra dejara huella en el mundo — porque la deja.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 73,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Justicia como Fundamento",
    ref: "Deuteronomio 16:20",
    hebrewText: "צֶדֶק צֶדֶק תִּרְדֹּף",
    translation: "\"Justicia, justicia perseguirás\"",
    analysis: "La repetición de la palabra <em>tzedek</em> (justicia) no es retórica: es <strong>urgencia</strong>. La justicia no es un estado, sino una <strong>persecución constante</strong>. El ser humano está llamado a <strong>correr tras la justicia</strong> como quien corre para salvar una vida.",
    conclusion: "La justicia no se encuentra: se persigue.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 74,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Honestidad como Santidad",
    ref: "Levítico 19:35",
    hebrewText: "לֹא-תַעֲשׂוּ עָוֶל בַּמִּשְׁפָּט",
    translation: "\"No haréis injusticia en el juicio\"",
    analysis: "La honestidad no es una virtud entre otras: es un <strong>pilar de la santidad</strong>. Medidas justas, pesos exactos y juicios rectos son la <strong>expresión de lo sagrado</strong> en lo cotidiano. La Torá no separa la ética comercial de la vida espiritual.",
    conclusion: "La santidad se mide en la justicia de tus balanzas.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 75,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "El Amor como Mandamiento",
    ref: "Deuteronomio 6:5",
    hebrewText: "וְאָהַבְתָּ אֵת יְהוָה",
    translation: "\"Y amarás a Adonai\"",
    analysis: "El amor no es un sentimiento: es un <strong>mandamiento</strong>. No se puede ordenar sentir, pero se puede ordenar <strong>actuar con amor</strong>. El amor a Dios se demuestra en la <strong>entrega del corazón, el alma y la fuerza</strong> — con todo lo que se es y se tiene.",
    conclusion: "El amor no se siente: se entrega.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 76,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Compasión como Deber",
    ref: "Zacarías 7:9",
    hebrewText: "חֶסֶד וְרַחֲמִים עֲשׂוּ",
    translation: "\"Haced bondad y compasión\"",
    analysis: "La compasión no es un lujo: es un <strong>deber</strong>. No se puede ser justo sin ser compasivo. La justicia sin compasión es dura; la compasión sin justicia es débil. Ambas deben caminar juntas para <strong>construir una sociedad humana</strong>.",
    conclusion: "La compasión no es opcional: es el otro nombre de la justicia.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 77,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Verdad como Escudo",
    ref: "Salmos 15:2",
    hebrewText: "דֹּבֵר אֱמֶת בִּלְבָבוֹ",
    translation: "\"El que habla verdad en su corazón\"",
    analysis: "La verdad no es solo lo que se dice: es lo que se <strong>vive y se siente</strong>. Hablar verdad <strong>desde el corazón</strong> significa que no hay grieta entre la palabra y la intención. La verdad es el <strong>escudo que protege</strong> la integridad del alma.",
    conclusion: "La verdad no se dice: se es.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 78,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Responsabilidad del Líder",
    ref: "Éxodo 18:21",
    hebrewText: "אַנְשֵׁי-חַיִל יִרְאֵי אֱלֹהִים",
    translation: "\"Hombres capaces, temerosos de Dios\"",
    analysis: "El líder no es el que tiene poder: es el que <strong>sirve con integridad</strong>. Los criterios para liderar son: <strong>capacidad, temor de Dios, verdad y desinterés</strong>. El liderazgo es una <strong>responsabilidad sagrada</strong>, no un privilegio personal.",
    conclusion: "El liderazgo no es poder: es responsabilidad.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 79,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Hospitalidad como Virtud",
    ref: "Génesis 18:1-8",
    hebrewText: "וַיִּשָּׂא עֵינָיו וַיַּרְא",
    translation: "\"Y alzó sus ojos y vio\"",
    analysis: "Avraham <strong>vio</strong> a los viajeros y <strong>corrió</strong> a recibirlos. La hospitalidad no es pasiva: es <strong>activa y urgente</strong>. Recibir al otro es <strong>recibir la presencia divina</strong> que viene disfrazada de extranjero. La hospitalidad es la <strong>primera forma de reconocer lo sagrado</strong>.",
    conclusion: "La hospitalidad no es abrir una puerta: es abrir los ojos.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 80,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "El Respeto por el Anciano",
    ref: "Levítico 19:32",
    hebrewText: "מִפְּנֵי שֵׂיבָה תָּקוּם",
    translation: "\"Delante de las canas te levantarás\"",
    analysis: "Levantarse ante el anciano no es un gesto de cortesía: es un <strong>acto de reconocimiento</strong>. La sabiduría no solo se adquiere: se <strong>hereda</strong>. El respeto por el que ha vivido más es el <strong>respeto por el tiempo</strong> y la experiencia que este otorga.",
    conclusion: "El respeto por el anciano es el respeto por el tiempo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 81,
    category: "middot",
    hebTitle: "מידות",
    latTitle: "Middot",
    title: "La Caridad como Justicia",
    ref: "Deuteronomio 15:7-8",
    hebrewText: "פָּתֹחַ תִּפְתַּח אֶת-יָדְךָ",
    translation: "\"Abrirás tu mano\"",
    analysis: "La caridad no es caridad: es <strong>justicia</strong>. El pobre tiene <strong>derecho</strong> a recibir, y el rico <strong>deber</strong> de dar. Abrir la mano no es un gesto de generosidad: es un <strong>acto de restitución</strong> de lo que pertenece a Dios y debe ser compartido.",
    conclusion: "La caridad no es un favor: es una deuda de justicia.",
    signature: "— Moré Imanuel ben Efraim",
  },
]
