import type { Tarjeta } from './tarjetasTypes'
export const TARJETAS_MUSAR: Tarjeta[] = [
  {
    id: 55,
    category: "musar",
    hebTitle: "מוסר השתיקה",
    latTitle: "Musar HaShtiká",
    title: "Ética del Silencio",
    ref: "Mishlé 12:19",
    hebrewText: "שְׂפָתַיִם יִשְׁקֹרוּ, וּלְשׁוֹן תַּעֲשֶׂה אֱמֶת",
    translation: "\"Los labios mentirosos son engaño, pero la lengua que habla verdad permanece para siempre\"",
    analysis: "La <em>lashon</em> (לשון, lengua) y las <em>sefatayim</em> (שפתיים, labios) operan en tensión dialéctica. Mientras los labios pueden tejer engaño momentáneo, la lengua debe alinearse con <em>emet</em> (אמת, verdad), cuyas letras son las primeras, medias y últimas del alfabeto.",
    conclusion: "El silencio que guarda la verdad vale más que el discurso que la diluye.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 56,
    category: "musar",
    hebTitle: "מוסר הכעס",
    latTitle: "Musar HaKa'as",
    title: "La Ira como Maestra",
    ref: "Pirkei Avot 5:11",
    hebrewText: "כָּל הַכּוֹעֵס — כָּל מִינֵי גֵיהִנּוֹם שׁוֹלְטִין בּוֹ",
    translation: "\"Todo el que se enfurece — todo tipo de Gehinnom domina sobre él\"",
    analysis: "El texto no dice \"caer en el Gehinnom\", sino <em>sholtin bo</em> — \"dominan <strong>sobre él</strong>\". La ira no es un destino, sino una soberanía ajena que usurpa el trono del <em>nefesh</em>. El trabajo del <em>musarnik</em> no es suprimir la cólera, sino <strong>restaurar su dominio propio</strong>.",
    conclusion: "Quien enseña a su ira a sentarse, enseña a su alma a gobernar.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 57,
    category: "musar",
    hebTitle: "ענוות משה",
    latTitle: "Anavat Moshé",
    title: "La Humildad de Moshé",
    ref: "Números 12:3",
    hebrewText: "וְהָאִישׁ מֹשֶׁה עָנָיו מְאֹד",
    translation: "\"Y el hombre Moshé era muy humilde\"",
    analysis: "Moshé, el más grande de los profetas, es llamado <em>anav</em> (humilde). La humildad en la Torá no significa pensar menos de uno mismo, sino <strong>pensar en uno mismo menos</strong>. Es la capacidad de ocupar el propio lugar sin necesidad de ocupar el de los demás.",
    conclusion: "La grandeza no se mide por cuánto te elevas, sino por cuánto espacio dejas para que otros se eleven.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 58,
    category: "musar",
    hebTitle: "מוסר הכרת הטוב",
    latTitle: "Musar Hakarat HaTov",
    title: "La Gratitud como Fundamento",
    ref: "Deuteronomio 8:10",
    hebrewText: "וְאָכַלְתָּ וְשָׂבָעְתָּ וּבֵרַכְתָּ",
    translation: "\"Y comerás y te saciarás y bendecirás\"",
    analysis: "La bendición después de comer (<em>birkat hamazón</em>) es el <strong>modelo de gratitud</strong>. No se agradece solo en la abundancia, sino en el <strong>acto cotidiano</strong> de recibir. La gratitud no es un sentimiento: es una <strong>obligación</strong> que transforma la recepción en conciencia.",
    conclusion: "La gratitud no es el final de la comida: es el principio de la conciencia.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 59,
    category: "musar",
    hebTitle: "אורך רוח",
    latTitle: "Orej Ruaj",
    title: "La Paciencia del Creador",
    ref: "Salmos 86:15",
    hebrewText: "וְאַתָּה אֲדֹנָי אֵל רַחוּם וְחַנּוּן",
    translation: "\"Y Tú, Adonai, Dios misericordioso y clemente\"",
    analysis: "La paciencia divina se revela en la <strong>lentitud para la ira</strong> y la <strong>rapidez para la misericordia</strong>. La paciencia no es pasividad: es la <strong>capacidad de sostener</strong> el tiempo del otro sin romperlo. El ser humano está llamado a imitar esta paciencia en sus relaciones.",
    conclusion: "La paciencia no es esperar: es sostener el tiempo del otro.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 60,
    category: "musar",
    hebTitle: "תשובה",
    latTitle: "Teshuvá",
    title: "El Arrepentimiento como Retorno",
    ref: "Deuteronomio 30:2",
    hebrewText: "וְשַׁבְתָּ עַד-יְהוָה",
    translation: "\"Y te volverás a Adonai\"",
    analysis: "La palabra <em>teshuvá</em> (arrepentimiento) significa literalmente <strong>\"retorno\"</strong>. No es un acto de culpa, sino un <strong>movimiento de regreso</strong> al lugar de origen. El arrepentimiento no es un destino: es un <strong>camino</strong> que se recorre con pasos de humildad.",
    conclusion: "No hay distancia que no pueda ser recorrida por un paso de retorno.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 61,
    category: "musar",
    hebTitle: "שמחה בעבודה",
    latTitle: "Simjá BaAvodá",
    title: "La Alegría del Servicio",
    ref: "Salmos 100:2",
    hebrewText: "עִבְדוּ אֶת-יְהוָה בְּשִׂמְחָה",
    translation: "\"Servid a Adonai con alegría\"",
    analysis: "Servir a Dios no es una carga, sino una <strong>fuente de alegría</strong>. La palabra <em>avodá</em> (servicio) comparte raíz con <em>eved</em> (esclavo), pero la alegría transforma la servidumbre en <strong>libertad</strong>. El servicio con alegría es la <strong>expresión más alta</strong> de la libertad humana.",
    conclusion: "La verdadera libertad no es no servir: es servir con alegría.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 62,
    category: "musar",
    hebTitle: "אמונה בחושך",
    latTitle: "Emuná BaJoshej",
    title: "La Fe en la Oscuridad",
    ref: "Habacuc 2:4",
    hebrewText: "וְצַדִּיק בֶּאֱמוּנָתוֹ יִחְיֶה",
    translation: "\"Y el justo por su fe vivirá\"",
    analysis: "La fe no es certeza: es <strong>confianza en la oscuridad</strong>. El justo vive porque <strong>cree</strong> incluso cuando no ve. La fe no es evidencia, sino <strong>la capacidad de caminar</strong> cuando el camino no está iluminado.",
    conclusion: "La fe no es ver: es caminar en la oscuridad con confianza.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 63,
    category: "musar",
    hebTitle: "בטחון",
    latTitle: "Bitajón",
    title: "La Confianza en Dios",
    ref: "Proverbios 3:5-6",
    hebrewText: "בְּטַח אֶל-יְהוָה בְּכָל-לִבֶּךָ",
    translation: "\"Confía en Adonai con todo tu corazón\"",
    analysis: "La confianza no es ingenuidad: es <strong>apoyarse en la roca</strong> cuando el suelo se mueve. El corazón humano busca seguridad, pero la verdadera seguridad no está en lo que se ve, sino en <strong>Quien sostiene lo que no se ve</strong>.",
    conclusion: "La confianza no es saberlo todo: es saber a Quién sostiene todo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 64,
    category: "musar",
    hebTitle: "חסד",
    latTitle: "Jesed",
    title: "La Bondad como Camino",
    ref: "Miqueas 6:8",
    hebrewText: "כִּי אִם-עֲשׂוֹת מִשְׁפָּט וְאַהֲבַת חֶסֶד",
    translation: "\"Solo hacer justicia, amar la bondad y caminar humildemente\"",
    analysis: "La bondad no es un sentimiento: es un <strong>camino</strong>. Amar la <em>jesed</em> (bondad) es <strong>practicarla</strong> con constancia. La humildad no es debilidad: es el <strong>paso seguro</strong> de quien sabe que el camino es largo.",
    conclusion: "La bondad no se siente: se camina.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 65,
    category: "musar",
    hebTitle: "משמעת עצמית",
    latTitle: "Mishmat Atzmit",
    title: "La Templanza y el Autocontrol",
    ref: "Proverbios 25:28",
    hebrewText: "עִיר פְּרוּצָה אֵין חוֹמָה",
    translation: "\"Ciudad sin muros\"",
    analysis: "La falta de autocontrol es como una <strong>ciudad sin murallas</strong>. La templanza no es represión: es <strong>construir límites</strong> para que el alma no sea saqueada por los impulsos. El dominio propio es la <strong>primera victoria</strong> antes de cualquier batalla externa.",
    conclusion: "La primera batalla no es contra el enemigo: es contra los propios muros caídos.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 66,
    category: "musar",
    hebTitle: "התמדה",
    latTitle: "Hatmadá",
    title: "La Perseverancia del Justo",
    ref: "Proverbios 24:16",
    hebrewText: "כִּי שֶׁבַע יִפּוֹל צַדִּיק וָקָם",
    translation: "\"El justo cae siete veces y se levanta\"",
    analysis: "La grandeza no está en no caer, sino en <strong>levantarse cada vez</strong>. El justo no es el que nunca tropieza: es el que <strong>siempre vuelve a levantarse</strong>. La perseverancia es la <strong>marca del alma que no se rinde</strong>.",
    conclusion: "No importa cuántas veces caigas: importa cuántas veces te levantas.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 67,
    category: "musar",
    hebTitle: "מוסר",
    latTitle: "Musar",
    title: "El Valor de la Disciplina",
    ref: "Proverbios 13:24",
    hebrewText: "וְאֹהֲבוֹ שִׁחֲרוֹ מוּסָר",
    translation: "\"El que ama a su hijo, lo disciplina\"",
    analysis: "La disciplina no es castigo: es <strong>amor que corrige</strong>. El <em>musar</em> (disciplina) es el <strong>camino hacia la sabiduría</strong>. Quien evita corregir, evita amar. La disciplina es la <strong>mano firme</strong> que endereza el camino del alma.",
    conclusion: "La disciplina no es dureza: es la firmeza del amor.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 68,
    category: "musar",
    hebTitle: "שלום",
    latTitle: "Shalom",
    title: "La Paz como Meta",
    ref: "Salmos 34:15",
    hebrewText: "בַּקֵּשׁ שָׁלוֹם וְרָדְפֵהוּ",
    translation: "\"Busca la paz y persíguela\"",
    analysis: "La paz no es un estado pasivo: es una <strong>persecución activa</strong>. No se espera la paz: se la <strong>persigue</strong>. La paz no es la ausencia de conflicto, sino la <strong>presencia de justicia</strong> que lo resuelve.",
    conclusion: "La paz no es un destino: es una persecución constante.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 69,
    category: "musar",
    hebTitle: "חכמת הלב",
    latTitle: "Jojmat HaLev",
    title: "La Sabiduría del Corazón",
    ref: "Proverbios 4:23",
    hebrewText: "מִכָּל-מִשְׁמָר נְצֹר לִבֶּךָ",
    translation: "\"Sobre toda cosa guardada, guarda tu corazón\"",
    analysis: "El corazón es el <strong>centro de la vida</strong>. No solo es el asiento de las emociones, sino la <strong>fuente de las decisiones</strong>. La sabiduría no es conocimiento: es la <strong>dirección correcta del corazón</strong>.",
    conclusion: "No guardes solo lo que sabes: guarda lo que tu corazón decide.",
    signature: "— Moré Imanuel ben Efraim",
  },
]
