import type { Tarjeta } from './tarjetasTypes'
export const TARJETAS_CABALA: Tarjeta[] = [
  {
    id: 82,
    category: "cabala",
    hebTitle: "חכמת האותיות",
    latTitle: "Jojmat HaOtiot",
    title: "Sabiduría de las Letras",
    ref: "Análisis léxico hebreo",
    hebrewText: "אֱמֶת · שֶׁקֶר",
    translation: "Emet (verdad) · Sheker (mentira)",
    analysis: "Las letras de <em>emet</em> son א (primera), מ (del medio), ת (última). La verdad abarca el proceso completo. <em>Sheker</em> (שקר) usa letras del final del alfabeto — la mentira busca aparentar conclusión sin haber transitado el camino.",
    conclusion: "La verdad no se pronuncia: se recorre.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 83,
    category: "cabala",
    hebTitle: "צמצום",
    latTitle: "Tzimtzum",
    title: "El Vacío y el Rayo (Tzimtzum)",
    ref: "Etz Jaim, Ari z\"l",
    hebrewText: "צִמְצוּם",
    translation: "Tzimtzum — Contracción divina",
    analysis: "Según el <em>Etz Jaim</em>, el Ein Sof no se ausentó; se <strong>retrajo</strong> (צמצם) para dejar un <em>chalal ha-panui</em> — un espacio vacío no de ausencia, sino de posibilidad. La contracción no es negación, sino el gesto más profundo de amor.",
    conclusion: "Dios no se alejó del mundo: se hizo humilde para que nosotros pudiéramos acercarnos.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 84,
    category: "cabala",
    hebTitle: "שבירת הכלים",
    latTitle: "Shevirat HaKelim",
    title: "La Vasija Rota (Shevirat HaKelim)",
    ref: "Etz Jaim",
    hebrewText: "שְׁבִירַת הַכֵּלִים",
    translation: "Shevirat HaKelim — Ruptura de los vasos",
    analysis: "Los <em>kelim</em> recibieron la luz del <em>Or Ein Sof</em> y se fracturaron. La cábala no llora la caída: enseña que las chispas de luz cayeron dentro de los fragmentos mismos. El <em>tikkun</em> es <strong>elevar la luz atrapada en la materia más baja</strong>.",
    conclusion: "Tu caída no fue un error: fue el lugar donde se escondió tu luz.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 85,
    category: "cabala",
    hebTitle: "סולם יעקב",
    latTitle: "Sulam Iaakov",
    title: "La Escalera de Iaakov",
    ref: "Génesis 28:12",
    hebrewText: "וְהִנֵּה סֻלָּם מֻצָּב אַרְצָה",
    translation: "\"Y he aquí una escalera apoyada en la tierra\"",
    analysis: "Iaakov ve una escalera <em>mutzav artzá</em> (apoyada en la tierra) y <em>rosho magia hashamáim</em> (su cabeza llega al cielo). La escalera es la <strong>conexión entre lo material y lo espiritual</strong>. Los ángeles suben y bajan: el movimiento es bidireccional.",
    conclusion: "La espiritualidad no es escapar del mundo: es transformarlo desde dentro.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 86,
    category: "cabala",
    hebTitle: "עשר ספירות",
    latTitle: "Eser Sefirot",
    title: "Las Diez Sefirot",
    ref: "Concepto cabalístico",
    hebrewText: "עֶשֶׂר סְפִירוֹת",
    translation: "Eser Sefirot — Las Diez Emanaciones",
    analysis: "Las <em>sefirot</em> son los <strong>canales</strong> a través de los cuales la luz divina se manifiesta en el mundo. No son dioses, sino <strong>atributos</strong> de la divinidad: Jojmá (sabiduría), Biná (entendimiento), Jesed (bondad), Gevurá (severidad), Tiferet (belleza), Netzaj (eternidad), Hod (gloria), Yesod (fundamento) y Malkut (reino).",
    conclusion: "La luz divina se viste con diez nombres para ser recibida.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 87,
    category: "cabala",
    hebTitle: "אין סוף",
    latTitle: "Ein Sof",
    title: "El Ein Sof",
    ref: "Concepto cabalístico",
    hebrewText: "אֵין סוֹף",
    translation: "Ein Sof — Sin Fin",
    analysis: "El <em>Ein Sof</em> es la <strong>infinitud divina</strong> que no puede ser capturada por ningún nombre o forma. Es el <strong>más allá</strong> de toda definición. La cábala enseña que lo que podemos conocer de Dios no es Su esencia, sino <strong>cómo se revela</strong> a través de las sefirot.",
    conclusion: "Lo que no tiene fin no puede ser atrapado: solo puede ser contemplado.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 88,
    category: "cabala",
    hebTitle: "עץ החיים",
    latTitle: "Etz Jaim",
    title: "El Árbol de la Vida",
    ref: "Concepto cabalístico",
    hebrewText: "עֵץ חַיִּים",
    translation: "Etz Jaim — Árbol de la Vida",
    analysis: "El Árbol de la Vida es el <strong>mapa de la creación</strong>, un diagrama de las diez sefirot y los caminos que las conectan. No es solo un símbolo: es una <strong>guía para el ascenso espiritual</strong> y el <strong>descenso de la luz</strong>. Quien estudia el Árbol aprende a <strong>navegar entre los mundos</strong>.",
    conclusion: "El Árbol de la Vida no es un dibujo: es un camino que se recorre.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 89,
    category: "cabala",
    hebTitle: "עולם עשייה",
    latTitle: "Olam Asiá",
    title: "El Mundo de la Acción (Asiá)",
    ref: "Concepto cabalístico",
    hebrewText: "עֲשִׂיָּה",
    translation: "Asiá — Mundo de la Acción",
    analysis: "Asiá es el <strong>mundo material</strong>, el más bajo de los cuatro mundos. Pero no es un mundo sin luz: es el <strong>lugar donde la luz se hace tangible</strong>. La acción en este mundo no es una caída: es la <strong>oportunidad de elevar</strong> lo material a través de las mitzvot.",
    conclusion: "El mundo material no es una cárcel: es un taller de luz.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 90,
    category: "cabala",
    hebTitle: "עולם יצירה",
    latTitle: "Olam Yetzirá",
    title: "El Mundo de la Formación (Yetzirá)",
    ref: "Concepto cabalístico",
    hebrewText: "יְצִירָה",
    translation: "Yetzirá — Mundo de la Formación",
    analysis: "Yetzirá es el <strong>mundo de los ángeles</strong> y las <strong>formas espirituales</strong>. Aquí la luz se viste de <strong>patrones y estructuras</strong> que luego se materializarán en Asiá. Es el <strong>lugar del diseño</strong>, donde lo que será creado toma forma en el pensamiento divino.",
    conclusion: "Antes de actuar, la luz dibuja su forma en el mundo de la formación.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 91,
    category: "cabala",
    hebTitle: "עולם בריאה",
    latTitle: "Olam Beríá",
    title: "El Mundo de la Creación (Beríá)",
    ref: "Concepto cabalístico",
    hebrewText: "בְּרִיאָה",
    translation: "Beríá — Mundo de la Creación",
    analysis: "Beríá es el <strong>mundo de los tronos</strong>, donde la luz divina se <strong>condensa por primera vez</strong> en una forma que puede ser percibida. Es el <strong>lugar del origen</strong>, donde la voluntad divina se convierte en <strong>idea</strong> antes de descender a Yetzirá.",
    conclusion: "La creación comienza cuando la voluntad se convierte en idea.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 92,
    category: "cabala",
    hebTitle: "עולם אצילות",
    latTitle: "Olam Atzilut",
    title: "El Mundo de la Emanación (Atzilut)",
    ref: "Concepto cabalístico",
    hebrewText: "אֲצִילוּת",
    translation: "Atzilut — Mundo de la Emanación",
    analysis: "Atzilut es el <strong>mundo más alto</strong>, el de la <strong>emanación directa</strong> de la luz divina. Aquí no hay separación entre el Creador y lo creado: todo es <strong>unidad esencial</strong>. Es el <strong>lugar de la identidad</strong> donde el alma reconoce que es parte de lo divino.",
    conclusion: "El origen no está lejos: es la emanación directa de lo Uno.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 93,
    category: "cabala",
    hebTitle: "ניצוץ אלוהי",
    latTitle: "Nitzotz Elohí",
    title: "La Chispa Divina en el Hombre",
    ref: "Concepto cabalístico",
    hebrewText: "נִיצוֹץ אֱלֹהִי",
    translation: "Nitzotz Elohí — Chispa Divina",
    analysis: "Cada ser humano lleva dentro una <strong>chispa de lo divino</strong> (nitzotz). Esta chispa es el <strong>testigo silencioso</strong> de nuestra verdadera identidad. El camino espiritual es <strong>descubrir y elevar</strong> esa chispa hasta que ilumine toda la vida.",
    conclusion: "No busques la luz fuera: la chispa divina ya está dentro de ti.",
    signature: "— Moré Imanuel ben Efraim",
  },
]
