import type { Tarjeta } from './tarjetasTypes'
export const TARJETAS_HEBREO: Tarjeta[] = [
  {
    id: 106,
    category: "hebreo",
    hebTitle: "אלף",
    latTitle: "Álef",
    title: "Álef (א) — La Unidad Originaria",
    ref: "Midrash Otiyot",
    hebrewText: "א",
    translation: "Álef — La primera letra, silenciosa y humilde",
    analysis: "La Álef es la única consonante que no se pronuncia por sí misma; solo <strong>porta el sonido de la vocal</strong>. Su forma está compuesta por una <em>iud</em> arriba, una <em>iud</em> abajo y una <em>vav</em> diagonal que las conecta: tres elementos que simbolizan la <strong>unidad entre cielo, tierra y el puente</strong> que los une. El Zohar enseña que la Álef representa al <em>Ein Sof</em> (el Infinito), que es el principio de todo pero no se muestra directamente. Es la humildad de lo que está antes del sonido, el origen de todo lenguaje.",
    conclusion: "La unidad no se pronuncia: se sostiene en silencio.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 107,
    category: "hebreo",
    hebTitle: "בית",
    latTitle: "Bet",
    title: "Bet (ב) — La Casa de la Creación",
    ref: "Sefer Yetzirá",
    hebrewText: "ב",
    translation: "Bet — Casa, recipiente",
    analysis: "La Bet es la segunda letra, pero la primera de la Torá: <em>Bereshit</em> (בראשית) comienza con ella. Su nombre significa \"casa\" y su forma es un cuadrado abierto por un lado, simbolizando que el mundo es la <strong>casa de Dios</strong>, pero aún abierta a la revelación. El midrash dice que la Bet fue elegida para comenzar la Torá porque representa la <strong>bendición</strong> (<em>berajá</em>) y la <strong>casa</strong> donde la creación puede habitar. Es la letra del <strong>recipiente</strong> que contiene la luz divina.",
    conclusion: "La creación es la casa donde Dios habita y nosotros aprendemos.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 108,
    category: "hebreo",
    hebTitle: "גמל",
    latTitle: "Guímel",
    title: "Guímel (ג) — El Camello que Camina",
    ref: "Midrash Otiyot",
    hebrewText: "ג",
    translation: "Guímel — Camello / beneficencia",
    analysis: "La letra Guímel tiene la forma de una <em>vav</em> con un pie que se extiende hacia la izquierda, simbolizando a una persona que <strong>camina para hacer el bien</strong>. Su nombre significa \"camello\", que es el animal que viaja largas distancias. En el alfabeto, la Guímel sigue a la Bet (la casa) y precede a la Dálet (la puerta), lo que indica que después de tener una casa, uno debe <strong>salir a hacer el bien a los demás</strong>. Es la letra de la <strong>beneficencia</strong> (guemilut jasadim).",
    conclusion: "Después de construir tu casa, camina hacia el otro.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 109,
    category: "hebreo",
    hebTitle: "דלת",
    latTitle: "Dálet",
    title: "Dálet (ד) — La Puerta del Pobre",
    ref: "Midrash Otiyot",
    hebrewText: "ד",
    translation: "Dálet — Puerta / pobre",
    analysis: "La Dálet es la cuarta letra y su forma es una <em>vav</em> con un pie horizontal hacia la derecha. Su nombre significa \"puerta\", y su diseño recuerda a una persona <strong>inclinada hacia la puerta</strong>, como un pobre que espera caridad. En la tradición, la Dálet es la <strong>puerta del alma</strong> que debe estar siempre abierta para recibir. También representa la <strong>pobreza</strong> (dalut) que nos hace conscientes de nuestra dependencia de Dios.",
    conclusion: "La puerta del alma siempre debe estar abierta a la humildad.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 110,
    category: "hebreo",
    hebTitle: "הא",
    latTitle: "Hei",
    title: "Hei (ה) — El Aliento Divino",
    ref: "Sefer Yetzirá",
    hebrewText: "ה",
    translation: "Hei — Aliento / expresión",
    analysis: "La Hei es la quinta letra, compuesta por una <em>vav</em> y una <em>iud</em> en la parte inferior. Representa el <strong>aliento</strong> que Dios insufló en la creación para dar vida. Es una de las letras que forman el Nombre de Dios (YHVH) y simboliza la <strong>expresión divina</strong> que se revela a través del <strong>aliento de vida</strong>. El midrash dice que la Hei está en el corazón de la palabra <em>hinei</em> (הִנֵּה — \"he aquí\"), que es el llamado a la presencia.",
    conclusion: "El aliento divino habita en cada inhalación consciente.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 111,
    category: "hebreo",
    hebTitle: "ויו",
    latTitle: "Vav",
    title: "Vav (ו) — El Gancho que Conecta",
    ref: "Midrash Otiyot",
    hebrewText: "ו",
    translation: "Vav — Gancho / conexión",
    analysis: "La Vav es la sexta letra, con la forma de una <strong>línea recta vertical</strong>. Es el gancho que conecta las partes superiores e inferiores. En la Torá, la Vav aparece como la primera letra de muchas palabras, actuando como <strong>conector de la narrativa</strong>. Simboliza la <strong>conexión entre el cielo y la tierra</strong>, y está presente en el Nombre de Dios como el puente entre la sabiduría y la comprensión.",
    conclusion: "La vida se construye con los ganchos invisibles del amor.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 112,
    category: "hebreo",
    hebTitle: "זין",
    latTitle: "Zain",
    title: "Zain (ז) — La Espada que Sustenta",
    ref: "Midrash Otiyot",
    hebrewText: "ז",
    translation: "Zain — Espada / sustento",
    analysis: "La Zain es la séptima letra, con forma de <em>vav</em> coronada por una <em>iud</em>. Su nombre significa \"arma\" o \"espada\", pero también comparte raíz con <em>mazón</em> (sustento). Es la letra que <strong>sostiene</strong> el mundo, pues representa el equilibrio entre la fuerza y la provisión. En el Shabbat, la Zain es la letra que recuerda que el <strong>sustento viene de lo alto</strong>, no del esfuerzo humano.",
    conclusion: "El verdadero sustento no se toma con espada: se recibe con confianza.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 113,
    category: "hebreo",
    hebTitle: "חית",
    latTitle: "Jet",
    title: "Jet (ח) — La Vida que Trasciende",
    ref: "Midrash Otiyot",
    hebrewText: "ח",
    translation: "Jet — Vida / pecado",
    analysis: "La Jet es la octava letra, con forma de <em>vav</em> y <em>zain</em> unidas por un puente. Su nombre evoca la <strong>vida</strong> (jayim) y, por su sonido gutural, el <strong>pecado</strong> (jet). Esta dualidad refleja la condición humana: la vida misma contiene la posibilidad de la falta. La Jet nos enseña que la vida no es perfección, sino el <strong>movimiento constante hacia la trascendencia</strong> incluso desde la imperfección.",
    conclusion: "La vida no es un estado: es un puente sobre la imperfección.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 114,
    category: "hebreo",
    hebTitle: "טית",
    latTitle: "Tet",
    title: "Tet (ט) — La Bondad Escondida",
    ref: "Midrash Otiyot",
    hebrewText: "ט",
    translation: "Tet — Bondad / 9",
    analysis: "La Tet es la novena letra, con forma de un <strong>útero</strong> o recipiente cerrado. Es la primera letra de la palabra <em>tov</em> (טוב — \"bueno\"), que aparece en la creación cuando Dios ve que la luz es buena. La Tet está asociada con la <strong>bondad escondida</strong> (<em>tov ha-ganuz</em>), la recompensa futura que está reservada para los justos. Es una letra que encierra el bien en su interior, esperando ser revelado.",
    conclusion: "La bondad verdadera está escondida, esperando ser descubierta.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 115,
    category: "hebreo",
    hebTitle: "יוד",
    latTitle: "Iud",
    title: "Iud (י) — La Chispa Divina",
    ref: "Sefer Yetzirá",
    hebrewText: "י",
    translation: "Iud — Chispa / mano",
    analysis: "La Iud es la décima letra, la más pequeña del alfabeto. Es la <strong>chispa</strong> de donde surge todo el universo, el punto de la creación. Es también la primera letra del Nombre de Dios (YHVH) y de la palabra <em>Israel</em>. La Iud simboliza la <strong>humildad</strong> y la <strong>presencia mínima</strong> que contiene lo infinito. Es la mano de Dios que guía la historia.",
    conclusion: "La grandeza de Dios se esconde en la chispa más pequeña.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 116,
    category: "hebreo",
    hebTitle: "כף",
    latTitle: "Kaf",
    title: "Kaf (כ) — La Palmera que se Inclina",
    ref: "Midrash Otiyot",
    hebrewText: "כ",
    translation: "Kaf — Palmera / fuerza",
    analysis: "La Kaf es la undécima letra, con forma de una <strong>palma abierta</strong> que recibe o sostiene. Su nombre significa \"palmera\", que se inclina con el viento pero no se rompe. Es la letra de la <strong>fuerza que se doblega</strong> para no quebrarse. La Kaf aparece al principio de la palabra <em>keter</em> (corona), que es la sefirá más alta, la corona de la voluntad divina.",
    conclusion: "La verdadera fuerza es la que se dobla para seguir en pie.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 117,
    category: "hebreo",
    hebTitle: "למד",
    latTitle: "Lámed",
    title: "Lámed (ל) — El Corazón que Aprende",
    ref: "Midrash Otiyot",
    hebrewText: "ל",
    translation: "Lámed — Enseñar / aprender",
    analysis: "La Lámed es la duodécima letra, la más alta del alfabeto. Es la única que se eleva por encima de las demás, simbolizando el <strong>estudio</strong> y la <strong>enseñanza</strong>. Su nombre significa \"aprender\" y \"enseñar\", y es el centro de la palabra <em>lev</em> (corazón). La Lámed es la letra del <strong>corazón que estudia</strong> y del <strong>maestro que eleva a los demás</strong>.",
    conclusion: "El corazón que enseña es el que nunca deja de aprender.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 118,
    category: "hebreo",
    hebTitle: "מם",
    latTitle: "Mem",
    title: "Mem (מ) — El Agua de la Vida",
    ref: "Sefer Yetzirá",
    hebrewText: "מ",
    translation: "Mem — Agua / 40",
    analysis: "La Mem es la decimotercera letra, con forma de un <strong>surtidor de agua</strong>. Su nombre significa \"agua\", que es el símbolo de la Torá y la vida. La Mem tiene una forma abierta y una cerrada (final), representando los <strong>dos niveles del agua</strong>: la que corre superficialmente y la que brota desde las profundidades. Es la letra del <strong>mikvé</strong> (baño ritual) y de la <strong>purificación</strong>.",
    conclusion: "El agua que fluye es la Torá que brota en el corazón.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 119,
    category: "hebreo",
    hebTitle: "נון",
    latTitle: "Nun",
    title: "Nun (נ) — El Pez que Nada en lo Oculto",
    ref: "Midrash Otiyot",
    hebrewText: "נ",
    translation: "Nun — Pez / 50",
    analysis: "La Nun es la decimocuarta letra, con forma de un <strong>pez</strong> o una <strong>serpiente</strong>. Su nombre significa \"descendencia\" y también \"pez\", que vive en las profundidades del agua. La Nun es la letra de la <strong>vida oculta</strong>, de la <strong>nube</strong> que guió a Israel en el desierto. Es el inicio de la palabra <em>nefesh</em> (alma) y <em>neshamá</em> (aliento divino).",
    conclusion: "La vida profunda no se ve en la superficie: se nada en lo oculto.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 120,
    category: "hebreo",
    hebTitle: "סמך",
    latTitle: "Sámaj",
    title: "Sámaj (ס) — El Círculo que Sostiene",
    ref: "Midrash Otiyot",
    hebrewText: "ס",
    translation: "Sámaj — Sostener / 60",
    analysis: "La Sámaj es la decimoquinta letra, con forma de <strong>círculo</strong> que contiene todo en su interior. Su nombre significa \"sostener\" o \"apoyar\", y es la letra del <strong>soporte divino</strong>. Es la única letra que puede formar un círculo completo, simbolizando que Dios <strong>sostiene todo el universo</strong> en Su mano. La Sámaj es también la letra de la <strong>memoria</strong> (zicaron) y del <strong>sustento</strong> (misján).",
    conclusion: "Dios es el círculo que sostiene todo lo que existe.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 121,
    category: "hebreo",
    hebTitle: "עין",
    latTitle: "Ain",
    title: "Ain (ע) — El Ojo que Ve lo Invisible",
    ref: "Midrash Otiyot",
    hebrewText: "ע",
    translation: "Ain — Ojo / 70",
    analysis: "La Ain es la decimosexta letra, con forma de un <strong>ojo</strong>. Su nombre significa \"ojo\", y representa la <strong>visión espiritual</strong> que ve más allá de la apariencia. La Ain es la letra de la <strong>profecía</strong> y de la <strong>intuición</strong>. Está asociada con el número 70, que corresponde a las 70 naciones y a los 70 rostros de la Torá. Es el ojo que ve la unidad detrás de la multiplicidad.",
    conclusion: "El verdadero ojo no ve lo que es, sino lo que puede ser.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 122,
    category: "hebreo",
    hebTitle: "פה",
    latTitle: "Pei",
    title: "Pei (פ) — La Boca que Habla",
    ref: "Midrash Otiyot",
    hebrewText: "פ",
    translation: "Pei — Boca / 80",
    analysis: "La Pei es la decimoséptima letra, con forma de una <strong>boca</strong>. Su nombre significa \"boca\", y es la letra de la <strong>palabra hablada</strong>. Representa la capacidad humana de <strong>expresar</strong> lo que está en el corazón. La Pei tiene dos formas: una abierta y una cerrada (final), que simbolizan la diferencia entre la palabra que se dice y la que se guarda. Es la letra de la <strong>oración</strong> (tefilá) y de la <strong>profecía</strong>.",
    conclusion: "La boca que habla es el puente entre el alma y el mundo.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 123,
    category: "hebreo",
    hebTitle: "צדיק",
    latTitle: "Tzadi",
    title: "Tzadi (צ) — El Justo que se Inclina",
    ref: "Midrash Otiyot",
    hebrewText: "צ",
    translation: "Tzadi — Justo / 90",
    analysis: "La Tzadi es la decimoctava letra, con forma de una persona <strong>inclinada</strong> hacia la derecha. Su nombre significa \"justo\" (tzadik), y es la letra de la <strong>rectitud</strong>. La Tzadi tiene dos formas: una abierta y una cerrada (final), que simbolizan al justo que se inclina para escuchar y al justo que se mantiene firme. Es la letra de la <strong>humildad del justo</strong> que se dobla para recoger las chispas de luz.",
    conclusion: "El justo no es el que se mantiene erguido, sino el que se inclina para levantar.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 124,
    category: "hebreo",
    hebTitle: "קוף",
    latTitle: "Kuf",
    title: "Kuf (ק) — El Monje que Busca",
    ref: "Midrash Otiyot",
    hebrewText: "ק",
    translation: "Kuf — Monje / 100",
    analysis: "La Kuf es la decimonovena letra, con forma de <em>vav</em> y <em>zain</em> separadas, como una persona que <strong>busca</strong> en todas direcciones. Su nombre significa \"mono\" o \"aguja\", y simboliza la <strong>búsqueda</strong> constante de lo sagrado. La Kuf es la letra de la <strong>pregunta</strong> y de la <strong>curiosidad</strong> espiritual. Es la búsqueda del <strong>Kadosh</strong> (Santo) que está más allá de lo visible.",
    conclusion: "La búsqueda de lo sagrado es la única pregunta que no cesa.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 125,
    category: "hebreo",
    hebTitle: "ריש",
    latTitle: "Reish",
    title: "Reish (ר) — La Cabeza que Piensa",
    ref: "Midrash Otiyot",
    hebrewText: "ר",
    translation: "Reish — Cabeza / 200",
    analysis: "La Reish es la vigésima letra, con forma de <strong>cabeza</strong>. Su nombre significa \"cabeza\" y es la letra del <strong>pensamiento</strong> y del <strong>liderazgo</strong>. Es la primera letra de la palabra <em>rosh</em> (cabeza), que es el principio de todo. La Reish está asociada con el <strong>raciocinio</strong> y la <strong>dirección</strong>. Es también la letra de <em>reshut</em> (dominio) y de <em>reshimá</em> (inscripción), el acto de marcar el pensamiento.",
    conclusion: "El pensamiento es la cabeza de toda acción.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 126,
    category: "hebreo",
    hebTitle: "שין",
    latTitle: "Shin",
    title: "Shin (ש) — El Diente que Muerde",
    ref: "Midrash Otiyot",
    hebrewText: "ש",
    translation: "Shin — Diente / 300",
    analysis: "La Shin es la vigésimo primera letra, con forma de <strong>dientes</strong>. Su nombre significa \"diente\", y representa la <strong>fuerza</strong> y la <strong>transformación</strong>. Es la letra del <em>Shadai</em> (Todopoderoso) y del <em>Shalom</em> (paz). La Shin tiene tres cabezas, que simbolizan los <strong>tres mundos</strong> (Asiá, Yetzirá, Beríá) o los <strong>tres patriarcas</strong>. Es la letra del <strong>fuego</strong> que transforma y purifica.",
    conclusion: "El diente que muerde la materia la transforma en luz.",
    signature: "— Moré Imanuel ben Efraim",
  },
  {
    id: 127,
    category: "hebreo",
    hebTitle: "תו",
    latTitle: "Tav",
    title: "Tav (ת) — La Señal de la Verdad",
    ref: "Midrash Otiyot",
    hebrewText: "ת",
    translation: "Tav — Señal / 400",
    analysis: "La Tav es la última letra del alfabeto, con forma de <strong>cruz</strong> o <strong>marca</strong>. Su nombre significa \"señal\", y es la letra de la <strong>verdad</strong> (emet), que comienza con Álef, tiene Mem en medio y termina con Tav. La Tav representa el <strong>sello</strong> de la creación, la marca de la <strong>perfección</strong> y el <strong>cumplimiento</strong>. Es la letra del <em>tikkun</em> (reparación) y del <em>ta'am</em> (sabor). Es el final que contiene el principio.",
    conclusion: "La verdad es el sello que cierra el círculo del ser.",
    signature: "— Moré Imanuel ben Efraim",
  },
]
